begin;
select extensions.no_plan();
create temporary table timing_actors(alias text primary key,auth_id uuid default gen_random_uuid(),profile_id uuid);
create temporary table timing_ids(key text primary key,id uuid,payload jsonb);
grant select,insert,update on timing_actors,timing_ids to authenticated;
insert into timing_actors(alias)values('admin'),('other_admin'),('worker'),('peer'),('outsider');
insert into auth.users(instance_id,id,aud,role,email,encrypted_password,email_confirmed_at,raw_app_meta_data,raw_user_meta_data,created_at,updated_at)
select '00000000-0000-0000-0000-000000000000',auth_id,'authenticated','authenticated',alias||'-task-timing@example.invalid','',now(),'{}','{}',now(),now()from timing_actors;
update timing_actors a set profile_id=p.id from public.profiles p where p.auth_user_id=a.auth_id;
create function pg_temp.login(a text)returns void language sql as $$select set_config('request.jwt.claim.sub',(select auth_id::text from timing_actors where alias=a),true)::void$$;
create function pg_temp.uid(k text)returns uuid language sql as $$select id from timing_ids where key=k$$;
create function pg_temp.day()returns date language sql as $$select(statement_timestamp()at time zone 'Europe/Amsterdam')::date$$;
create function pg_temp.upsert(k text,d date,t time default null,assignee text default 'worker',horse uuid default null,existing uuid default null,version bigint default null,rid uuid default null)returns jsonb language sql as $$
select public.upsert_c010_stable_task(pg_temp.uid('org'),existing,version,k,'Controleer en meld terug','other',d,t,(select profile_id from timing_actors where alias=assignee),'Stalgang',null,horse,coalesce(rid,gen_random_uuid()))$$;
create function pg_temp.personal(k text,d date default null)returns jsonb language sql as $$select v from jsonb_array_elements(public.get_c010_personal_day(d)->'items')v where v->>'task_id'=pg_temp.uid(k)::text$$;
create function pg_temp.stable(k text,d date default null,scope text default 'all')returns jsonb language sql as $$select v from jsonb_array_elements(public.get_c010_stable_round1_workspace(pg_temp.uid('org'),d,scope)->'activities')v where v->>'activity_id'=pg_temp.uid(k)::text$$;
select set_config('request.jwt.claim.role','authenticated',true);
set local role authenticated;
select pg_temp.login('admin');
insert into timing_ids select 'org',(public.create_c010_stable('Timing A','Fictief',gen_random_uuid())->>'organization_id')::uuid,null;
select pg_temp.login('other_admin');
insert into timing_ids select 'foreign',(public.create_c010_stable('Timing B','Fictief',gen_random_uuid())->>'organization_id')::uuid,null;
do $$declare who text;inv record;accepted record;begin foreach who in array array['worker','peer']loop
 perform pg_temp.login('admin');select*into inv from public.create_c010_stable_invitation(pg_temp.uid('org'),'groom',who||'-task-timing@example.invalid',now()+interval'7 days',gen_random_uuid());
 perform pg_temp.login(who);select*into accepted from public.respond_stable_invitation(inv.invitation_token,'accept',gen_random_uuid());insert into timing_ids values('member_'||who,accepted.membership_id,null);
end loop;end$$;
select pg_temp.login('admin');
insert into timing_ids select 'horse',horse_id,null from public.create_canonical_horse_profile('Timing paard',null,null,'unknown',null,null,null,null,null,null,null,null,gen_random_uuid());
select public.set_c010_horse_residency(pg_temp.uid('horse'),pg_temp.uid('org'),null,gen_random_uuid());
insert into timing_ids select 'viewgrant',grant_id,null from public.grant_horse_profile_permission(pg_temp.uid('horse'),(select profile_id from timing_actors where alias='worker'),'horse.view',null,null,null,'MANUAL_GRANT',gen_random_uuid());
-- END_FIXTURE_SETUP (before-migration probe reuses only this setup in rollback)
insert into timing_ids values('general_request',gen_random_uuid(),null);
insert into timing_ids select 'general',(r->>'task_id')::uuid,r from(select pg_temp.upsert('Looppad vegen',null,null,'worker',null,null,null,pg_temp.uid('general_request'))r)s;
select extensions.ok((select payload->>'row_version'='1'from timing_ids where key='general'),'undated general task is created through existing RPC');
select extensions.ok(pg_temp.upsert('Looppad vegen',null,null,'worker',null,null,null,pg_temp.uid('general_request'))->>'idempotent'='true','null timing survives idempotent replay');
insert into timing_ids select 'today',(r->>'task_id')::uuid,r from(select pg_temp.upsert('Vandaag zonder tijd',pg_temp.day())r)s;
insert into timing_ids select 'tomorrow',(r->>'task_id')::uuid,r from(select pg_temp.upsert('Morgen zonder tijd',pg_temp.day()+1)r)s;
insert into timing_ids select 'timed',(r->>'task_id')::uuid,r from(select pg_temp.upsert('Bak slepen',pg_temp.day()+1,'12:00')r)s;
insert into timing_ids select 'peer',(r->>'task_id')::uuid,r from(select pg_temp.upsert('Anders toegewezen',null,null,'peer')r)s;
insert into timing_ids select 'linked',(r->>'task_id')::uuid,r from(select pg_temp.upsert('Algemeen bij paard',null,null,'worker',pg_temp.uid('horse'))r)s;
select extensions.throws_ok('select pg_temp.upsert(''Losse tijd'',null,''12:00'')','22023','C010_TASK_INPUT_INVALID','time without date refused by actual RPC');
select extensions.ok(pg_temp.stable('general')->>'due_date'is null and pg_temp.stable('general')->>'due_time'is null and pg_temp.stable('general')->>'scheduled_at'is null,'general task has no invented date/time/midnight');
select extensions.ok(pg_temp.stable('general',pg_temp.day()+60)is not null,'general visible in selected future stable day');
select extensions.ok(pg_temp.stable('general',pg_temp.day()-60)is not null,'general visible when reviewing earlier stable day');
select extensions.ok(pg_temp.stable('today')->>'due_time'is null and pg_temp.stable('today')->>'scheduled_at'is null,'date-only today task does not become midnight');
select extensions.ok(pg_temp.stable('tomorrow')is null and pg_temp.stable('tomorrow',pg_temp.day()+1)is not null,'future day-only task appears on its actual day only');
select extensions.ok(pg_temp.stable('timed',pg_temp.day()+1)->>'due_time'='12:00:00','time task retains noon');
select extensions.ok(pg_temp.stable('timed')is null,'tomorrow noon task not shown as today');
select extensions.ok(pg_temp.stable('general')->>'location_name'='Stalgang' and pg_temp.stable('general')->>'horse_id'is null,'free location and optional horse remain valid');
select extensions.ok(pg_temp.stable('linked')->>'horse_id'=pg_temp.uid('horse')::text,'authorized horse link remains valid without date');
select extensions.ok(pg_temp.personal('general')is null,'management alone does not put somebody else task into personal day');
select pg_temp.login('worker');
select extensions.ok(pg_temp.personal('general')is not null and pg_temp.personal('general',pg_temp.day()+60)is not null,'own open general task appears across selected personal days');
select extensions.ok(pg_temp.personal('general')->>'due_date'is null and pg_temp.personal('general')->>'due_time'is null and pg_temp.personal('general')->>'scheduled_start_at'is null,'personal general task has no timestamp');
select extensions.ok(pg_temp.personal('peer')is null,'another assignee general task excluded from personal day');
select extensions.ok(pg_temp.personal('today')is not null and pg_temp.personal('tomorrow')is null,'own normal daily selection unchanged');
select extensions.ok(pg_temp.personal('tomorrow',pg_temp.day()+1)is not null and pg_temp.personal('timed',pg_temp.day()+1)->>'due_time'='12:00:00','personal future day/time tasks loaded by explicit date');
select extensions.ok(pg_temp.stable('peer')is not null and pg_temp.stable('peer',null,'mine')is null,'stable all versus mine filter unchanged for general tasks');
select extensions.ok(pg_temp.personal('linked')is not null,'linked general task visible with explicit horse view');
select extensions.ok((select count(*)=count(distinct v->>'source_id')from jsonb_array_elements(public.get_c010_personal_day()->'items')v),'no duplicate task registry or projection rows');
select pg_temp.login('peer');
select extensions.ok(pg_temp.stable('linked')is null,'stable member without explicit horse view cannot read linked general task');
select extensions.throws_ok(format('select public.transition_c010_stable_task(%L,%L,1,''complete'',%L)',pg_temp.uid('org'),pg_temp.uid('general'),gen_random_uuid()),'42501','TASK_COMPLETION_PERMISSION_REQUIRED','nonassignee cannot complete general task');
select pg_temp.login('outsider');
select extensions.throws_ok('select pg_temp.stable(''general'')','42501','ORGANIZATION_PERMISSION_REQUIRED','outsider cannot read stable general tasks');
select extensions.throws_ok('select pg_temp.upsert(''Unauthorized'',null)','42501','STABLE_TASK_MANAGE_PERMISSION_REQUIRED','outsider cannot create undated task');
select pg_temp.login('other_admin');
select extensions.throws_ok('select pg_temp.stable(''general'')','42501','ORGANIZATION_PERMISSION_REQUIRED','other-stable owner cannot read general tasks');
select pg_temp.login('admin');
select extensions.ok(pg_temp.upsert('Looppad vegen',pg_temp.day()+2,'13:00','worker',null,pg_temp.uid('general'),1)->>'row_version'='2','general can be scheduled using existing CAS update');
select extensions.ok(pg_temp.stable('general')is null and pg_temp.stable('general',pg_temp.day()+2)->>'due_time'='13:00:00','new scheduled day is authoritative after reread');
select extensions.throws_ok(format('select pg_temp.upsert(''Looppad vegen'',null,null,''worker'',null,%L,1)',pg_temp.uid('general')),'PT409','STALE_TASK_VERSION','stale timing edit preserves business409');
select extensions.ok(pg_temp.upsert('Looppad vegen',null,null,'worker',null,pg_temp.uid('general'),2)->>'row_version'='3','schedule can be cleared to genuine general todo');
select extensions.ok(pg_temp.stable('general',pg_temp.day()+2)->>'due_date'is null and pg_temp.stable('general')->>'note'='Controleer en meld terug','clearing timing retains original instruction');
select public.transition_horse_profile_permission_grant(pg_temp.uid('viewgrant'),1,'revoke','MANUAL_REVOKE',gen_random_uuid());
select pg_temp.login('worker');
select extensions.ok(pg_temp.personal('linked')is null,'revoked explicit horse view immediately hides undated task');
select extensions.throws_ok(format('select public.transition_c010_stable_task(%L,%L,1,''complete'',%L)',pg_temp.uid('org'),pg_temp.uid('linked'),gen_random_uuid()),'42501','TASK_VISIBILITY_PERMISSION_REQUIRED','revoked horse view prevents undated completion');
insert into timing_ids values('complete_request',gen_random_uuid(),null);
select extensions.ok(public.transition_c010_stable_task(pg_temp.uid('org'),pg_temp.uid('general'),3,'complete',pg_temp.uid('complete_request'))->>'row_version'='4','assignee completes general task');
select extensions.ok(public.transition_c010_stable_task(pg_temp.uid('org'),pg_temp.uid('general'),3,'complete',pg_temp.uid('complete_request'))->>'idempotent'='true','completion replay does not repeat terminal event');
select extensions.ok(pg_temp.personal('general')is null and pg_temp.personal('general',pg_temp.day()+60)is null,'completed general removed from personal open-todo list on every day');
select extensions.ok(pg_temp.stable('general')->>'status'='completed' and pg_temp.stable('general',pg_temp.day()+60)->>'status'='completed','completed general history retained in stable workspace');
select pg_temp.login('admin');
select public.revoke_c010_membership(pg_temp.uid('org'),pg_temp.uid('member_worker'),1,gen_random_uuid());
select pg_temp.login('worker');
select extensions.ok(pg_temp.personal('tomorrow',pg_temp.day()+1)is null,'ended membership hides own scheduled tasks');
select extensions.throws_ok('select pg_temp.stable(''general'')','42501','ORGANIZATION_PERMISSION_REQUIRED','ended membership hides general-task history');
reset role;
select set_config('request.jwt.claim.sub','',true);
select extensions.is((select count(*)from public.stable_task_events where task_id=pg_temp.uid('general')and event_type='completed'),1::bigint,'exactly one completion event remains');
select extensions.throws_ok(format('update public.stable_tasks set due_time=''11:00'' where id=%L',pg_temp.uid('peer')),'23514',null,'database constraint independently rejects time without date');
select extensions.ok(not has_function_privilege('anon','public.upsert_c010_stable_task(uuid,uuid,bigint,text,text,text,date,time,uuid,text,uuid,uuid,uuid)','EXECUTE'),'anonymous write ACL unchanged');
select*from extensions.finish();
rollback;
