begin;
select extensions.no_plan();
create temporary table p2_actors(alias text primary key,auth_id uuid default gen_random_uuid(),profile_id uuid);
create temporary table p2_ids(key text primary key,id uuid,payload jsonb);
grant select,insert,update on p2_actors,p2_ids to authenticated;
insert into p2_actors(alias) values('admin'),('other'),('rider'),('groom'),('outsider');
insert into auth.users(instance_id,id,aud,role,email,encrypted_password,email_confirmed_at,raw_app_meta_data,raw_user_meta_data,created_at,updated_at)
select '00000000-0000-0000-0000-000000000000',auth_id,'authenticated','authenticated',alias||'-p2-contract@example.invalid','',now(),'{}','{}',now(),now() from p2_actors;
update p2_actors a set profile_id=p.id from public.profiles p where p.auth_user_id=a.auth_id;
create function pg_temp.login(a text) returns void language sql as $$ select set_config('request.jwt.claim.sub',(select auth_id::text from p2_actors where alias=a),true)::void $$;
create function pg_temp.uid(k text) returns uuid language sql as $$select id from p2_ids where key=k$$;
create function pg_temp.day() returns date language sql as $$select (statement_timestamp() at time zone 'Europe/Amsterdam')::date+1$$;
create function pg_temp.ws() returns jsonb language sql as $$select public.get_c010_facility_workspace(pg_temp.uid('org'),pg_temp.day())$$;
create function pg_temp.booking(k text,resource text,start_at time,end_at time,horse text default null,n integer default 1,whole boolean default false,description text default 'Fictieve reservering') returns jsonb language plpgsql as $$declare r jsonb;begin
 r:=public.save_c010_facility_booking(pg_temp.uid('org'),null,null,pg_temp.uid(resource),pg_temp.day(),start_at,end_at,case when horse is null then '{}'::uuid[] else array[pg_temp.uid(horse)] end,n,'Oefenen',description,whole,gen_random_uuid());
 insert into p2_ids values(k,(r->>'booking_id')::uuid,r);return r;end$$;
create function pg_temp.config(walker_capacity integer default 4,boxes integer default 2) returns jsonb language sql as $$select public.configure_c010_facilities(pg_temp.uid('org'),(pg_temp.ws()->'configuration'->>'row_version')::bigint,jsonb_build_object('stall',boxes,'pasture',1,'paddock',1,'arena',1,'walker',1,'wash',1,'locker',1),walker_capacity,true,gen_random_uuid())$$;
select extensions.ok(not has_table_privilege('authenticated','public.c010_facility_bookings','SELECT'),'booking table cannot bypass redacting projection');
select extensions.ok(not has_table_privilege('authenticated','public.c010_horse_places','SELECT'),'placement table cannot expose hidden horse IDs');
select extensions.ok(not has_table_privilege('authenticated','public.c010_facility_units','UPDATE'),'client cannot directly update resource');
select extensions.ok(not has_function_privilege('anon','public.get_c010_facility_workspace(uuid,date)','EXECUTE'),'anonymous workspace invocation denied');
select extensions.ok(not has_function_privilege('authenticated','private.c010p2_capacity(uuid,date,time,time,integer,boolean,uuid)','EXECUTE'),'private capacity helper not callable by clients');
select extensions.ok((select bool_and(relrowsecurity) from pg_class where oid in('public.c010_facility_units'::regclass,'public.c010_horse_places'::regclass,'public.c010_facility_bookings'::regclass,'public.c010_facility_booking_horses'::regclass)),'RLS enabled on every new public table');
select extensions.ok(not private.c010p2_civil_time('2027-03-28','02:30'),'DST skipped Amsterdam wall time refused');
select extensions.ok(not private.c010p2_civil_time('2026-10-25','02:30'),'DST repeated Amsterdam wall time refused');
select extensions.ok(private.c010p2_civil_time('2026-10-25','03:30'),'unambiguous wall time after DST accepted');
select extensions.ok(not private.c010p2_civil_time('infinity','12:00') and not private.c010p2_civil_time('2026-09-11','24:00'),'infinite date and midnight24 invalid');
select set_config('request.jwt.claim.role','authenticated',true);
set local role authenticated;
select pg_temp.login('admin');
insert into p2_ids select 'org',(public.create_c010_stable('P2 contract stal','Local',gen_random_uuid())->>'organization_id')::uuid,null;
select pg_temp.login('other');
insert into p2_ids select 'foreign',(public.create_c010_stable('P2 foreign stal','Local',gen_random_uuid())->>'organization_id')::uuid,null;
select pg_temp.login('admin');
do $$declare who text;inv record;accepted record;begin foreach who in array array['rider','groom'] loop
 perform pg_temp.login('admin');select * into inv from public.create_c010_stable_invitation(pg_temp.uid('org'),who,who||'-p2-contract@example.invalid',now()+interval '7 days',gen_random_uuid());
 perform pg_temp.login(who);select * into accepted from public.respond_stable_invitation(inv.invitation_token,'accept',gen_random_uuid());insert into p2_ids values('member_'||who,accepted.membership_id,null);
end loop;end$$;
select pg_temp.login('admin');
insert into p2_ids select 'horse',horse_id,null from public.create_canonical_horse_profile('P2 zichtbaar paard',null,null,'unknown',null,null,null,null,null,null,null,null,gen_random_uuid());
insert into p2_ids select 'hidden',horse_id,null from public.create_canonical_horse_profile('P2 afgeschermd paard',null,null,'unknown',null,null,null,null,null,null,null,null,gen_random_uuid());
select public.set_c010_horse_residency(id,pg_temp.uid('org'),null,gen_random_uuid()) from p2_ids where key in('horse','hidden');
select public.set_c010_horse_collaborator(pg_temp.uid('horse'),profile_id,'trainer',array['horse.view','horse.planning.manage'],true,gen_random_uuid()) from p2_actors where alias='rider';
select extensions.ok(pg_temp.config()->>'row_version' is not null,'manager creates existing box configuration and physical units');
insert into p2_ids select item->>'kind'||coalesce(item->>'number','1'),(item->>'id')::uuid,item from jsonb_array_elements(pg_temp.ws()->'resources') item;
select extensions.is(jsonb_array_length(pg_temp.ws()->'resources'),8,'two canonical boxes and six nonbox resources');
select extensions.ok(pg_temp.ws()->'calendar'->'covered_dates' @> jsonb_build_array(pg_temp.day(),(statement_timestamp() at time zone 'Europe/Amsterdam')::date),'selected day plus actual Today coverage');
select extensions.ok(public.update_c010_facility_unit(pg_temp.uid('org'),pg_temp.uid('stall1'),(select (payload->>'rowVersion')::bigint from p2_ids where key='stall1'),'Stal 1 · naam','Grote box','available',1,'Boxnotitie',gen_random_uuid())->>'row_version' is not null,'box metadata writes through existing canonical box');
select extensions.ok(exists(select 1 from jsonb_array_elements(pg_temp.ws()->'resources') r where r->>'id'=pg_temp.uid('stall1')::text and r->>'type'='Grote box' and r->>'note'='Boxnotitie'),'box metadata returned after reread');
select public.update_c010_facility_unit(pg_temp.uid('org'),pg_temp.uid('stall1'),2,'Stal 1 · naam','Grote box','maintenance',1,'Boxnotitie',gen_random_uuid());
select extensions.throws_ok(format('select public.set_c010_horse_place(%L,%L,%L,null,%L,%L)',pg_temp.uid('org'),pg_temp.uid('horse'),pg_temp.uid('stall1'),'',gen_random_uuid()),'42501','C010_FACILITY_UNAVAILABLE','maintenance box refused by RPC independent of UI');
select public.update_c010_facility_unit(pg_temp.uid('org'),pg_temp.uid('stall1'),3,'Stal 1 · naam','Grote box','available',1,'Boxnotitie',gen_random_uuid());
select extensions.ok(public.set_c010_horse_place(pg_temp.uid('org'),pg_temp.uid('hidden'),pg_temp.uid('stall2'),null,'Privé paardeninstructie',gen_random_uuid())->>'status'='active','manager assigns hidden horse to box');
select extensions.throws_ok('select pg_temp.config(4,1)','PT409','C010_FACILITY_HAS_HISTORY','cannot shrink past occupied box');
select extensions.throws_ok(format('select public.set_c010_horse_place(%L,%L,%L,null,%L,%L)',pg_temp.uid('org'),pg_temp.uid('horse'),pg_temp.uid('stall2'),'',gen_random_uuid()),'PT409','C010_PLACE_OCCUPIED','occupied box cannot be double assigned');
select pg_temp.login('groom');
select extensions.ok(exists(select 1 from jsonb_array_elements(pg_temp.ws()->'resources') r where r->>'id'=pg_temp.uid('stall2')::text and r->>'occupied'='true'),'hidden horse box still visibly occupied');
select extensions.ok(exists(select 1 from jsonb_array_elements(pg_temp.ws()->'placements') p where p->>'resourceId'=pg_temp.uid('stall2')::text and p->>'horseId' is null and p->>'note'='' and p->>'redacted'='true'),'hidden placement has no horse identity or private note');
select extensions.ok(pg_temp.ws()->'placementVersions'='{}'::jsonb,'hidden horses absent from placement version map');
select extensions.ok(public.save_my_c010_function_profile(array['manager','vet'],null,gen_random_uuid())->>'row_version'='1','own multi-function preference stored');
select extensions.ok(pg_temp.ws()->'capabilities'->>'manage'='false' and pg_temp.ws()->'capabilities'->>'book'='false','preferred manager or vet function grants no authority');
select extensions.throws_ok('select pg_temp.config()','42501','C010_FACILITY_MANAGE_REQUIRED','groom cannot configure');
select extensions.throws_ok('select public.save_my_c010_function_profile(array[''rider''],null,gen_random_uuid())','PT409','C010_FUNCTION_VERSION_STALE','preferences require current CAS');
select extensions.throws_ok('select public.save_my_c010_function_profile(''{}''::text[],1,gen_random_uuid())','22023','C010_FUNCTION_CHOICES_INVALID','zero functions refused');
select pg_temp.login('outsider');
select extensions.throws_ok('select pg_temp.ws()','42501','C010_FACILITY_ACCESS_REQUIRED','outsider cannot read foreign stable workspace');
select pg_temp.login('rider');
select extensions.throws_ok(format('select public.get_c010_facility_workspace(%L,null)',pg_temp.uid('foreign')),'42501','C010_FACILITY_ACCESS_REQUIRED','member of A cannot read B');
select extensions.ok(pg_temp.ws()->'capabilities'->>'book'='true','rider with explicit planning and resident horse may book arena');
select extensions.ok(pg_temp.booking('shared','arena1','09:00','10:00','horse',2)->>'status'='approved','shared arena automatically approved within capacity');
select extensions.ok(pg_temp.booking('adjacent','arena1','10:00','11:00','horse',4)->>'status'='approved','half-open adjacent booking is allowed');
select extensions.throws_ok('select pg_temp.booking(''hidden_try'',''arena1'',''12:00'',''13:00'',''hidden'',1)','42501','C010_HORSE_CONTEXT_REQUIRED','rider cannot book hidden horse');
select extensions.throws_ok('select pg_temp.booking(''pasture_try'',''pasture1'',''12:00'',''13:00'',''horse'',1)','42501','C010_FACILITY_MANAGE_REQUIRED','nonmanager cannot manage pasture allocation');
select extensions.ok(pg_temp.booking('whole','arena1','14:00','15:00',null,1,true,'Private lesaanvraag')->>'status'='requested','exclusive request always requires decision');
select extensions.throws_ok(format('select public.transition_c010_facility_booking(%L,%L,1,''approve'','''',%L)',pg_temp.uid('org'),pg_temp.uid('whole'),gen_random_uuid()),'42501','C010_FACILITY_MANAGE_REQUIRED','requester cannot self approve exclusive use');
select pg_temp.login('groom');
select extensions.ok(not exists(select 1 from jsonb_array_elements(pg_temp.ws()->'arenaBookings') b where b->>'id'=pg_temp.uid('whole')::text),'other users cannot see pending no-horse request');
select extensions.ok(exists(select 1 from jsonb_array_elements(pg_temp.ws()->'arenaBookings') b where b->>'id'=pg_temp.uid('shared')::text and b->>'participants'='2' and b->>'note'='' and b->>'requesterId' is null and b->'horseIds'='[]'::jsonb),'approved anonymous occupancy retains full capacity and strips identity/note');
select pg_temp.login('admin');
select extensions.throws_ok('select pg_temp.booking(''capacity_try'',''arena1'',''09:30'',''09:45'',null,3)','PT409','C010_FACILITY_CAPACITY_CONFLICT','overlap exceeding capacity refused');
select extensions.ok(public.transition_c010_facility_booking(pg_temp.uid('org'),pg_temp.uid('whole'),1,'approve','Ruimte vrij',gen_random_uuid())->>'status'='approved','manager explicitly approves exclusive request');
select extensions.throws_ok('select pg_temp.booking(''exclusive_try'',''arena1'',''14:30'',''15:30'',null,1)','PT409','C010_FACILITY_CAPACITY_CONFLICT','exclusive approval consumes entire arena capacity');
select extensions.throws_ok(format('select public.update_c010_facility_unit(%L,%L,1,''Rijbak'','''',''maintenance'',4,'''',%L)',pg_temp.uid('org'),pg_temp.uid('arena1'),gen_random_uuid()),'PT409','C010_FACILITY_HAS_PLANNING','resource cannot become unavailable over upcoming planning');
select extensions.ok(pg_temp.booking('walker','walker1','12:00','13:00','horse',1)->>'status'='approved','manager walker reservation saved');
select extensions.ok(pg_temp.config(2)->>'row_version' is not null,'safe walker capacity update accepted');
select extensions.ok(exists(select 1 from jsonb_array_elements(pg_temp.ws()->'resources') r where r->>'kind'='walker' and r->>'capacity'='2'),'walker configuration synchronizes existing unit capacity');
select extensions.ok(pg_temp.booking('walker_hidden','walker1','12:00','13:00','hidden',1)->>'status'='approved','second walker participant consumes remaining capacity');
select extensions.throws_ok('select pg_temp.config(1)','PT409','C010_FACILITY_CAPACITY_CONFLICT','walker reduction that conflicts with reservations rolls back');
select extensions.ok(pg_temp.ws()->'configuration'->>'walker_capacity'='2','failed reduction leaves configuration intact');
select pg_temp.login('rider');
insert into p2_ids values('cancel_request',gen_random_uuid(),null);
select extensions.ok(public.transition_c010_facility_booking(pg_temp.uid('org'),pg_temp.uid('shared'),1,'cancel','Plan vervallen',pg_temp.uid('cancel_request'))->>'row_version'='2','requester cancels own booking with CAS');
select extensions.ok(public.transition_c010_facility_booking(pg_temp.uid('org'),pg_temp.uid('shared'),1,'cancel','Plan vervallen',pg_temp.uid('cancel_request'))->>'idempotent'='true','same cancellation request replays one terminal change');
select extensions.throws_ok(format('select public.transition_c010_facility_booking(%L,%L,1,''cancel'',''Anders'',%L)',pg_temp.uid('org'),pg_temp.uid('shared'),pg_temp.uid('cancel_request')),'22023','C010_P2_IDEMPOTENCY_CONFLICT','request ID cannot be reused for changed payload');
select extensions.throws_ok(format('select public.transition_c010_facility_booking(%L,%L,1,''cancel'','''',%L)',pg_temp.uid('org'),pg_temp.uid('shared'),gen_random_uuid()),'PT409','C010_BOOKING_VERSION_STALE','stale cancellation returns business409');
select pg_temp.login('admin');
select extensions.ok(public.revoke_c010_membership(pg_temp.uid('org'),pg_temp.uid('member_rider'),1,gen_random_uuid())->>'membership_id' is not null,'manager ends rider membership through existing RPC');
select pg_temp.login('rider');
select extensions.throws_ok(format('select public.transition_c010_facility_booking(%L,%L,1,''cancel'',''Plan vervallen'',%L)',pg_temp.uid('org'),pg_temp.uid('shared'),pg_temp.uid('cancel_request')),'42501','C010_FACILITY_ACCESS_REQUIRED','revoked membership is checked before receipt replay');
select extensions.throws_ok('select pg_temp.ws()','42501','C010_FACILITY_ACCESS_REQUIRED','revoked member loses facility read access immediately');
reset role;
-- Trusted fixture-only lifecycle state transitions exercise production triggers.
select set_config('request.jwt.claim.sub','',true);
update public.horse_residencies set status='ended',valid_until=clock_timestamp() where horse_id=pg_temp.uid('hidden') and status='active';
select extensions.ok((select status='ended' and note='Privé paardeninstructie' from public.c010_horse_places where horse_id=pg_temp.uid('hidden')),'ending residency releases box and retains assignment note');
select extensions.ok((select count(*)=1 from private.c010_facility_receipts where request_id=pg_temp.uid('cancel_request')),'one durable receipt for replayed cancellation');
select extensions.ok((select not (result ? 'functions') from private.c010_facility_receipts where actor_profile_id=(select profile_id from p2_actors where alias='groom') and operation='functions'),'function preference values not retained in immutable receipts');
update public.profiles set status='deletion_pending',access_version=access_version+1 where id=(select profile_id from p2_actors where alias='groom');
select extensions.ok(not exists(select 1 from private.c010_function_preferences where profile_id=(select profile_id from p2_actors where alias='groom')),'deletion preparation removes own function preferences');
select * from extensions.finish();
rollback;
