import test from 'node:test';
import assert from 'node:assert/strict';
import {createBackendClient,normalizeLoad,normalizeFeeding,amsterdamInstant,localParts} from '../backend-client.js';
const uid=n=>`10000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const actor=uid(1),horse=uid(2),org=uid(3),task=uid(4),activity=uid(5),plan=uid(6),item=uid(7),versionId=uid(8);
const DAY='2026-09-10', response=(data,status=200)=>({ok:status>=200&&status<300,status,json:async()=>data});
const session=(user=actor,expires=Date.now()/1000+3600)=>({access_token:'access-'+user,refresh_token:'refresh-'+user,user:{id:user},expires_at:expires});
const defer=()=>{let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};};
const next=()=>new Promise(r=>setImmediate(r));
function raw(){return {
 profile:[{profile_status:'active',profile_id:actor,display_name:'Testactor',row_version:2,theme_mode:'light'}],
 day:{on_date:DAY,calendar:{today_date:DAY},items:[{source_type:'stable_task',source_id:task,task_id:task,title:'Mijn taak',organization_id:org,horse_id:horse,due_date:DAY,status:'open',row_version:2,can_complete:true},{source_type:'horse_activity',source_id:activity,schedule_item_id:activity,horse_id:horse,item_kind:'training',title:'Training',scheduled_start_at:DAY+'T08:00:14.321Z',scheduled_end_at:DAY+'T09:00:14.321Z',status:'planned',row_version:3,can_complete:true,participant_profile_ids:[actor]}]},
 horses:[{horse_id:horse,display_name:'Testpaard',lifecycle_status:'active',can_edit:true,can_manage:true,can_manage_planning:true,can_manage_feeding:true,is_primary_authority:true,row_version:1}],
 stables:[{organization_id:org,name:'Teststal',lifecycle_status:'active',role_codes:['primary_admin']}],
 workspace:{organization:{id:org,name:'Teststal'},capabilities:{'organization.edit':true,'organization.memberships.view':true},horses:[{horse_id:horse}],memberships:[{status:'active',profile_id:actor,profile_name:'Testactor',role_code:'primary_admin',role_name:'Beheerder'}]},
 round1:{can_manage_tasks:true,task_candidates:[{profile_id:actor,display_name:'Testactor'}],places:[],activities:[{activity_kind:'stable_task',activity_id:task,horse_id:horse,title:'Nieuwste taak',due_date:DAY,status:'open',row_version:3,can_complete:false,assignee_profile_id:uid(9)}]},
 schedules:{[horse]:[{schedule_item_id:activity,horse_id:horse,item_kind:'training',title:'Training',scheduled_start_at:DAY+'T08:00:14.321Z',scheduled_end_at:DAY+'T09:00:14.321Z',state:'planned',row_version:3,is_mine:true,participant_profile_ids:[actor,uid(10)],participant_names:['Testactor','Andere deelnemer'],source_timezone:'Europe/Amsterdam'}]},
 details:{[horse]:{residencies:[{status:'active',organization_id:org,organization_name:'Teststal'}]}},
 feeding:{[horse]:{plans:[{feeding_plan_id:plan,plan_type:'standard',status:'active',effective_from:'2026-01-01',active_version_id:versionId,row_version:5,versions:[{feeding_plan_version_id:versionId,items:[{feeding_plan_item_id:item,row_version:2,product_brand:'Beschrijvend product',product_name:'roughage',product_variant:'roughage',planned_quantity:0.25,unit_code:'kg',instruction:'Volledige notitie',round_code:'morning'}]}]}]}}
};}
function harness({data=raw(),override,timeoutMs=5000,expires}={}){
 const calls=[],memory=new Map();let currentUser=actor;
 const routes={get_current_account_profile:()=>data.profile,get_c010_personal_day:()=>data.day,list_c010_horses:()=>data.horses,list_c010_stables:()=>data.stables,get_c010_stable_workspace:()=>data.workspace,get_c010_stable_round1_workspace:()=>data.round1,list_c010_horse_schedule:p=>data.schedules[p.p_horse_id]||[],get_canonical_horse_workspace:p=>data.details[p.p_horse_id]||{},get_canonical_horse_feeding:p=>data.feeding[p.p_horse_id]||{plans:[]}};
 const fetchImpl=async(path,options)=>{const body=options.body?JSON.parse(options.body):null;calls.push({path,body,headers:options.headers});if(override){const result=await override(path,body,options);if(result!==undefined)return result;}
  if(path.includes('grant_type=password')){currentUser=body.email==='second'?uid(20):actor;return response(session(currentUser,expires));}
  if(path.includes('grant_type=refresh_token'))return response(session(currentUser));
  if(path.endsWith('/auth/v1/user'))return response({id:currentUser});
  if(path.endsWith('/auth/v1/logout?scope=local'))return response(null,204);
  const name=path.split('/').at(-1);if(routes[name])return response(routes[name](body));
  return response(name.includes('feeding')?{feeding_plan_id:plan,plan_row_version:6}:name.includes('activity')||name.includes('schedule')?{schedule_item_id:activity,row_version:4,state:'completed'}:{task_id:task,row_version:4,status:'completed'});
 };
 const storage={getItem:k=>memory.get(k),setItem:(k,v)=>memory.set(k,v),removeItem:k=>memory.delete(k)};
 const client=createBackendClient({fetchImpl,storage,timeoutMs});
 return {client,calls,memory,data,ready:async()=>{await client.login('first','test');return client.load();}};
}

test('authorized normalization: one task, server completion false retained; Today distinct',()=>{const s=normalizeLoad(raw(),{day:'2026-09-12',organizationId:org});assert.equal(s.tasks.length,1);assert.equal(s.tasks[0].rowVersion,3);assert.equal(s.tasks[0].canComplete,false);assert.equal(s.backend.todayTasks[0].canComplete,true);assert.equal(s.backend.todayDate,DAY);assert.equal(s.selectedDay,'2026-09-12');assert.equal(s.backend.actor.id,actor);assert.equal(s.horses[0].imageIsPlaceholder,true);assert.equal(s.horses[0].image,'assets/horse-placeholder.svg');});
test('role text never grants permissions; explicit false remains false',()=>{const r=raw();r.workspace.capabilities={};r.round1.can_manage_tasks=false;r.horses[0]={...r.horses[0],can_edit:false,can_manage:false,can_manage_planning:false,can_manage_feeding:false,is_primary_authority:false};const s=normalizeLoad(r,{day:DAY,organizationId:org});assert.equal(s.backend.capabilities.canCreateTask,false);assert.equal(s.backend.capabilities.canManage,false);assert.equal(s.backend.horseCapabilities[horse].feeding,false);assert.equal(s.activities[0].canComplete,false);assert.equal(s.backend.actor.personalHorseIds.length,0);});
test('feed uses product description, exact note, IDs and native unit',()=>{const f=normalizeFeeding(raw().feeding[horse],DAY);assert.equal(f.meals[0].items[0].product,'Beschrijvend product');assert.equal(f.meals[0].items[0].note,'Volledige notitie');assert.equal(f.meals[0].items[0].amount,'0,25 kg');assert.equal(f.meals[0].items[0].unit,'kg');assert.equal(f.meals[0].items[0].id,item);});
for(const [name,day,time,utc] of [['summer','2026-09-10','10:15','2026-09-10T08:15:00.000Z'],['winter','2026-12-10','10:15','2026-12-10T09:15:00.000Z']])test('civil '+name+' conversion',()=>assert.equal(amsterdamInstant(day,time),utc));
for(const [name,day,time] of [['missing','2026-03-29','02:30'],['ambiguous','2026-10-25','02:30'],['invalid','2026-09-10','25:30']])test('reject '+name+' civil time',()=>assert.throws(()=>amsterdamInstant(day,time)));
for(const [day,nextDay,hours] of [['2026-03-29','2026-03-30',23],['2026-10-25','2026-10-26',25]])test('calendar day has '+hours+' hours',()=>assert.equal((Date.parse(amsterdamInstant(nextDay,'00:00'))-Date.parse(amsterdamInstant(day,'00:00')))/3600000,hours));
test('selected planning day does not replace personal Today query',async()=>{const h=harness();await h.ready();await h.client.load({day:'2026-09-12',organizationId:null});const q=h.calls.filter(c=>c.path.endsWith('get_c010_personal_day'));assert(q.every(c=>c.body.p_on_date===null));assert.equal(h.calls.filter(c=>c.path.endsWith('get_c010_stable_workspace')).length,1);});
test('task completion requires genuine current server boolean',async()=>{const h=harness();await h.ready();await assert.rejects(h.client.completeTask(task,3,uid(40)));assert.equal(h.calls.filter(c=>c.path.endsWith('transition_c010_stable_task')).length,0);});
test('task completion actorless RPC sends supplied CAS and request ID',async()=>{const r=raw();r.round1.activities[0].can_complete=true;const h=harness({data:r});await h.ready();await h.client.completeTask(task,3,uid(40));const c=h.calls.at(-1);assert.equal(c.path,'/api/rest/v1/rpc/transition_c010_stable_task');assert.deepEqual(c.body,{p_organization_id:org,p_task_id:task,p_expected_row_version:3,p_action:'complete',p_request_id:uid(40)});});
test('edit activity preserves exact original instants and participants',async()=>{const h=harness();await h.ready();await h.client.saveActivity({id:activity,rowVersion:3,horseId:horse,type:'Training',title:'Aangepast',note:'Nieuwe notitie',date:DAY,time:'10:00',end:'11:00'},uid(40));const p=h.calls.at(-1).body;assert.equal(p.p_scheduled_start_at,DAY+'T08:00:14.321Z');assert.equal(p.p_scheduled_end_at,DAY+'T09:00:14.321Z');assert.deepEqual(p.p_participant_profile_ids,[actor,uid(10)]);assert.equal(p.p_expected_row_version,3);assert.equal(p.p_instruction,'Nieuwe notitie');assert(!Object.hasOwn(p,'p_actor_id'));});
test('new feed product after deleting old row never reuses positional ID',async()=>{const h=harness();await h.ready();await h.client.saveFeedingRound({horseId:horse,day:DAY,mealName:'Ochtend',items:[{product:'Nieuw product',productType:'pellet',amount:'0,30',unit:'kg',note:'Nieuw'}]},uid(40));const p=h.calls.at(-1).body;assert.equal(p.p_products[0].quantity,'0.30');assert.equal(p.p_products[0].description,'Nieuw product');assert(!Object.hasOwn(p.p_products[0],'item_id'));assert.equal(p.p_feeding_plan_id,plan);assert.equal(p.p_expected_plan_row_version,5);});
test('existing feed item uses its own ID and version, not position',async()=>{const h=harness();await h.ready();await h.client.saveFeedingRound({horseId:horse,day:DAY,mealName:'Ochtend',items:[{id:item,product:'Aangepast',amount:'1',unit:'piece',note:'Behouden'}]},uid(40));const p=h.calls.at(-1).body.p_products[0];assert.equal(p.item_id,item);assert.equal(p.expected_row_version,2);assert.equal(p.unit_code,'piece');assert.equal(p.note,'Behouden');});
test('unknown feed ID and translated backend unit rejected before write',async()=>{const h=harness();await h.ready();for(const entry of [{id:uid(99),product:'A',productType:'pellet',amount:'1',unit:'kg'},{product:'A',productType:'pellet',amount:'1',unit:'stuk'}])await assert.rejects(h.client.saveFeedingRound({horseId:horse,day:DAY,mealName:'Ochtend',items:[entry]},uid(40)));assert.equal(h.calls.filter(c=>c.path.endsWith('save_canonical_horse_feeding_round')).length,0);});
test('409 is actionable conflict without false access loss',async()=>{const h=harness({override:async p=>p.endsWith('complete_c010_personal_activity')?response({code:'PT409',message:'STALE_SCHEDULE_VERSION'},409):undefined});await h.ready();await assert.rejects(h.client.completeActivity(activity,3,uid(40)),e=>e.status===409&&!e.accessLost&&!e.uncertain&&e.message.includes('Laad de actuele'));});
for(const [message,accessLost] of [['CROSS_STABLE_HORSE_DENIED',false],['PERMISSION_DENIED',true]])test('42501 scoped mapping '+message,async()=>{const h=harness({override:async p=>p.endsWith('upsert_c010_stable_task')?response({code:'42501',message},403):undefined});await h.ready();await assert.rejects(h.client.saveTask({title:'Test',date:DAY,assigneeProfileId:actor},uid(40)),e=>e.accessLost===accessLost);});
test('parallel load refreshes rotated session exactly once',async()=>{let refresh=0;const h=harness({expires:1,override:async p=>{if(p.includes('grant_type=refresh_token')){refresh++;await new Promise(r=>setTimeout(r,5));return response(session());}}});await h.ready();assert.equal(refresh,1);});
test('logout invalidates pending load and clears session state',async()=>{const gate=defer();const h=harness({override:async p=>p.endsWith('get_current_account_profile')?gate.promise:undefined});await h.client.login('first','test');const pending=h.client.load();await next();await h.client.logout();gate.resolve(response(raw().profile));await assert.rejects(pending,e=>e.code==='STALE_CONTEXT');assert.equal(h.memory.size,0);});
test('old restore failure cannot clear newer account session',async()=>{const gate=defer();const h=harness({override:async p=>p.endsWith('/auth/v1/user')?gate.promise:undefined});await h.client.login('first','test');const restore=h.client.restore();await next();await h.client.login('second','test');gate.resolve(response({message:'bad'},401));await assert.rejects(restore);const stored=JSON.parse([...h.memory.values()][0]);assert.equal(stored.user_id,uid(20));});
test('newer load wins when earlier profile response arrives late',async()=>{const gate=defer();let count=0;const h=harness({override:async p=>p.endsWith('get_current_account_profile')&&count++===0?gate.promise:undefined});await h.client.login('first','test');const old=h.client.load();await next();const fresh=await h.client.load({day:'2026-09-12'});gate.resolve(response(raw().profile));await assert.rejects(old,e=>e.code==='STALE_CONTEXT');assert.equal(fresh.selectedDay,'2026-09-12');});
test('mutation timeout covers stalled response body and never retries',async()=>{let calls=0;const h=harness({timeoutMs:25,override:async p=>{if(p.endsWith('complete_c010_personal_activity')){calls++;return {ok:true,status:200,json:()=>new Promise(()=>{})};}}});await h.ready();await assert.rejects(h.client.completeActivity(activity,3,uid(40)),e=>e.code==='TIMEOUT'&&e.uncertain);assert.equal(calls,1);});
test('ambiguous response is not reported as saved',async()=>{const h=harness({override:async p=>p.endsWith('complete_c010_personal_activity')?response({ok:true}):undefined});await h.ready();await assert.rejects(h.client.completeActivity(activity,3,uid(40)),e=>e.code==='INVALID_RESPONSE'&&e.uncertain);});
test('duplicate parallel mutations rejected without second request',async()=>{const gate=defer();const h=harness({override:async p=>p.endsWith('complete_c010_personal_activity')?gate.promise:undefined});await h.ready();const first=h.client.completeActivity(activity,3,uid(40));await next();await assert.rejects(h.client.completeActivity(activity,3,uid(41)));gate.resolve(response({schedule_item_id:activity,row_version:4}));await first;assert.equal(h.calls.filter(c=>c.path.endsWith('complete_c010_personal_activity')).length,1);});
test('feeding stays on server Today after browsing a future planning day',()=>{const r=raw();const future=structuredClone(r.feeding[horse].plans[0]);Object.assign(future,{feeding_plan_id:uid(70),plan_type:'temporary',effective_from:'2026-09-12',effective_until:'2026-09-13'});future.versions[0].items[0].product_brand='Future product';r.feeding[horse].plans.push(future);const s=normalizeLoad(r,{day:'2026-09-12',organizationId:org});assert.equal(s.feeding[horse].planId,plan);assert.equal(s.feeding[horse].meals[0].items[0].product,'Beschrijvend product');assert.equal(s.backend.todayDate,DAY);});
test('feeding save permits server Today and refuses selected future date',async()=>{const h=harness();await h.ready();await h.client.load({day:'2026-09-12'});const form={horseId:horse,mealName:'Ochtend',items:[{id:item,product:'Today',quantity:'1',unit:'kg'}]};await assert.rejects(h.client.saveFeedingRound({...form,day:'2026-09-12'},uid(40)));await h.client.saveFeedingRound({...form,day:DAY},uid(40));assert.equal(h.calls.at(-1).body.p_effective_from,'2026-01-01');});
test('client base URL cannot forward user session to another origin',()=>{for(const baseUrl of ['https://foreign.invalid','//foreign.invalid','/api?override=remote'])assert.throws(()=>createBackendClient({baseUrl}));});

test('horse location and people come from canonical horse facts, never the selected stable team',()=>{
 const r=raw();r.details[horse]={residencies:[],relationships:[],person_ownerships:[]};
 r.workspace.memberships.push({status:'active',profile_id:uid(31),profile_name:'Unrelated groom',role_code:'groom'});
 let h=normalizeLoad(r,{day:DAY,organizationId:org}).horses[0];
 assert.equal(h.stable,'');assert.equal(h.organizationId,null);assert.equal(h.owner,'');
 assert.deepEqual(h.team,[{id:actor,name:'Testactor',role:'Hoofdbeheerder'}]);
 r.details[horse]={residencies:[{status:'active',organization_id:uid(32),organization_name:'Actual residence'}],relationships:[{status:'active',profile_id:uid(33),profile_name:'Actual rider',relationship_type:'rider'},{status:'ended',profile_id:uid(34),profile_name:'Former rider'}],person_ownerships:[{status:'active',profile_name:'Recorded owner'},{status:'ended',profile_name:'Previous owner'}]};
 h=normalizeLoad(r,{day:DAY,organizationId:org}).horses[0];
 assert.equal(h.stable,'Actual residence');assert.equal(h.organizationId,uid(32));assert.equal(h.owner,'Recorded owner');assert.deepEqual(h.team.map(m=>m.name),['Testactor','Actual rider']);
});
