import test from 'node:test';
import assert from 'node:assert/strict';
import {normalizeFeeding,normalizeLoad} from '../backend-client.js';
import {createFeedingEditor,renderTemporaryPreview,feedingProductRow} from '../backend-feeding-form.js';
import {renderHorseFeeding} from '../feeding.js';
import {esc,icon} from '../components.js';
import {uid,horse,org,plan,item,DAY,response,raw,harness,defer,next} from './feeding-fixture.mjs';
const temporary=()=>{const p=structuredClone(raw().feeding[horse].plans[0]);Object.assign(p,{feeding_plan_id:uid(70),plan_type:'temporary',effective_from:DAY,effective_until:'2026-09-17',row_version:8});p.versions[0].items[0].feeding_plan_item_id=uid(71);p.versions[0].items[0].product_brand='Tijdelijk';return p;};
const dataBoth=()=>{const r=raw();r.feeding[horse].plans.push(temporary());return r;};
const product={product:'Hooi',productType:'roughage',quantity:'2,25',unit:'kg',note:'Hele instructie behouden'};
const saveInput=(extra={})=>({horseId:horse,day:DAY,planId:null,planType:'temporary',effectiveFrom:DAY,effectiveUntil:DAY,mealName:'morning',items:[product],...extra});

test('temporary is effective while full base and future plans remain individually available',()=>{const r=dataBoth(),future=temporary();future.feeding_plan_id=uid(72);future.effective_from='2026-10-01';future.effective_until='2026-10-02';r.feeding[horse].plans.push(future);const f=normalizeFeeding(r.feeding[horse],DAY);assert.equal(f.planId,uid(70));assert.equal(f.plans.length,3);assert.equal(f.plans.find(p=>p.planId===plan).meals[0].items[0].note,'Volledige notitie');assert.equal(normalizeFeeding(r.feeding[horse],'2026-09-18').planId,plan);});
test('new single-day temporary uses exact equal date strings and null identity',async()=>{const h=harness();await h.ready();await h.client.saveFeedingRound(saveInput(),uid(40));const p=h.calls.at(-1).body;assert.equal(p.p_effective_from,DAY);assert.equal(p.p_effective_until,DAY);assert.equal(p.p_feeding_plan_id,null);assert.equal(p.p_expected_plan_row_version,null);assert.equal(p.p_products[0].quantity,'2.25');});
test('explicit base edit during temporary uses base CAS and base item, never active temporary',async()=>{const h=harness({data:dataBoth()});await h.ready();await h.client.saveFeedingRound(saveInput({planId:plan,planType:'standard',planRowVersion:5,effectiveFrom:'2026-01-01',effectiveUntil:null,items:[{...product,id:item,rowVersion:2}]}),uid(40));const p=h.calls.at(-1).body;assert.equal(p.p_feeding_plan_id,plan);assert.equal(p.p_expected_plan_row_version,5);assert.equal(p.p_products[0].item_id,item);});
test('captured plan and item CAS preserved after a newer snapshot reload',async()=>{const h=harness();await h.ready();h.data.feeding[horse].plans[0].row_version=12;h.data.feeding[horse].plans[0].versions[0].items[0].row_version=6;await h.client.load();await h.client.saveFeedingRound(saveInput({planId:plan,planType:'standard',planRowVersion:5,effectiveFrom:'2026-01-01',effectiveUntil:null,items:[{...product,id:item,rowVersion:2}]}),uid(40));assert.equal(h.calls.at(-1).body.p_expected_plan_row_version,5);assert.equal(h.calls.at(-1).body.p_products[0].expected_row_version,2);});
test('missing or insufficient base rejects before any mutation',async()=>{for(const missing of [true,false]){const r=raw();if(missing)r.feeding[horse].plans=[];else r.feeding[horse].plans[0].effective_until='2026-09-09';const h=harness({data:r});await h.ready();await assert.rejects(h.client.saveFeedingRound(saveInput(),uid(40)),/basisvoeding/);assert(!h.calls.some(c=>c.path.endsWith('save_canonical_horse_feeding_round')));}});
test('backward or invalid calendar range rejects before mutation',async()=>{const h=harness();await h.ready();for(const until of ['2026-09-09','2026-02-30'])await assert.rejects(h.client.saveFeedingRound(saveInput({effectiveUntil:until}),uid(40)));});
test('new base uses same atomic round contract',async()=>{const r=raw();r.feeding[horse].plans=[];const h=harness({data:r});await h.ready();await h.client.saveFeedingRound(saveInput({planType:'standard',effectiveUntil:null}),uid(40));assert.equal(h.calls.at(-1).body.p_plan_type,'standard');assert.equal(h.calls.at(-1).body.p_feeding_plan_id,null);});
test('explicit horse feeding grant uses C010 wrapper without horse.edit',async()=>{const r=raw();r.horses[0].can_edit=false;const h=harness({data:r});await h.ready();await h.client.saveFeedingRound(saveInput(),uid(40));assert(h.calls.at(-1).path.endsWith('/save_c010_horse_feeding_round'));});
test('missing feeding grant refuses all save and retire paths',async()=>{const r=dataBoth();r.horses[0].can_edit=false;r.horses[0].can_manage_feeding=false;const h=harness({data:r});await h.ready();await assert.rejects(h.client.saveFeedingRound(saveInput(),uid(40)));await assert.rejects(h.client.retireFeedingPlan({horseId:horse,planId:uid(70),planRowVersion:8},uid(40)));});
test('retire permits temporary only and keeps explicit CAS/request identity',async()=>{const h=harness({data:dataBoth()});await h.ready();await assert.rejects(h.client.retireFeedingPlan({horseId:horse,planId:plan,planRowVersion:5},uid(40)));await h.client.retireFeedingPlan({horseId:horse,planId:uid(70),planRowVersion:8},uid(40));assert.equal(h.calls.at(-1).path,'/api/rest/v1/rpc/retire_canonical_horse_feeding_plan');assert.deepEqual(h.calls.at(-1).body,{p_horse_id:horse,p_feeding_plan_id:uid(70),p_expected_row_version:8,p_request_id:uid(40)});});
test('shortening preserves selected original round items and dates',async()=>{const h=harness({data:dataBoth()});const s=await h.ready(),p=s.feeding[horse].plans.find(p=>p.planType==='temporary');await h.client.saveFeedingRound(saveInput({...p,horseId:horse,day:DAY,mealName:'morning',effectiveUntil:DAY,items:p.meals[0].items}),uid(40));const q=h.calls.at(-1).body;assert.equal(q.p_products[0].item_id,uid(71));assert.equal(q.p_effective_until,DAY);assert.equal(q.p_products[0].note,'Volledige notitie');});
test('known temporary conflict is actionable; unrelated 23P01 is not mislabelled',async()=>{for(const message of ['TEMPORARY_FEEDING_PLAN_CONFLICT','OTHER_CONSTRAINT']){const h=harness({override:async p=>p.endsWith('save_canonical_horse_feeding_round')?response({code:'23P01',message},400):undefined});await h.ready();await assert.rejects(h.client.saveFeedingRound(saveInput(),uid(40)),e=>!e.accessLost&&(message==='OTHER_CONSTRAINT'?!e.message.includes('basisvoeding'):e.message.includes('hele periode')));}});
test('full replacement preview pairs edited round with saved other rounds, escapes every instruction',()=>{const plan={meals:[{code:'afternoon',items:[{product:'Middag',quantity:3,unit:'kg',note:'Niet bij ochtend'}]}]};const html=renderTemporaryPreview({plan,roundCode:'morning',items:[{product:'Hooi',quantity:2.25,unit:'kg',note:'<script>long instruction</script>'}],from:DAY,until:DAY});assert(html.includes('Dit vervangt alle basisvoeding'));assert(html.includes('Geen producten — basisvoeding wordt niet aangevuld'));assert(html.indexOf('Hooi')<html.indexOf('Middag'));assert(html.includes('&lt;script&gt;'));assert(!html.includes('<script>'));assert(html.includes('10-09-2026 tot en met 10-09-2026'));});
test('existing native units and notes render without translating submitted value',()=>{const html=feedingProductRow({...product,unit:'piece'});assert(html.includes('value="piece" selected'));assert(html.includes('Hele instructie behouden'));assert(html.includes('value="">Kies een productsoort'));});
test('current temporary and separately preserved base both rendered; readonly has no edit actions',()=>{const s=normalizeLoad(dataBoth(),{day:DAY,organizationId:org});s.today=DAY;s.horseId=horse;const ctx={esc,icon,horse:id=>s.horses.find(h=>h.id===id)};const html=renderHorseFeeding(s,ctx);assert(html.includes('Bewaard als vaste basis'));assert(html.includes('Volledige notitie'));assert(html.includes('Tijdelijke schema’s'));s.backend.horseCapabilities[horse].feeding=false;const readonly=renderHorseFeeding(s,ctx);assert(!readonly.includes('data-action="backend-feed-plan"'));assert(!readonly.includes('data-action="edit-feeding"'));});
test('internal P2 read rejects late response after logout',async()=>{const gate=defer();const h=harness({override:async p=>p.endsWith('p2_read')?gate.promise:undefined});await h.ready();const pending=h.client.requestRpc('p2_read',{});await next();await h.client.logout();gate.resolve(response({ok:true}));await assert.rejects(pending,e=>e.code==='STALE_CONTEXT');});
test('internal P2 writes share P1 mutex and preserve caller payload',async()=>{const gate=defer();const h=harness({override:async p=>p.endsWith('p2_write')?gate.promise:undefined});await h.ready();const pending=h.client.requestRpc('p2_write',{p_request_id:uid(40)},{write:true});await next();await assert.rejects(h.client.saveFeedingRound(saveInput(),uid(41)));gate.resolve(response({saved:true}));assert.deepEqual(await pending,{saved:true});});

function editorHarness(source=dataBoth()){
 const state=normalizeLoad(source,{day:DAY,organizationId:org});state.today=DAY;state.horseId=horse;
 let form=null,html='',opened=0;const calls=[],errors=[];
 const decode=s=>s.replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&');
 const showModal=(title,body)=>{html=body;opened++;const name=body.match(/<form id="([^"]+)"/);if(!name){form=null;return;}
  const fields={};for(const m of body.matchAll(/<input\b([^>]*)>/g)){const attrs=m[1],n=attrs.match(/\bname="([^"]+)"/);if(n)fields[n[1]]={name:n[1],value:decode(attrs.match(/\bvalue="([^"]*)"/)?.[1]||''),checked:false};}
  const rows=[...body.matchAll(/<div class="backend-feed-row"([\s\S]*?)Product weghalen<\/button><\/div>/g)].map(m=>{const fragment=m[1],values={};for(const k of ['product','quantity','unit','note','productType']){if(k==='note')values[k]=decode(fragment.match(/<textarea data-field="note">([\s\S]*?)<\/textarea>/)?.[1]||'');else if(['unit','productType'].includes(k)){const select=fragment.match(new RegExp(`<select data-field="${k}"[^>]*>([\\s\\S]*?)<\\/select>`))?.[1]||'';values[k]=decode(select.match(/<option value="([^"]*)" selected/)?.[1]||select.match(/<option value="([^"]*)"/)?.[1]||'');}else values[k]=decode(fragment.match(new RegExp(`data-field="${k}"[^>]*value="([^"]*)"`))?.[1]||'');}
   return {dataset:{itemId:fragment.match(/data-item-id="([^"]*)"/)?.[1]||'',itemVersion:fragment.match(/data-item-version="([^"]*)"/)?.[1]||''},values,querySelector:s=>({get value(){return values[s.match(/data-field="([^"]+)"/)[1]];}})};});
  const preview={innerHTML:''};form={id:name[1],dataset:{},elements:{namedItem:k=>fields[k]},listeners:{},fields,rows,preview,addEventListener(n,f){this.listeners[n]=f;},querySelectorAll:()=>rows,querySelector:s=>s==='[data-feed-preview]'?preview:null};
 };
 globalThis.document={getElementById:()=>form};
 const api=createFeedingEditor({getState:()=>state,showModal,perform:(f,op)=>op(uid(40)),client:{saveFeedingRound:(data,id)=>calls.push({data,id}),retireFeedingPlan:(data,id)=>calls.push({data,id,retire:true})},formError:(f,e)=>errors.push(e.message),reload:()=>{}});
 return {state,api,calls,errors,get form(){return form;},get html(){return html;},get opened(){return opened;},action:(action,dataset)=>api.handleAction(action,{dataset}),submit:()=>api.handleSubmit(form,{preventDefault(){}})};
}
test('actual editor creates equal-day temporary from default start and end-only change',()=>{const h=editorHarness(raw());h.action('backend-feed-meal',{horse,planType:'temporary',meal:'morning'});assert.equal(h.form.fields.effectiveFrom.value,DAY);h.form.fields.effectiveUntil.value=DAY;Object.assign(h.form.rows[0].values,product);h.form.fields.replacementConfirmed.checked=true;h.submit();assert.equal(h.calls[0].data.effectiveFrom,DAY);assert.equal(h.calls[0].data.effectiveUntil,DAY);assert.equal(h.calls[0].data.planId,null);});
test('actual checkbox confirmation remains checked on its input event; editing resets it',()=>{const h=editorHarness();h.action('backend-feed-meal',{horse,plan:uid(70),meal:'morning'});const check=h.form.fields.replacementConfirmed;check.checked=true;h.form.listeners.input({target:check});assert.equal(check.checked,true);h.form.listeners.input({target:{name:'quantity'}});assert.equal(check.checked,false);assert(h.form.preview.innerHTML.includes('Volledige notitie'));assert(h.form.preview.innerHTML.includes('basisvoeding wordt niet aangevuld'));});
test('actual editor blocks unchecked whole-plan replacement and retains input',()=>{const h=editorHarness();h.action('backend-feed-meal',{horse,plan:uid(70),meal:'morning'});h.submit();assert.equal(h.calls.length,0);assert.equal(h.errors.length,1);assert.equal(h.form.rows[0].values.note,'Volledige notitie');});
test('actual editor captures original plan CAS even when live presentation reloads',()=>{const h=editorHarness();h.action('backend-feed-meal',{horse,plan,meal:'morning'});h.state.feeding[horse].plans.find(p=>p.planId===plan).planRowVersion=99;h.submit();assert.equal(h.calls[0].data.planRowVersion,5);assert.equal(h.calls[0].data.items[0].rowVersion,2);});
test('actual editor stop preserves original products and submits inclusive chosen end',()=>{const h=editorHarness();h.action('backend-feed-end',{horse,plan:uid(70)});h.form.fields.until.value=DAY;h.submit();assert.equal(h.calls[0].data.effectiveUntil,DAY);assert.equal(h.calls[0].data.items[0].note,'Volledige notitie');assert.equal(h.calls[0].data.items[0].id,uid(71));});
test('actual editor remove is explicit and retires only chosen temporary',()=>{const h=editorHarness();h.action('backend-feed-remove',{horse,plan:uid(70)});assert(h.html.includes('basisvoeding en eerdere registraties blijven bewaard'));h.submit();assert.equal(h.calls[0].retire,true);assert.equal(h.calls[0].data.planId,uid(70));});
test('actual editor offers basis first when no base, and refuses revoked actor before submit',()=>{const r=raw();r.feeding[horse].plans=[];const h=editorHarness(r);h.action('edit-feeding',{horse});assert(h.html.includes('Basisvoeding vastleggen'));assert(!h.html.includes('Tijdelijk schema toevoegen'));h.action('backend-feed-meal',{horse,planType:'standard',meal:'morning'});h.state.backend.horseCapabilities[horse].feeding=false;h.submit();assert.equal(h.calls.length,0);});
