import test from 'node:test';
import assert from 'node:assert/strict';
import {INITIAL_STATE} from '../data.js';
import {createContext} from '../components.js';
import {renderTasks} from '../tasks.js';
import {renderToday,renderStable} from '../daily-ui.js';
import {renderPlanning} from '../planning.js';
import {harness,raw,uid,actor,org,DAY} from './feeding-fixture.mjs';

const task=(id,date,time=null,extras={})=>({id,title:'Titel '+id,date,time,horseId:null,location:'Weide 6',assignee:'Noor Meijer',note:'Eerst het hele hek controleren. Laatste instructieregel blijft zichtbaar.',status:'open',organizationId:'a',...extras});
function state(over={}){return {...structuredClone(INITIAL_STATE),today:DAY,route:'tasks',selectedDay:DAY,activities:[],tasks:[task('general',null),task('today',DAY),task('today-time',DAY,'15:30'),task('tomorrow','2026-09-11'),task('later','2026-09-20')],...over};}
const ids=html=>[...html.matchAll(/data-action="open-task" data-id="([^"]+)"/g)].map(m=>m[1]);
// Existing fixtures describe DAY; inject that local clock into the dynamic dashboard.
const render=(fn,s)=>fn(s,createContext(s),fn===renderToday?new Date(DAY+'T14:00:00'):undefined);
test('selected day task list contains only that day plus separately headed general tasks',()=>{const s=state({selectedDay:'2026-09-11'}),html=render(renderTasks,s);assert.deepEqual(ids(html),['tomorrow','general']);assert.match(html,/<h2>Morgen /);assert.match(html,/<h2>Algemene taken /);assert.match(html,/aria-label="2 open taken"/);assert(html.indexOf('data-id="tomorrow"')<html.indexOf('Algemene taken'));assert(html.indexOf('data-id="general"')>html.indexOf('Algemene taken'));assert.match(html,/value="2026-09-11" data-task-day/);});
test('general tasks remain available after choosing another day without becoming dated',()=>{const s=state({selectedDay:'2026-09-20'}),html=render(renderTasks,s);assert.deepEqual(ids(html),['later','general']);assert.match(html,/Zonder datum/);assert.equal(s.tasks.find(t=>t.id==='general').date,null);});
test('task cards preserve complete note and free location and never label missing time as midnight/null',()=>{const s=state(),html=createContext(s).taskCard(s.tasks[0],{showInstruction:true});assert.match(html,/Laatste instructieregel blijft zichtbaar/);assert.match(html,/Weide 6/);assert.match(html,/aria-label="Titel general · Zonder datum · Weide 6"/);assert.doesNotMatch(html,/00:00|null|undefined/);});
test('explicit midnight survives card rendering',()=>{const s=state(),html=createContext(s).taskCard(task('midnight',DAY,'00:00'));assert.match(html,/Vandaag · 00:00/);});
test('done and cancelled general rows leave open group and counter',()=>{const s=state({tasks:[task('completed',null,null,{status:'completed'}),task('cancelled',null,null,{status:'cancelled'}),task('open',DAY)]}),html=render(renderTasks,s);assert.match(html,/aria-label="1 open taken"/);assert.match(html,/1 van 3 taken afgerond/);const before=html.slice(0,html.indexOf('<details'));assert.deepEqual(ids(before),['open']);assert.deepEqual(ids(html.slice(html.indexOf('<details'))),['completed','cancelled']);assert.doesNotMatch(before,/<h2>Algemene taken/);});
test('horse task route excludes optional/no-horse tasks and other horses',()=>{const s=state({route:'horse-tasks',horseId:'orion',tasks:[task('orion',DAY,null,{horseId:'orion'}),task('nova',DAY,null,{horseId:'nova'}),task('no-horse',null)]});assert.deepEqual(ids(render(renderTasks,s)),['orion']);});
test('local Today remains today when selected task day is tomorrow',()=>{const s=state({route:'today',selectedDay:'2026-09-11'}),html=render(renderToday,s);assert.deepEqual(ids(html),['today','today-time','general']);assert.match(html,/Algemene taken/);assert(!ids(html).includes('tomorrow'));});
test('connected Today uses authoritative personal projection, not selected-day manager list',async()=>{const data=raw();data.day.items=[{source_type:'stable_task',source_id:uid(501),task_id:uid(501),title:'Vandaag persoonlijk',due_date:DAY,status:'open',row_version:1,organization_id:org,can_complete:true},{source_type:'stable_task',source_id:uid(502),task_id:uid(502),title:'Algemeen persoonlijk',due_date:null,status:'open',row_version:1,organization_id:org,can_complete:true}];data.round1.activities=[{activity_kind:'stable_task',activity_id:uid(503),title:'Morgen managerlijst',due_date:'2026-09-11',status:'open',row_version:1,organization_id:org,assignee_profile_id:actor,can_complete:true}];const h=harness({data});await h.ready();const s=await h.client.load({day:'2026-09-11'});s.today=s.backend.todayDate;s.route='today';s.backend.todayTasks=s.backend.todayItems.filter(t=>t.sourceType==='stable_task');s.backend.todayActivities=[];const html=render(renderToday,s);assert.deepEqual(ids(html),[uid(501),uid(502)]);assert(!ids(html).includes(uid(503)));assert.match(html,/Algemene taken/);});
test('active stable excludes other organization general tasks even without a horse',()=>{const s=state({route:'stable',selectedDay:'2026-09-11',tasks:[task('a-general',null),task('a-today',DAY),task('a-tomorrow','2026-09-11'),task('b-general',null,null,{organizationId:'b'})]});s.backend={connected:true,organizationId:'a',stableHorseIds:['orion'],actor:{id:actor,name:'Manager',accessibleHorseIds:['orion'],personalHorseIds:[],assignedHorseIds:[]},capabilities:{canManage:true,canViewTeam:true},p2:{connected:true,canManage:false,canBook:false}};const html=render(renderStable,s);assert.deepEqual(ids(html),['a-today','a-general']);assert(!html.includes('Titel b-general'));});
test('planning shows selected dated tasks without assigning general tasks to an agenda day',()=>{const s=state({route:'planning',selectedDay:'2026-09-11'});const html=render(renderPlanning,s);assert.deepEqual(ids(html),['tomorrow']);assert.match(html,/Taken · Morgen/);assert(!html.includes('Titel general'));});
test('horse planning excludes dated nonhorse and other-horse tasks',()=>{const s=state({route:'horse-planning',horseId:'orion',tasks:[task('orion',DAY,null,{horseId:'orion'}),task('nova',DAY,null,{horseId:'nova'}),task('general',null),task('no-horse-day',DAY)]});assert.deepEqual(ids(render(renderPlanning,s)),['orion']);});
test('text and instruction fields remain escaped in cards and expanded task list',()=>{const s=state({tasks:[task('safe',null,null,{title:'<img onerror="bad">',note:'<script>bad()</script>',location:'" onclick="bad'})]}),html=render(renderTasks,s);assert.doesNotMatch(html,/<script>|<img onerror=/);assert.match(html,/&lt;script&gt;bad\(\)&lt;\/script&gt;/);assert.match(html,/&quot; onclick=&quot;bad/);});
