import test from 'node:test';
import assert from 'node:assert/strict';
import {harness,raw,response,uid,actor,horse,org,DAY} from './feeding-fixture.mjs';
import {taskFormValues} from '../task-timing.js';

const form={title:'Vrije locatie controleren',location:'Weide 6',note:'Loop het hele hek na.',assigneeProfileId:actor};
for(const [name,selection,expectedDate,expectedTime,expectedHorse] of [
 ['general',{when:'none',time:'09:30',date:DAY,addTime:'on'},null,null,null],
 ['today without time',{when:'today'},DAY,null,null],
 ['tomorrow without time',{when:'tomorrow'},'2026-09-11',null,null],
 ['future timed and horse optional',{when:'custom',date:'2026-09-20',time:'15:30',addTime:'on'},'2026-09-20','15:30:00',null],
 ['horse-linked general',{when:'none',horseId:horse},null,null,horse],
 ['existing midnight is explicit',{when:'today',time:'00:00',addTime:'on',horseId:horse},DAY,'00:00:00',horse],
]) test(`real client sends exact nullable RPC fields: ${name}`,async()=>{const h=harness();await h.ready();await h.client.saveTask(taskFormValues({...form,...selection},DAY),uid(100));const call=h.calls.find(c=>c.path.endsWith('/upsert_c010_stable_task'));assert.equal(call.body.p_due_date,expectedDate);assert.equal(call.body.p_due_time,expectedTime);assert.equal(call.body.p_horse_id,expectedHorse);assert.equal(call.body.p_assignee_profile_id,actor);assert.equal(call.body.p_location_text,'Weide 6');assert.equal(call.body.p_organization_id,org);assert.equal(call.body.p_request_id,uid(100));assert.equal(call.body.p_task_id,null);assert.equal(call.body.p_expected_row_version,null);});

for(const [name,delta] of [['time without date',{date:null,time:'15:30'}],['invalid hour',{date:DAY,time:'24:00'}],['invalid minute',{date:DAY,time:'12:60'}],['non-clock value',{date:DAY,time:'noon'}],['invalid civil day',{date:'2026-02-30'}],['missing assignee',{date:null,assigneeProfileId:null}],['foreign horse',{date:null,horseId:uid(999)}]]) test(`invalid task refused before write: ${name}`,async()=>{const h=harness();await h.ready();await assert.rejects(()=>h.client.saveTask({...form,...delta},uid(101)));assert.equal(h.calls.filter(c=>c.path.endsWith('/upsert_c010_stable_task')).length,0);});

test('real client synthetic RPC save/readback preserves all timing variants and old timed row',async()=>{const data=raw();data.round1.activities=[{activity_kind:'stable_task',activity_id:uid(4),title:'Oude getimede taak',due_date:DAY,due_time:'09:45:00',horse_id:horse,organization_id:org,assignee_profile_id:actor,status:'open',row_version:3,can_complete:true}];data.day.items=[];let seq=200;const h=harness({data,override:(path,body)=>{if(!path.endsWith('/upsert_c010_stable_task'))return;const id=uid(seq++);data.round1.activities.push({activity_kind:'stable_task',activity_id:id,title:body.p_title,note:body.p_note,due_date:body.p_due_date,due_time:body.p_due_time,horse_id:body.p_horse_id,organization_id:body.p_organization_id,assignee_profile_id:body.p_assignee_profile_id,status:'open',row_version:1,can_complete:true});return response({task_id:id,row_version:1});}});await h.ready();const variants=[{when:'none'},{when:'tomorrow'},{when:'custom',date:'2026-09-20',time:'15:30',addTime:'on',horseId:horse}];for(let i=0;i<variants.length;i++)await h.client.saveTask(taskFormValues({...form,title:'Nieuwe taak '+i,...variants[i]},DAY),uid(300+i));const next=await h.client.load({day:'2026-09-20'});assert.deepEqual(next.tasks.map(t=>[t.title,t.date,t.time,t.horseId]),[['Oude getimede taak',DAY,'09:45',horse],['Nieuwe taak 0',null,'',null],['Nieuwe taak 1','2026-09-11','',null],['Nieuwe taak 2','2026-09-20','15:30',horse]]);assert.equal(next.backend.todayDate,DAY);const personal=h.calls.filter(c=>c.path.endsWith('/get_c010_personal_day'));assert(personal.every(c=>c.body.p_on_date===null));assert.equal(h.calls.filter(c=>c.path.endsWith('/get_c010_stable_round1_workspace')).at(-1).body.p_on_date,'2026-09-20');});

test('editing old task preserves server CAS and can explicitly remove its date/time',async()=>{const h=harness();await h.ready();await h.client.saveTask({...form,id:uid(4),rowVersion:3,date:null,time:null},uid(102));const body=h.calls.find(c=>c.path.endsWith('/upsert_c010_stable_task')).body;assert.equal(body.p_task_id,uid(4));assert.equal(body.p_expected_row_version,3);assert.equal(body.p_due_date,null);assert.equal(body.p_due_time,null);});
test('task preference or role label cannot grant server-denied task creation',async()=>{const data=raw();data.round1.can_manage_tasks=false;data.workspace.capabilities={};const h=harness({data});await h.ready();await assert.rejects(()=>h.client.saveTask({...form,date:null},uid(103)));assert.equal(h.calls.filter(c=>c.path.endsWith('/upsert_c010_stable_task')).length,0);});
