import test from 'node:test';
import assert from 'node:assert/strict';
import {createP2Client,P2_RPC_NAMES} from '../p2-client.js';
const actor='10000000-0000-4000-8000-000000000001',org='10000000-0000-4000-8000-000000000002',horse='10000000-0000-4000-8000-000000000003',resource='10000000-0000-4000-8000-000000000004',booking='10000000-0000-4000-8000-000000000005',requestId='10000000-0000-4000-8000-000000000006';
const state=()=>({backend:{connected:true,actor:{id:actor},organizationId:org,todayDate:'2026-09-11',p2:{connected:true,organizationId:org,canManage:true,canBook:true}},horses:[{id:horse,organizationId:org,box:''}],facilities:{configuration:{rowVersion:3},resources:[{id:resource,name:'Stal 1',kind:'stall'}],placementVersions:{[horse]:7}}});
const workspace=()=>({profile_id:actor,organization_id:org,on_date:'2026-09-12',calendar:{today_date:'2026-09-11',selected_date:'2026-09-12',covered_dates:['2026-09-11','2026-09-12'],time_zone:'Europe/Amsterdam'},configuration:{row_version:3,counts:{stall:1,pasture:0,paddock:0,arena:0,walker:0,wash:0,locker:0},walker_capacity:1,tack_room:false},capabilities:{manage:true,book:true},resources:[{id:resource,kind:'stall',name:'Stal 1',note:'Gereed'}],placements:[{resourceId:resource,horseId:horse,rowVersion:7,note:''}],placementVersions:{[horse]:7},bookings:[],arenaBookings:[]});
function client(handler){let calls=[];return {calls,api:createP2Client({request:async(name,params,options)=>{calls.push({name,params,options});return handler(name,params,options)}})}}
const reads=(name)=>name==='get_my_c010_function_profile'?{profile_id:actor,functions:['rider'],row_version:1}:workspace();
test('read augments new snapshot only, current box and preference copied from server',async()=>{let {api}=client(reads),s=state(),before=structuredClone(s),r=await api.load(s,{day:'2026-09-12'});assert.deepEqual(s,before);assert.equal(r.horses[0].box,'Stal 1');assert.equal(r.facilityDate,'2026-09-12');assert.deepEqual(r.functionProfiles[actor],['rider']);assert.equal(r.backend.p2.canManage,true)});
test('no organization still loads own functions and no resources',async()=>{let {api,calls}=client(reads),s=state();s.backend.organizationId=null;const r=await api.load(s);assert.equal(calls.length,1);assert.equal(r.backend.p2.canManage,false);assert.deepEqual(r.facilities.resources,[])});
test('captured placement CAS comes from placement map, not horse row',async()=>{let {api,calls}=client(()=>({horse_id:horse,row_version:8}));let s=state();s.horses[0].rowVersion=200;await api.setPlacement(s,{horseId:horse,resourceId:resource,note:'Behouden'},requestId);assert.equal(calls[0].params.p_expected_row_version,7);assert.equal(calls[0].params.p_note,'Behouden');assert.deepEqual(calls[0].options,{write:true})});
test('explicit null placement CAS retained for new assignment',async()=>{let {api,calls}=client(()=>({horse_id:horse,row_version:1}));await api.setPlacement(state(),{horseId:horse,resourceId:resource,rowVersion:null},requestId);assert.equal(calls[0].params.p_expected_row_version,null)});
test('preference choice never changes permissions locally',async()=>{let s=state();s.backend.p2.canManage=false;let {api}=client(()=>({profile_id:actor,row_version:1}));await api.saveFunctions(s,['manager'],requestId);assert.equal(s.backend.p2.canManage,false)});
test('nonmanager configuration rejected before transport',async()=>{let s=state();s.backend.p2.canManage=false;let {api,calls}=client(()=>({}));assert.throws(()=>api.configure(s,{},requestId));assert.equal(calls.length,0)});
test('read-only response preserves redacted occupancy with no invented horse',async()=>{let w=workspace();w.placements=[{resourceId:resource,horseId:null,redacted:true}];w.resources[0].occupied=true;let {api}=client(n=>n==='get_my_c010_function_profile'?reads(n):w);let r=await api.load(state());assert.equal(r.facilities.placements[0].horseId,null);assert.equal(r.horses[0].box,'');assert.equal(r.facilities.resources[0].occupied,true)});
for(const [label,mutate] of [['missing collections',w=>delete w.bookings],['wrong profile',w=>w.profile_id=horse],['wrong organization',w=>w.organization_id=horse],['missing calendar',w=>delete w.calendar]])test('read fails closed: '+label,async()=>{let w=workspace();mutate(w);let {api}=client(n=>n==='get_my_c010_function_profile'?reads(n):w);await assert.rejects(api.load(state()))});
for(const [label,p] of [['missing functions',{profile_id:actor,row_version:1}],['invalid choice',{profile_id:actor,functions:['superadmin'],row_version:1}],['missing version',{profile_id:actor,functions:[]}],['wrong profile',{profile_id:horse,functions:[],row_version:null}]])test('preference response fails closed: '+label,async()=>{let {api}=client(n=>n==='get_my_c010_function_profile'?p:workspace());await assert.rejects(api.load(state()))});
const mutations=[['configure',(a,s)=>a.configure(s,{counts:{},walkerCapacity:1,tackRoom:false},requestId),'organization_id',org],['resource',(a,s)=>a.saveResource(s,{id:resource,rowVersion:1,name:'Box',status:'available',capacity:1},requestId),'resource_id',resource],['placement',(a,s)=>a.setPlacement(s,{horseId:horse,resourceId:resource},requestId),'horse_id',horse],['new booking',(a,s)=>a.saveBooking(s,{resourceId:resource,horseIds:[horse],date:'2026-09-12',start:'10:00',end:'11:00'},requestId),'booking_id',booking],['transition',(a,s)=>a.transitionBooking(s,{id:booking,rowVersion:1,action:'cancel'},requestId),'booking_id',booking],['functions',(a,s)=>a.saveFunctions(s,['rider'],requestId),'profile_id',actor]];
for(const [label,invoke,field,value]of mutations){test(label+' rejects version-only apparent success',async()=>{let{api}=client(()=>({row_version:1}));await assert.rejects(invoke(api,state()),e=>e.code==='INVALID_RESPONSE'&&e.uncertain===true)});test(label+' accepts identified versioned result',async()=>{let{api,calls}=client(()=>({[field]:value,row_version:2}));let r=await invoke(api,state());assert.equal(r[field],value);assert.equal(calls[0].options.write,true)});}
test('existing booking cannot accept response for another record',async()=>{let{api}=client(()=>({booking_id:resource,row_version:2}));await assert.rejects(api.saveBooking(state(),{id:booking,rowVersion:1,resourceId:resource,horseIds:[horse],date:'2026-09-12',start:'10:00',end:'11:00'},requestId),e=>e.code==='INVALID_RESPONSE'&&e.uncertain)});
test('capacity message updates userMessage favored by actual controller',async()=>{let error=Object.assign(new Error('server'),{code:'C010_FACILITY_CAPACITY_CONFLICT',userMessage:'Generic'});let{api}=client(()=>{throw error});await assert.rejects(api.transitionBooking(state(),{id:booking,rowVersion:1,action:'approve'},requestId),e=>e.userMessage===e.message&&e.message.includes('onvoldoende ruimte'))});
test('exact eight RPCs have no generic/direct-table endpoint',()=>{assert.equal(P2_RPC_NAMES.length,8);assert.ok(P2_RPC_NAMES.every(x=>/^[a-z_]+$/.test(x)||/^.*c010.*$/.test(x)))});
