// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final authCallbackPageHandle = ffai.ProjectPageHandle<AuthCallbackPageParams, AuthCallbackPageState>(
  name: "AuthCallbackPage",
  key: "Scaffold_qbppcchy",
  route: "auth/callback",
  params: const AuthCallbackPageParams(),
  state: const AuthCallbackPageState(),
  widgets: AuthCallbackPageWidgets.tree,
);

final class AuthCallbackPageParams {
  const AuthCallbackPageParams();
}

final class AuthCallbackPageState {
  const AuthCallbackPageState();
}

abstract final class AuthCallbackPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_qbppcchy",
      type: "Scaffold",
      path: "AuthCallbackPage",
      name: "AuthCallbackPage",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_oe5sxf6k",
            type: "Container",
            path: "AuthCallbackPage.body[0]",
            name: "Phase4AcallbackPageBody",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_jo4bprym",
                type: "Column",
                path: "AuthCallbackPage.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_h00itk67",
                    type: "Container",
                    path: "AuthCallbackPage.body[0].children[0].children[0]",
                    name: "Phase4AcallbackRuntime",
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}
