// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final feedingRoundExecutionPageHandle = ffai.ProjectPageHandle<FeedingRoundExecutionPageParams, FeedingRoundExecutionPageState>(
  name: "FeedingRoundExecutionPage",
  key: "Scaffold_dcjwss70",
  route: "voeding/ronde",
  params: const FeedingRoundExecutionPageParams(),
  state: const FeedingRoundExecutionPageState(),
  widgets: FeedingRoundExecutionPageWidgets.tree,
);

final class FeedingRoundExecutionPageParams {
  const FeedingRoundExecutionPageParams();
}
final class FeedingRoundExecutionPageState {
  const FeedingRoundExecutionPageState();
}

abstract final class FeedingRoundExecutionPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_dcjwss70",
      type: "Scaffold",
      path: "FeedingRoundExecutionPage",
      name: "FeedingRoundExecutionPage",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Row_brdjulim",
            type: "Row",
            path: "FeedingRoundExecutionPage.body[0]",
            name: "Phase4C7ResponsiveShell",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Container_rv2evmk5",
                type: "Container",
                path: "FeedingRoundExecutionPage.body[0].children[0]",
                name: "Phase4C7DesktopSideNavigation",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_agv14uff",
                    type: "Container",
                    path: "FeedingRoundExecutionPage.body[0].children[0].children[0]",
                    name: "AvarynDesktopNavigationBody",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_4hhykos3",
                        type: "Column",
                        path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0]",
                        name: "Column",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_wi9yfq1i",
                            type: "Container",
                            path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[0]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Column_zef6xkn8",
                                type: "Column",
                                path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[0].children[0]",
                                name: "Column",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_c5zcfc4w",
                                    type: "Text",
                                    path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[0].children[0].children[0]",
                                    name: "Text",
                                    text: "AVARYN",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_yrqmpgz8",
                                    type: "Text",
                                    path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[0].children[0].children[1]",
                                    name: "Text",
                                    text: "Performance",
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_qawd9bby",
                            type: "Container",
                            path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[1]",
                            name: "Container",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_ve7lnp65",
                            type: "Container",
                            path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[2]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_vijxmo7a",
                                type: "Row",
                                path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[2].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_krlaue3h",
                                    type: "Container",
                                    path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[2].children[0].children[0]",
                                    name: "Container",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Button_2jy75282",
                                    type: "Button",
                                    path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[2].children[0].children[1]",
                                    name: "Button",
                                    text: "Vandaag",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_p0t0e605",
                            type: "Container",
                            path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[3]",
                            name: "Container",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_425hvt9y",
                                type: "Row",
                                path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[3].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_hn83fab4",
                                    type: "Container",
                                    path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[3].children[0].children[0]",
                                    name: "Container",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_xnq1wxdd",
                                    type: "Container",
                                    path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[3].children[0].children[1]",
                                    name: "Container",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Row_9clhmkdu",
                                        type: "Row",
                                        path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[3].children[0].children[1].children[0]",
                                        name: "Row",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_yfqm6li1",
                                            type: "Container",
                                            path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[3].children[0].children[1].children[0].children[0]",
                                            name: "Container",
                                            children: <ffai.ProjectWidgetHandle>[
                                              ffai.ProjectWidgetHandle(
                                                key: "Container_azf1bx35",
                                                type: "Container",
                                                path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[3].children[0].children[1].children[0].children[0].children[0]",
                                                name: "AvarynHorseshoeIcon",
                                              ),
                                            ],
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_bzwqkoid",
                                            type: "Text",
                                            path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[3].children[0].children[1].children[0].children[1]",
                                            name: "Text",
                                            text: "Paarden",
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_xzvdijav",
                            type: "Container",
                            path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[4]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_efn9np1k",
                                type: "Row",
                                path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[4].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_fik30x9j",
                                    type: "Container",
                                    path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[4].children[0].children[0]",
                                    name: "Container",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Button_ths33i1i",
                                    type: "Button",
                                    path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[4].children[0].children[1]",
                                    name: "Button",
                                    text: "Voeding",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_dcdsci80",
                            type: "Container",
                            path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[5]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_ajp77cyz",
                                type: "Row",
                                path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[5].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_tpmc00u2",
                                    type: "Container",
                                    path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[5].children[0].children[0]",
                                    name: "Container",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Button_125ujlcs",
                                    type: "Button",
                                    path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[5].children[0].children[1]",
                                    name: "Button",
                                    text: "Planning",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_m6gc5zpm",
                            type: "Container",
                            path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[6]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_adtbbeeu",
                                type: "Row",
                                path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[6].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_3ts1anbl",
                                    type: "Container",
                                    path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[6].children[0].children[0]",
                                    name: "Container",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Button_pq3kri78",
                                    type: "Button",
                                    path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[6].children[0].children[1]",
                                    name: "Button",
                                    text: "Profiel",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Spacer_2psg9bbk",
                            type: "Spacer",
                            path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[7]",
                            name: "FlexSpacer",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_3l75uo7c",
                            type: "Container",
                            path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[8]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_ro7hnx65",
                                type: "Row",
                                path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[8].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Icon_179n9wp7",
                                    type: "Icon",
                                    path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[8].children[0].children[0]",
                                    name: "Icon",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_aocpucnr",
                                    type: "Column",
                                    path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[8].children[0].children[1]",
                                    name: "Column",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_dx12f4o7",
                                        type: "Text",
                                        path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[8].children[0].children[1].children[0]",
                                        name: "Text",
                                        text: "Besloten Alpha",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_koblmlek",
                                        type: "Text",
                                        path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[8].children[0].children[1].children[1]",
                                        name: "Text",
                                        text: "Geen productie",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Container_1nvj50vz",
                type: "Container",
                path: "FeedingRoundExecutionPage.body[0].children[1]",
                name: "Phase4C7OperationalColumnBounds",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Column_zq67wntj",
                    type: "Column",
                    path: "FeedingRoundExecutionPage.body[0].children[1].children[0]",
                    name: "Column",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_o1glz2rf",
                        type: "Container",
                        path: "FeedingRoundExecutionPage.body[0].children[1].children[0].children[0]",
                        name: "Phase4C7StableContextSelector",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_9xmizlx9",
                            type: "Container",
                            path: "FeedingRoundExecutionPage.body[0].children[1].children[0].children[0].children[0]",
                            name: "Phase4C7StableContextRuntime",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_dx21ngsa",
                        type: "Container",
                        path: "FeedingRoundExecutionPage.body[0].children[1].children[0].children[1]",
                        name: "Phase4C7OperationalRuntime",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_aqznn4fd",
                        type: "Container",
                        path: "FeedingRoundExecutionPage.body[0].children[1].children[0].children[2]",
                        name: "Phase4C7MobileBottomNavigation",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_jvvudoyu",
                            type: "Container",
                            path: "FeedingRoundExecutionPage.body[0].children[1].children[0].children[2].children[0]",
                            name: "AvarynMobileNavigationBody",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_8xx7ge18",
                                type: "Row",
                                path: "FeedingRoundExecutionPage.body[0].children[1].children[0].children[2].children[0].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_rlzktl23",
                                    type: "Container",
                                    path: "FeedingRoundExecutionPage.body[0].children[1].children[0].children[2].children[0].children[0].children[0]",
                                    name: "Container",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Column_5lzrgiqe",
                                        type: "Column",
                                        path: "FeedingRoundExecutionPage.body[0].children[1].children[0].children[2].children[0].children[0].children[0].children[0]",
                                        name: "Column",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_u124nq90",
                                            type: "Container",
                                            path: "FeedingRoundExecutionPage.body[0].children[1].children[0].children[2].children[0].children[0].children[0].children[0].children[0]",
                                            name: "Container",
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Icon_ldj8bh46",
                                            type: "Icon",
                                            path: "FeedingRoundExecutionPage.body[0].children[1].children[0].children[2].children[0].children[0].children[0].children[0].children[1]",
                                            name: "Icon",
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_88elofv9",
                                            type: "Text",
                                            path: "FeedingRoundExecutionPage.body[0].children[1].children[0].children[2].children[0].children[0].children[0].children[0].children[2]",
                                            name: "Text",
                                            text: "Vandaag",
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_styrwa9x",
                                    type: "Container",
                                    path: "FeedingRoundExecutionPage.body[0].children[1].children[0].children[2].children[0].children[0].children[1]",
                                    name: "Container",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Column_npkzv1qr",
                                        type: "Column",
                                        path: "FeedingRoundExecutionPage.body[0].children[1].children[0].children[2].children[0].children[0].children[1].children[0]",
                                        name: "Column",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_yw54ojrn",
                                            type: "Container",
                                            path: "FeedingRoundExecutionPage.body[0].children[1].children[0].children[2].children[0].children[0].children[1].children[0].children[0]",
                                            name: "Container",
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_701xq855",
                                            type: "Container",
                                            path: "FeedingRoundExecutionPage.body[0].children[1].children[0].children[2].children[0].children[0].children[1].children[0].children[1]",
                                            name: "Container",
                                            children: <ffai.ProjectWidgetHandle>[
                                              ffai.ProjectWidgetHandle(
                                                key: "Container_6kajuogo",
                                                type: "Container",
                                                path: "FeedingRoundExecutionPage.body[0].children[1].children[0].children[2].children[0].children[0].children[1].children[0].children[1].children[0]",
                                                name: "AvarynHorseshoeIcon",
                                              ),
                                            ],
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_qj110nxz",
                                            type: "Text",
                                            path: "FeedingRoundExecutionPage.body[0].children[1].children[0].children[2].children[0].children[0].children[1].children[0].children[2]",
                                            name: "Text",
                                            text: "Paarden",
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_oxjfdk37",
                                    type: "Container",
                                    path: "FeedingRoundExecutionPage.body[0].children[1].children[0].children[2].children[0].children[0].children[2]",
                                    name: "Container",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Column_2t23wxi1",
                                        type: "Column",
                                        path: "FeedingRoundExecutionPage.body[0].children[1].children[0].children[2].children[0].children[0].children[2].children[0]",
                                        name: "Column",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_s3akbsxo",
                                            type: "Container",
                                            path: "FeedingRoundExecutionPage.body[0].children[1].children[0].children[2].children[0].children[0].children[2].children[0].children[0]",
                                            name: "Container",
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Icon_oqcwui4s",
                                            type: "Icon",
                                            path: "FeedingRoundExecutionPage.body[0].children[1].children[0].children[2].children[0].children[0].children[2].children[0].children[1]",
                                            name: "Icon",
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_bllkgoq6",
                                            type: "Text",
                                            path: "FeedingRoundExecutionPage.body[0].children[1].children[0].children[2].children[0].children[0].children[2].children[0].children[2]",
                                            name: "Text",
                                            text: "Voeding",
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_h2icink5",
                                    type: "Container",
                                    path: "FeedingRoundExecutionPage.body[0].children[1].children[0].children[2].children[0].children[0].children[3]",
                                    name: "Container",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Column_lscfypqg",
                                        type: "Column",
                                        path: "FeedingRoundExecutionPage.body[0].children[1].children[0].children[2].children[0].children[0].children[3].children[0]",
                                        name: "Column",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_mco55c04",
                                            type: "Container",
                                            path: "FeedingRoundExecutionPage.body[0].children[1].children[0].children[2].children[0].children[0].children[3].children[0].children[0]",
                                            name: "Container",
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Icon_lmlkz1r1",
                                            type: "Icon",
                                            path: "FeedingRoundExecutionPage.body[0].children[1].children[0].children[2].children[0].children[0].children[3].children[0].children[1]",
                                            name: "Icon",
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_rp4hkf3z",
                                            type: "Text",
                                            path: "FeedingRoundExecutionPage.body[0].children[1].children[0].children[2].children[0].children[0].children[3].children[0].children[2]",
                                            name: "Text",
                                            text: "Planning",
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_yen9lusz",
                                    type: "Container",
                                    path: "FeedingRoundExecutionPage.body[0].children[1].children[0].children[2].children[0].children[0].children[4]",
                                    name: "Container",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Column_l5slnu0a",
                                        type: "Column",
                                        path: "FeedingRoundExecutionPage.body[0].children[1].children[0].children[2].children[0].children[0].children[4].children[0]",
                                        name: "Column",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_fl57glu7",
                                            type: "Container",
                                            path: "FeedingRoundExecutionPage.body[0].children[1].children[0].children[2].children[0].children[0].children[4].children[0].children[0]",
                                            name: "Container",
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Icon_9s95nsql",
                                            type: "Icon",
                                            path: "FeedingRoundExecutionPage.body[0].children[1].children[0].children[2].children[0].children[0].children[4].children[0].children[1]",
                                            name: "Icon",
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_m8zkv7gz",
                                            type: "Text",
                                            path: "FeedingRoundExecutionPage.body[0].children[1].children[0].children[2].children[0].children[0].children[4].children[0].children[2]",
                                            name: "Text",
                                            text: "Profiel",
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}
