// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final feedingRoundExecutionPageHandle = ffai.ProjectPageHandle<FeedingRoundExecutionPageParams, FeedingRoundExecutionPageState>(
  name: "FeedingRoundExecutionPage",
  key: "Scaffold_dcjwss70",
  route: "voeding/ronde",
  params: const FeedingRoundExecutionPageParams(),
  state: const FeedingRoundExecutionPageState(),
  widgets: FeedingRoundExecutionPageWidgets.tree,
);

final class FeedingRoundExecutionPageParams {
  const FeedingRoundExecutionPageParams();
}

final class FeedingRoundExecutionPageState {
  const FeedingRoundExecutionPageState();
}

abstract final class FeedingRoundExecutionPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_dcjwss70",
      type: "Scaffold",
      path: "FeedingRoundExecutionPage",
      name: "FeedingRoundExecutionPage",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Row_sy801qp5",
            type: "Row",
            path: "FeedingRoundExecutionPage.body[0]",
            name: "FeedingRoundExecutionResponsiveShell",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Container_s4prrgoo",
                type: "Container",
                path: "FeedingRoundExecutionPage.body[0].children[0]",
                name: "FeedingRoundExecutionDesktopSideNavigation",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_v0t59duo",
                    type: "Container",
                    path: "FeedingRoundExecutionPage.body[0].children[0].children[0]",
                    name: "AvarynDesktopNavigationBody",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_e7tcavcj",
                        type: "Column",
                        path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0]",
                        name: "Column",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_latmv39n",
                            type: "Container",
                            path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[0]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Column_jr3kee2h",
                                type: "Column",
                                path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[0].children[0]",
                                name: "Column",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_u7xmgj83",
                                    type: "Text",
                                    path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[0].children[0].children[0]",
                                    name: "Text",
                                    text: "AVARYN",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_u1orduf0",
                                    type: "Text",
                                    path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[0].children[0].children[1]",
                                    name: "Text",
                                    text: "Performance",
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_eycm5rdy",
                            type: "Container",
                            path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[1]",
                            name: "Container",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_hc6of8i8",
                            type: "Container",
                            path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[2]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_4e1s1tm4",
                                type: "Row",
                                path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[2].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_4wo8ul6j",
                                    type: "Container",
                                    path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[2].children[0].children[0]",
                                    name: "Container",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Button_mf7fz9xb",
                                    type: "Button",
                                    path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[2].children[0].children[1]",
                                    name: "Button",
                                    text: "Vandaag",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_h5ih7vfq",
                            type: "Container",
                            path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[3]",
                            name: "Container",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_ogoy6z7o",
                                type: "Row",
                                path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[3].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_rvj7pz02",
                                    type: "Container",
                                    path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[3].children[0].children[0]",
                                    name: "Container",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_u7lj2j3h",
                                    type: "Container",
                                    path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[3].children[0].children[1]",
                                    name: "Container",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Row_qal52x28",
                                        type: "Row",
                                        path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[3].children[0].children[1].children[0]",
                                        name: "Row",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_nz90trei",
                                            type: "Container",
                                            path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[3].children[0].children[1].children[0].children[0]",
                                            name: "Container",
                                            children: <ffai.ProjectWidgetHandle>[
                                              ffai.ProjectWidgetHandle(
                                                key: "Container_6l9p34mn",
                                                type: "Container",
                                                path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[3].children[0].children[1].children[0].children[0].children[0]",
                                                name: "AvarynHorseshoeIcon",
                                              ),
                                            ],
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_dukdgnfs",
                                            type: "Text",
                                            path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[3].children[0].children[1].children[0].children[1]",
                                            name: "Text",
                                            text: "Paarden",
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_jizt3gj7",
                            type: "Container",
                            path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[4]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_ozhjeesi",
                                type: "Row",
                                path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[4].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_ywupuw6o",
                                    type: "Container",
                                    path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[4].children[0].children[0]",
                                    name: "Container",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Button_fjyza66c",
                                    type: "Button",
                                    path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[4].children[0].children[1]",
                                    name: "Button",
                                    text: "Planning",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_k1iorv2g",
                            type: "Container",
                            path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[5]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_i1mmvtsl",
                                type: "Row",
                                path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[5].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_xra6eruk",
                                    type: "Container",
                                    path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[5].children[0].children[0]",
                                    name: "Container",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Button_w7ghvose",
                                    type: "Button",
                                    path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[5].children[0].children[1]",
                                    name: "Button",
                                    text: "Wedstrijden",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_nshobwo5",
                            type: "Container",
                            path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[6]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_dy7qqpf1",
                                type: "Row",
                                path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[6].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_cv00af7d",
                                    type: "Container",
                                    path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[6].children[0].children[0]",
                                    name: "Container",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Button_or5kz2sq",
                                    type: "Button",
                                    path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[6].children[0].children[1]",
                                    name: "Button",
                                    text: "Profiel",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Spacer_sasb1g82",
                            type: "Spacer",
                            path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[7]",
                            name: "FlexSpacer",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_yjhzcz48",
                            type: "Container",
                            path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[8]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_warkjyx2",
                                type: "Row",
                                path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[8].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Icon_uq2qzl42",
                                    type: "Icon",
                                    path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[8].children[0].children[0]",
                                    name: "Icon",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_4d2cc4lk",
                                    type: "Column",
                                    path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[8].children[0].children[1]",
                                    name: "Column",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_vqt09nkf",
                                        type: "Text",
                                        path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[8].children[0].children[1].children[0]",
                                        name: "Text",
                                        text: "Local prototype",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_2za2lhgo",
                                        type: "Text",
                                        path: "FeedingRoundExecutionPage.body[0].children[0].children[0].children[0].children[8].children[0].children[1].children[1]",
                                        name: "Text",
                                        text: "Sample data only",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Column_dqbxejcv",
                type: "Column",
                path: "FeedingRoundExecutionPage.body[0].children[1]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_w3kuw0ll",
                    type: "Container",
                    path: "FeedingRoundExecutionPage.body[0].children[1].children[0]",
                    name: "FeedingRoundExecutionRuntime",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_1jpj5hdf",
                    type: "Container",
                    path: "FeedingRoundExecutionPage.body[0].children[1].children[1]",
                    name: "FeedingRoundExecutionMobileBottomNavigation",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_q22oziib",
                        type: "Container",
                        path: "FeedingRoundExecutionPage.body[0].children[1].children[1].children[0]",
                        name: "AvarynMobileNavigationBody",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Row_996i5ugf",
                            type: "Row",
                            path: "FeedingRoundExecutionPage.body[0].children[1].children[1].children[0].children[0]",
                            name: "Row",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Container_6jsz00lx",
                                type: "Container",
                                path: "FeedingRoundExecutionPage.body[0].children[1].children[1].children[0].children[0].children[0]",
                                name: "Container",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_4cqyshox",
                                    type: "Column",
                                    path: "FeedingRoundExecutionPage.body[0].children[1].children[1].children[0].children[0].children[0].children[0]",
                                    name: "Column",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_5kkux0b9",
                                        type: "Container",
                                        path: "FeedingRoundExecutionPage.body[0].children[1].children[1].children[0].children[0].children[0].children[0].children[0]",
                                        name: "Container",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_3uhc88de",
                                        type: "Icon",
                                        path: "FeedingRoundExecutionPage.body[0].children[1].children[1].children[0].children[0].children[0].children[0].children[1]",
                                        name: "Icon",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_to7f4om0",
                                        type: "Text",
                                        path: "FeedingRoundExecutionPage.body[0].children[1].children[1].children[0].children[0].children[0].children[0].children[2]",
                                        name: "Text",
                                        text: "Vandaag",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Container_49rsvgi9",
                                type: "Container",
                                path: "FeedingRoundExecutionPage.body[0].children[1].children[1].children[0].children[0].children[1]",
                                name: "Container",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_7p1h03tw",
                                    type: "Column",
                                    path: "FeedingRoundExecutionPage.body[0].children[1].children[1].children[0].children[0].children[1].children[0]",
                                    name: "Column",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_zpxlx0ei",
                                        type: "Container",
                                        path: "FeedingRoundExecutionPage.body[0].children[1].children[1].children[0].children[0].children[1].children[0].children[0]",
                                        name: "Container",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_y30i85fo",
                                        type: "Container",
                                        path: "FeedingRoundExecutionPage.body[0].children[1].children[1].children[0].children[0].children[1].children[0].children[1]",
                                        name: "Container",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_kgu74fr6",
                                            type: "Container",
                                            path: "FeedingRoundExecutionPage.body[0].children[1].children[1].children[0].children[0].children[1].children[0].children[1].children[0]",
                                            name: "AvarynHorseshoeIcon",
                                          ),
                                        ],
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_ynxyw24g",
                                        type: "Text",
                                        path: "FeedingRoundExecutionPage.body[0].children[1].children[1].children[0].children[0].children[1].children[0].children[2]",
                                        name: "Text",
                                        text: "Paarden",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Container_xaog0ocz",
                                type: "Container",
                                path: "FeedingRoundExecutionPage.body[0].children[1].children[1].children[0].children[0].children[2]",
                                name: "Container",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_edhh938j",
                                    type: "Column",
                                    path: "FeedingRoundExecutionPage.body[0].children[1].children[1].children[0].children[0].children[2].children[0]",
                                    name: "Column",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_fxxq4rtu",
                                        type: "Container",
                                        path: "FeedingRoundExecutionPage.body[0].children[1].children[1].children[0].children[0].children[2].children[0].children[0]",
                                        name: "Container",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_455kbdvs",
                                        type: "Icon",
                                        path: "FeedingRoundExecutionPage.body[0].children[1].children[1].children[0].children[0].children[2].children[0].children[1]",
                                        name: "Icon",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_7tc226fh",
                                        type: "Text",
                                        path: "FeedingRoundExecutionPage.body[0].children[1].children[1].children[0].children[0].children[2].children[0].children[2]",
                                        name: "Text",
                                        text: "Planning",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Container_gz5duoa0",
                                type: "Container",
                                path: "FeedingRoundExecutionPage.body[0].children[1].children[1].children[0].children[0].children[3]",
                                name: "Container",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_1xxoqln7",
                                    type: "Column",
                                    path: "FeedingRoundExecutionPage.body[0].children[1].children[1].children[0].children[0].children[3].children[0]",
                                    name: "Column",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_js4i9nki",
                                        type: "Container",
                                        path: "FeedingRoundExecutionPage.body[0].children[1].children[1].children[0].children[0].children[3].children[0].children[0]",
                                        name: "Container",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_kgebio33",
                                        type: "Icon",
                                        path: "FeedingRoundExecutionPage.body[0].children[1].children[1].children[0].children[0].children[3].children[0].children[1]",
                                        name: "Icon",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_95tg2l6a",
                                        type: "Text",
                                        path: "FeedingRoundExecutionPage.body[0].children[1].children[1].children[0].children[0].children[3].children[0].children[2]",
                                        name: "Text",
                                        text: "Wedstrijden",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Container_pbv53ucy",
                                type: "Container",
                                path: "FeedingRoundExecutionPage.body[0].children[1].children[1].children[0].children[0].children[4]",
                                name: "Container",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_wm91da0x",
                                    type: "Column",
                                    path: "FeedingRoundExecutionPage.body[0].children[1].children[1].children[0].children[0].children[4].children[0]",
                                    name: "Column",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_vg0w0094",
                                        type: "Container",
                                        path: "FeedingRoundExecutionPage.body[0].children[1].children[1].children[0].children[0].children[4].children[0].children[0]",
                                        name: "Container",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_b7c0g7ge",
                                        type: "Icon",
                                        path: "FeedingRoundExecutionPage.body[0].children[1].children[1].children[0].children[0].children[4].children[0].children[1]",
                                        name: "Icon",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_6jflifit",
                                        type: "Text",
                                        path: "FeedingRoundExecutionPage.body[0].children[1].children[1].children[0].children[0].children[4].children[0].children[2]",
                                        name: "Text",
                                        text: "Profiel",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

