// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final horsesOverviewPageHandle =
    ffai.ProjectPageHandle<HorsesOverviewPageParams, HorsesOverviewPageState>(
      name: "HorsesOverviewPage",
      key: "Scaffold_z0m2k0lv",
      route: "paarden",
      params: const HorsesOverviewPageParams(),
      state: const HorsesOverviewPageState(),
      widgets: HorsesOverviewPageWidgets.tree,
    );

final class HorsesOverviewPageParams {
  const HorsesOverviewPageParams();
}

final class HorsesOverviewPageState {
  const HorsesOverviewPageState();
}

abstract final class HorsesOverviewPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_z0m2k0lv",
      type: "Scaffold",
      path: "HorsesOverviewPage",
      name: "HorsesOverviewPage",
      triggers: const <String>["ON_INIT_STATE"],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Row_y8bgtbpn",
            type: "Row",
            path: "HorsesOverviewPage.body[0]",
            name: "Phase4C7ResponsiveShell",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Container_kl7zm7qv",
                type: "Container",
                path: "HorsesOverviewPage.body[0].children[0]",
                name: "Phase4C7DesktopSideNavigation",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_g944g2yk",
                    type: "Container",
                    path: "HorsesOverviewPage.body[0].children[0].children[0]",
                    name: "AvarynDesktopNavigationBody",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_80jo8buf",
                        type: "Column",
                        path:
                            "HorsesOverviewPage.body[0].children[0].children[0].children[0]",
                        name: "Column",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_dmgru16g",
                            type: "Container",
                            path:
                                "HorsesOverviewPage.body[0].children[0].children[0].children[0].children[0]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Column_bdaxic4l",
                                type: "Column",
                                path:
                                    "HorsesOverviewPage.body[0].children[0].children[0].children[0].children[0].children[0]",
                                name: "Column",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_emomz8rs",
                                    type: "Text",
                                    path:
                                        "HorsesOverviewPage.body[0].children[0].children[0].children[0].children[0].children[0].children[0]",
                                    name: "Text",
                                    text: "AVARYN",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_yx0rr29s",
                                    type: "Text",
                                    path:
                                        "HorsesOverviewPage.body[0].children[0].children[0].children[0].children[0].children[0].children[1]",
                                    name: "Text",
                                    text: "Performance",
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_5vt852du",
                            type: "Container",
                            path:
                                "HorsesOverviewPage.body[0].children[0].children[0].children[0].children[1]",
                            name: "Container",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_yefv2itl",
                            type: "Container",
                            path:
                                "HorsesOverviewPage.body[0].children[0].children[0].children[0].children[2]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_a3xp2grs",
                                type: "Row",
                                path:
                                    "HorsesOverviewPage.body[0].children[0].children[0].children[0].children[2].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_jj1gtagp",
                                    type: "Container",
                                    path:
                                        "HorsesOverviewPage.body[0].children[0].children[0].children[0].children[2].children[0].children[0]",
                                    name: "Container",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Button_62d4g9uv",
                                    type: "Button",
                                    path:
                                        "HorsesOverviewPage.body[0].children[0].children[0].children[0].children[2].children[0].children[1]",
                                    name: "Button",
                                    text: "Vandaag",
                                    triggers: const <String>["ON_TAP"],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_acle5gxg",
                            type: "Container",
                            path:
                                "HorsesOverviewPage.body[0].children[0].children[0].children[0].children[3]",
                            name: "Container",
                            triggers: const <String>["ON_TAP"],
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_emnn3l7k",
                                type: "Row",
                                path:
                                    "HorsesOverviewPage.body[0].children[0].children[0].children[0].children[3].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_ejh7qq25",
                                    type: "Container",
                                    path:
                                        "HorsesOverviewPage.body[0].children[0].children[0].children[0].children[3].children[0].children[0]",
                                    name: "Container",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_jkr5ji18",
                                    type: "Container",
                                    path:
                                        "HorsesOverviewPage.body[0].children[0].children[0].children[0].children[3].children[0].children[1]",
                                    name: "Container",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Row_mxumc957",
                                        type: "Row",
                                        path:
                                            "HorsesOverviewPage.body[0].children[0].children[0].children[0].children[3].children[0].children[1].children[0]",
                                        name: "Row",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_qof0wjik",
                                            type: "Container",
                                            path:
                                                "HorsesOverviewPage.body[0].children[0].children[0].children[0].children[3].children[0].children[1].children[0].children[0]",
                                            name: "Container",
                                            children: <
                                              ffai.ProjectWidgetHandle
                                            >[
                                              ffai.ProjectWidgetHandle(
                                                key: "Container_7326c0i1",
                                                type: "Container",
                                                path:
                                                    "HorsesOverviewPage.body[0].children[0].children[0].children[0].children[3].children[0].children[1].children[0].children[0].children[0]",
                                                name: "AvarynHorseshoeIcon",
                                              ),
                                            ],
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_erge0pnl",
                                            type: "Text",
                                            path:
                                                "HorsesOverviewPage.body[0].children[0].children[0].children[0].children[3].children[0].children[1].children[0].children[1]",
                                            name: "Text",
                                            text: "Paarden",
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_e2gt95bb",
                            type: "Container",
                            path:
                                "HorsesOverviewPage.body[0].children[0].children[0].children[0].children[4]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_huj6yyye",
                                type: "Row",
                                path:
                                    "HorsesOverviewPage.body[0].children[0].children[0].children[0].children[4].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_izqm7r6k",
                                    type: "Container",
                                    path:
                                        "HorsesOverviewPage.body[0].children[0].children[0].children[0].children[4].children[0].children[0]",
                                    name: "Container",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Button_2v0ciol8",
                                    type: "Button",
                                    path:
                                        "HorsesOverviewPage.body[0].children[0].children[0].children[0].children[4].children[0].children[1]",
                                    name: "Button",
                                    text: "Planning",
                                    triggers: const <String>["ON_TAP"],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_cd25g9ka",
                            type: "Container",
                            path:
                                "HorsesOverviewPage.body[0].children[0].children[0].children[0].children[5]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_dt3qam0m",
                                type: "Row",
                                path:
                                    "HorsesOverviewPage.body[0].children[0].children[0].children[0].children[5].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_k4anwmgc",
                                    type: "Container",
                                    path:
                                        "HorsesOverviewPage.body[0].children[0].children[0].children[0].children[5].children[0].children[0]",
                                    name: "Container",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Button_5haffo1f",
                                    type: "Button",
                                    path:
                                        "HorsesOverviewPage.body[0].children[0].children[0].children[0].children[5].children[0].children[1]",
                                    name: "Button",
                                    text: "Profiel",
                                    triggers: const <String>["ON_TAP"],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Spacer_o4pocfxh",
                            type: "Spacer",
                            path:
                                "HorsesOverviewPage.body[0].children[0].children[0].children[0].children[6]",
                            name: "FlexSpacer",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_xat7kxn4",
                            type: "Container",
                            path:
                                "HorsesOverviewPage.body[0].children[0].children[0].children[0].children[7]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_7xbfy7qo",
                                type: "Row",
                                path:
                                    "HorsesOverviewPage.body[0].children[0].children[0].children[0].children[7].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Icon_mm73yg5g",
                                    type: "Icon",
                                    path:
                                        "HorsesOverviewPage.body[0].children[0].children[0].children[0].children[7].children[0].children[0]",
                                    name: "Icon",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_cxytb5gk",
                                    type: "Column",
                                    path:
                                        "HorsesOverviewPage.body[0].children[0].children[0].children[0].children[7].children[0].children[1]",
                                    name: "Column",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_0gph3gdn",
                                        type: "Text",
                                        path:
                                            "HorsesOverviewPage.body[0].children[0].children[0].children[0].children[7].children[0].children[1].children[0]",
                                        name: "Text",
                                        text: "Besloten Alpha",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_q2v8v2mj",
                                        type: "Text",
                                        path:
                                            "HorsesOverviewPage.body[0].children[0].children[0].children[0].children[7].children[0].children[1].children[1]",
                                        name: "Text",
                                        text: "Geen productie",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Column_s1z2db5c",
                type: "Column",
                path: "HorsesOverviewPage.body[0].children[1]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_dsbg75cf",
                    type: "Container",
                    path: "HorsesOverviewPage.body[0].children[1].children[0]",
                    name: "Phase4C7StableContextSelector",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_zw2ll1jh",
                        type: "Container",
                        path:
                            "HorsesOverviewPage.body[0].children[1].children[0].children[0]",
                        name: "Phase4C7StableContextRuntime",
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_fo4km9lp",
                    type: "Container",
                    path: "HorsesOverviewPage.body[0].children[1].children[1]",
                    name: "Phase4C7OperationalRuntime",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_ysuf8dqq",
                    type: "Container",
                    path: "HorsesOverviewPage.body[0].children[1].children[2]",
                    name: "Phase4C7MobileBottomNavigation",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_6ixgregx",
                        type: "Container",
                        path:
                            "HorsesOverviewPage.body[0].children[1].children[2].children[0]",
                        name: "AvarynMobileNavigationBody",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Row_n4utkjig",
                            type: "Row",
                            path:
                                "HorsesOverviewPage.body[0].children[1].children[2].children[0].children[0]",
                            name: "Row",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Container_d9quy31e",
                                type: "Container",
                                path:
                                    "HorsesOverviewPage.body[0].children[1].children[2].children[0].children[0].children[0]",
                                name: "Container",
                                triggers: const <String>["ON_TAP"],
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_6k43dwfp",
                                    type: "Column",
                                    path:
                                        "HorsesOverviewPage.body[0].children[1].children[2].children[0].children[0].children[0].children[0]",
                                    name: "Column",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_re057n1g",
                                        type: "Container",
                                        path:
                                            "HorsesOverviewPage.body[0].children[1].children[2].children[0].children[0].children[0].children[0].children[0]",
                                        name: "Container",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_x81w4fj4",
                                        type: "Icon",
                                        path:
                                            "HorsesOverviewPage.body[0].children[1].children[2].children[0].children[0].children[0].children[0].children[1]",
                                        name: "Icon",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_age06xd9",
                                        type: "Text",
                                        path:
                                            "HorsesOverviewPage.body[0].children[1].children[2].children[0].children[0].children[0].children[0].children[2]",
                                        name: "Text",
                                        text: "Vandaag",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Container_r28z4c1b",
                                type: "Container",
                                path:
                                    "HorsesOverviewPage.body[0].children[1].children[2].children[0].children[0].children[1]",
                                name: "Container",
                                triggers: const <String>["ON_TAP"],
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_2w8mmkc9",
                                    type: "Column",
                                    path:
                                        "HorsesOverviewPage.body[0].children[1].children[2].children[0].children[0].children[1].children[0]",
                                    name: "Column",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_cjm5hmfv",
                                        type: "Container",
                                        path:
                                            "HorsesOverviewPage.body[0].children[1].children[2].children[0].children[0].children[1].children[0].children[0]",
                                        name: "Container",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_i8qtd3f0",
                                        type: "Container",
                                        path:
                                            "HorsesOverviewPage.body[0].children[1].children[2].children[0].children[0].children[1].children[0].children[1]",
                                        name: "Container",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_8015hxkq",
                                            type: "Container",
                                            path:
                                                "HorsesOverviewPage.body[0].children[1].children[2].children[0].children[0].children[1].children[0].children[1].children[0]",
                                            name: "AvarynHorseshoeIcon",
                                          ),
                                        ],
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_qcy70ux0",
                                        type: "Text",
                                        path:
                                            "HorsesOverviewPage.body[0].children[1].children[2].children[0].children[0].children[1].children[0].children[2]",
                                        name: "Text",
                                        text: "Paarden",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Container_vux3u5wn",
                                type: "Container",
                                path:
                                    "HorsesOverviewPage.body[0].children[1].children[2].children[0].children[0].children[2]",
                                name: "Container",
                                triggers: const <String>["ON_TAP"],
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_bynt6fz6",
                                    type: "Column",
                                    path:
                                        "HorsesOverviewPage.body[0].children[1].children[2].children[0].children[0].children[2].children[0]",
                                    name: "Column",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_g04ny16r",
                                        type: "Container",
                                        path:
                                            "HorsesOverviewPage.body[0].children[1].children[2].children[0].children[0].children[2].children[0].children[0]",
                                        name: "Container",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_7m8ph8wd",
                                        type: "Icon",
                                        path:
                                            "HorsesOverviewPage.body[0].children[1].children[2].children[0].children[0].children[2].children[0].children[1]",
                                        name: "Icon",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_x340n168",
                                        type: "Text",
                                        path:
                                            "HorsesOverviewPage.body[0].children[1].children[2].children[0].children[0].children[2].children[0].children[2]",
                                        name: "Text",
                                        text: "Planning",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Container_svjelr4i",
                                type: "Container",
                                path:
                                    "HorsesOverviewPage.body[0].children[1].children[2].children[0].children[0].children[3]",
                                name: "Container",
                                triggers: const <String>["ON_TAP"],
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_hiepj72w",
                                    type: "Column",
                                    path:
                                        "HorsesOverviewPage.body[0].children[1].children[2].children[0].children[0].children[3].children[0]",
                                    name: "Column",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_rzo5xnld",
                                        type: "Container",
                                        path:
                                            "HorsesOverviewPage.body[0].children[1].children[2].children[0].children[0].children[3].children[0].children[0]",
                                        name: "Container",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_zrhcp4y2",
                                        type: "Icon",
                                        path:
                                            "HorsesOverviewPage.body[0].children[1].children[2].children[0].children[0].children[3].children[0].children[1]",
                                        name: "Icon",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_xqjp5o4q",
                                        type: "Text",
                                        path:
                                            "HorsesOverviewPage.body[0].children[1].children[2].children[0].children[0].children[3].children[0].children[2]",
                                        name: "Text",
                                        text: "Profiel",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}
