// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final inviteStableMemberPageHandle = ffai.ProjectPageHandle<InviteStableMemberPageParams, InviteStableMemberPageState>(
  name: "InviteStableMemberPage",
  key: "Scaffold_t2ou950j",
  route: "stal/uitnodigen",
  params: const InviteStableMemberPageParams(),
  state: const InviteStableMemberPageState(),
  widgets: InviteStableMemberPageWidgets.tree,
);

final class InviteStableMemberPageParams {
  const InviteStableMemberPageParams();
}

final class InviteStableMemberPageState {
  const InviteStableMemberPageState();
}

abstract final class InviteStableMemberPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_t2ou950j",
      type: "Scaffold",
      path: "InviteStableMemberPage",
      name: "InviteStableMemberPage",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Row_k87s2k9r",
            type: "Row",
            path: "InviteStableMemberPage.body[0]",
            name: "Phase4BResponsiveShell",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Container_czipeivx",
                type: "Container",
                path: "InviteStableMemberPage.body[0].children[0]",
                name: "Phase4BDesktopSideNavigation",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_lavjzbw4",
                    type: "Container",
                    path: "InviteStableMemberPage.body[0].children[0].children[0]",
                    name: "AvarynDesktopNavigationBody",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_6xc020ba",
                        type: "Column",
                        path: "InviteStableMemberPage.body[0].children[0].children[0].children[0]",
                        name: "Column",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_lipb3gw3",
                            type: "Container",
                            path: "InviteStableMemberPage.body[0].children[0].children[0].children[0].children[0]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Column_hei25nt4",
                                type: "Column",
                                path: "InviteStableMemberPage.body[0].children[0].children[0].children[0].children[0].children[0]",
                                name: "Column",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_44bigz42",
                                    type: "Text",
                                    path: "InviteStableMemberPage.body[0].children[0].children[0].children[0].children[0].children[0].children[0]",
                                    name: "Text",
                                    text: "AVARYN",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_h3v0ue5n",
                                    type: "Text",
                                    path: "InviteStableMemberPage.body[0].children[0].children[0].children[0].children[0].children[0].children[1]",
                                    name: "Text",
                                    text: "Performance",
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_2pp3i2ek",
                            type: "Container",
                            path: "InviteStableMemberPage.body[0].children[0].children[0].children[0].children[1]",
                            name: "Container",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_3hikzfni",
                            type: "Container",
                            path: "InviteStableMemberPage.body[0].children[0].children[0].children[0].children[2]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_s0s6q5nt",
                                type: "Row",
                                path: "InviteStableMemberPage.body[0].children[0].children[0].children[0].children[2].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_nnysxsve",
                                    type: "Container",
                                    path: "InviteStableMemberPage.body[0].children[0].children[0].children[0].children[2].children[0].children[0]",
                                    name: "Container",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Button_7ovgtoe5",
                                    type: "Button",
                                    path: "InviteStableMemberPage.body[0].children[0].children[0].children[0].children[2].children[0].children[1]",
                                    name: "Button",
                                    text: "Vandaag",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_i7kpzfgg",
                            type: "Container",
                            path: "InviteStableMemberPage.body[0].children[0].children[0].children[0].children[3]",
                            name: "Container",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_tbchwvfx",
                                type: "Row",
                                path: "InviteStableMemberPage.body[0].children[0].children[0].children[0].children[3].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_vo5zr97a",
                                    type: "Container",
                                    path: "InviteStableMemberPage.body[0].children[0].children[0].children[0].children[3].children[0].children[0]",
                                    name: "Container",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_lrj6at6v",
                                    type: "Container",
                                    path: "InviteStableMemberPage.body[0].children[0].children[0].children[0].children[3].children[0].children[1]",
                                    name: "Container",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Row_nb7y2p77",
                                        type: "Row",
                                        path: "InviteStableMemberPage.body[0].children[0].children[0].children[0].children[3].children[0].children[1].children[0]",
                                        name: "Row",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_379okrk5",
                                            type: "Container",
                                            path: "InviteStableMemberPage.body[0].children[0].children[0].children[0].children[3].children[0].children[1].children[0].children[0]",
                                            name: "Container",
                                            children: <ffai.ProjectWidgetHandle>[
                                              ffai.ProjectWidgetHandle(
                                                key: "Container_gj3pyb2m",
                                                type: "Container",
                                                path: "InviteStableMemberPage.body[0].children[0].children[0].children[0].children[3].children[0].children[1].children[0].children[0].children[0]",
                                                name: "AvarynHorseshoeIcon",
                                              ),
                                            ],
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_0dzqz0gi",
                                            type: "Text",
                                            path: "InviteStableMemberPage.body[0].children[0].children[0].children[0].children[3].children[0].children[1].children[0].children[1]",
                                            name: "Text",
                                            text: "Paarden",
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_7afa7csw",
                            type: "Container",
                            path: "InviteStableMemberPage.body[0].children[0].children[0].children[0].children[4]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_u85vlp3j",
                                type: "Row",
                                path: "InviteStableMemberPage.body[0].children[0].children[0].children[0].children[4].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_ryxlumw2",
                                    type: "Container",
                                    path: "InviteStableMemberPage.body[0].children[0].children[0].children[0].children[4].children[0].children[0]",
                                    name: "Container",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Button_ssuto74l",
                                    type: "Button",
                                    path: "InviteStableMemberPage.body[0].children[0].children[0].children[0].children[4].children[0].children[1]",
                                    name: "Button",
                                    text: "Planning",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_mst86er3",
                            type: "Container",
                            path: "InviteStableMemberPage.body[0].children[0].children[0].children[0].children[5]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_rkn15ggw",
                                type: "Row",
                                path: "InviteStableMemberPage.body[0].children[0].children[0].children[0].children[5].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_c44zsrcs",
                                    type: "Container",
                                    path: "InviteStableMemberPage.body[0].children[0].children[0].children[0].children[5].children[0].children[0]",
                                    name: "Container",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Button_6zowmedc",
                                    type: "Button",
                                    path: "InviteStableMemberPage.body[0].children[0].children[0].children[0].children[5].children[0].children[1]",
                                    name: "Button",
                                    text: "Wedstrijden",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_pjeon8mb",
                            type: "Container",
                            path: "InviteStableMemberPage.body[0].children[0].children[0].children[0].children[6]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_27cap9mg",
                                type: "Row",
                                path: "InviteStableMemberPage.body[0].children[0].children[0].children[0].children[6].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_obfm4bzm",
                                    type: "Container",
                                    path: "InviteStableMemberPage.body[0].children[0].children[0].children[0].children[6].children[0].children[0]",
                                    name: "Container",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Button_hsc4gstq",
                                    type: "Button",
                                    path: "InviteStableMemberPage.body[0].children[0].children[0].children[0].children[6].children[0].children[1]",
                                    name: "Button",
                                    text: "Profiel",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Spacer_tu6pjdjg",
                            type: "Spacer",
                            path: "InviteStableMemberPage.body[0].children[0].children[0].children[0].children[7]",
                            name: "FlexSpacer",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_042r4hyw",
                            type: "Container",
                            path: "InviteStableMemberPage.body[0].children[0].children[0].children[0].children[8]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_4hgql17l",
                                type: "Row",
                                path: "InviteStableMemberPage.body[0].children[0].children[0].children[0].children[8].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Icon_4h8at62i",
                                    type: "Icon",
                                    path: "InviteStableMemberPage.body[0].children[0].children[0].children[0].children[8].children[0].children[0]",
                                    name: "Icon",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_wps1wtpi",
                                    type: "Column",
                                    path: "InviteStableMemberPage.body[0].children[0].children[0].children[0].children[8].children[0].children[1]",
                                    name: "Column",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_4vw2goly",
                                        type: "Text",
                                        path: "InviteStableMemberPage.body[0].children[0].children[0].children[0].children[8].children[0].children[1].children[0]",
                                        name: "Text",
                                        text: "Local prototype",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_dcorrtbs",
                                        type: "Text",
                                        path: "InviteStableMemberPage.body[0].children[0].children[0].children[0].children[8].children[0].children[1].children[1]",
                                        name: "Text",
                                        text: "Sample data only",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Column_grdvurn1",
                type: "Column",
                path: "InviteStableMemberPage.body[0].children[1]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_ugx2t325",
                    type: "Container",
                    path: "InviteStableMemberPage.body[0].children[1].children[0]",
                    name: "Phase4BStableContextSelector",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_6cox4yxn",
                        type: "Container",
                        path: "InviteStableMemberPage.body[0].children[1].children[0].children[0]",
                        name: "Phase4BStableContextRuntime",
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_nc6gxqjz",
                    type: "Container",
                    path: "InviteStableMemberPage.body[0].children[1].children[1]",
                    name: "Phase4BinviteRuntime",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_9qqle456",
                    type: "Container",
                    path: "InviteStableMemberPage.body[0].children[1].children[2]",
                    name: "Phase4BMobileBottomNavigation",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_mctxjmk1",
                        type: "Container",
                        path: "InviteStableMemberPage.body[0].children[1].children[2].children[0]",
                        name: "AvarynMobileNavigationBody",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Row_fbgrtg0d",
                            type: "Row",
                            path: "InviteStableMemberPage.body[0].children[1].children[2].children[0].children[0]",
                            name: "Row",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Container_hhyk58lq",
                                type: "Container",
                                path: "InviteStableMemberPage.body[0].children[1].children[2].children[0].children[0].children[0]",
                                name: "Container",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_akqi94k6",
                                    type: "Column",
                                    path: "InviteStableMemberPage.body[0].children[1].children[2].children[0].children[0].children[0].children[0]",
                                    name: "Column",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_2qldq9e3",
                                        type: "Container",
                                        path: "InviteStableMemberPage.body[0].children[1].children[2].children[0].children[0].children[0].children[0].children[0]",
                                        name: "Container",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_6cgomzcb",
                                        type: "Icon",
                                        path: "InviteStableMemberPage.body[0].children[1].children[2].children[0].children[0].children[0].children[0].children[1]",
                                        name: "Icon",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_0ew0boyg",
                                        type: "Text",
                                        path: "InviteStableMemberPage.body[0].children[1].children[2].children[0].children[0].children[0].children[0].children[2]",
                                        name: "Text",
                                        text: "Vandaag",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Container_6eyqa3a7",
                                type: "Container",
                                path: "InviteStableMemberPage.body[0].children[1].children[2].children[0].children[0].children[1]",
                                name: "Container",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_ybtj5lm1",
                                    type: "Column",
                                    path: "InviteStableMemberPage.body[0].children[1].children[2].children[0].children[0].children[1].children[0]",
                                    name: "Column",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_umr6xu73",
                                        type: "Container",
                                        path: "InviteStableMemberPage.body[0].children[1].children[2].children[0].children[0].children[1].children[0].children[0]",
                                        name: "Container",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_iz6plu1x",
                                        type: "Container",
                                        path: "InviteStableMemberPage.body[0].children[1].children[2].children[0].children[0].children[1].children[0].children[1]",
                                        name: "Container",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_j9kfs3hl",
                                            type: "Container",
                                            path: "InviteStableMemberPage.body[0].children[1].children[2].children[0].children[0].children[1].children[0].children[1].children[0]",
                                            name: "AvarynHorseshoeIcon",
                                          ),
                                        ],
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_uf91ke2a",
                                        type: "Text",
                                        path: "InviteStableMemberPage.body[0].children[1].children[2].children[0].children[0].children[1].children[0].children[2]",
                                        name: "Text",
                                        text: "Paarden",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Container_ash2zlgn",
                                type: "Container",
                                path: "InviteStableMemberPage.body[0].children[1].children[2].children[0].children[0].children[2]",
                                name: "Container",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_w601lalr",
                                    type: "Column",
                                    path: "InviteStableMemberPage.body[0].children[1].children[2].children[0].children[0].children[2].children[0]",
                                    name: "Column",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_alb790vj",
                                        type: "Container",
                                        path: "InviteStableMemberPage.body[0].children[1].children[2].children[0].children[0].children[2].children[0].children[0]",
                                        name: "Container",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_x5kmshpy",
                                        type: "Icon",
                                        path: "InviteStableMemberPage.body[0].children[1].children[2].children[0].children[0].children[2].children[0].children[1]",
                                        name: "Icon",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_1xedqygv",
                                        type: "Text",
                                        path: "InviteStableMemberPage.body[0].children[1].children[2].children[0].children[0].children[2].children[0].children[2]",
                                        name: "Text",
                                        text: "Planning",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Container_z8hx07s0",
                                type: "Container",
                                path: "InviteStableMemberPage.body[0].children[1].children[2].children[0].children[0].children[3]",
                                name: "Container",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_2vf4hsb9",
                                    type: "Column",
                                    path: "InviteStableMemberPage.body[0].children[1].children[2].children[0].children[0].children[3].children[0]",
                                    name: "Column",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_owflrev4",
                                        type: "Container",
                                        path: "InviteStableMemberPage.body[0].children[1].children[2].children[0].children[0].children[3].children[0].children[0]",
                                        name: "Container",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_y1yhyp33",
                                        type: "Icon",
                                        path: "InviteStableMemberPage.body[0].children[1].children[2].children[0].children[0].children[3].children[0].children[1]",
                                        name: "Icon",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_11248f1l",
                                        type: "Text",
                                        path: "InviteStableMemberPage.body[0].children[1].children[2].children[0].children[0].children[3].children[0].children[2]",
                                        name: "Text",
                                        text: "Wedstrijden",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Container_bldhxj3i",
                                type: "Container",
                                path: "InviteStableMemberPage.body[0].children[1].children[2].children[0].children[0].children[4]",
                                name: "Container",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_k3mf67zl",
                                    type: "Column",
                                    path: "InviteStableMemberPage.body[0].children[1].children[2].children[0].children[0].children[4].children[0]",
                                    name: "Column",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_g7wmlm6c",
                                        type: "Container",
                                        path: "InviteStableMemberPage.body[0].children[1].children[2].children[0].children[0].children[4].children[0].children[0]",
                                        name: "Container",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_uvl1akxj",
                                        type: "Icon",
                                        path: "InviteStableMemberPage.body[0].children[1].children[2].children[0].children[0].children[4].children[0].children[1]",
                                        name: "Icon",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_pwy5j8oy",
                                        type: "Text",
                                        path: "InviteStableMemberPage.body[0].children[1].children[2].children[0].children[0].children[4].children[0].children[2]",
                                        name: "Text",
                                        text: "Profiel",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}
