// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final manageStableRolesPageHandle = ffai.ProjectPageHandle<ManageStableRolesPageParams, ManageStableRolesPageState>(
  name: "ManageStableRolesPage",
  key: "Scaffold_4migd6ef",
  route: "stal/rollen",
  params: const ManageStableRolesPageParams(),
  state: const ManageStableRolesPageState(),
  widgets: ManageStableRolesPageWidgets.tree,
);

final class ManageStableRolesPageParams {
  const ManageStableRolesPageParams();
}

final class ManageStableRolesPageState {
  const ManageStableRolesPageState();
}

abstract final class ManageStableRolesPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_4migd6ef",
      type: "Scaffold",
      path: "ManageStableRolesPage",
      name: "ManageStableRolesPage",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Row_zxhbzm6d",
            type: "Row",
            path: "ManageStableRolesPage.body[0]",
            name: "Phase4BResponsiveShell",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Container_phyg19oi",
                type: "Container",
                path: "ManageStableRolesPage.body[0].children[0]",
                name: "Phase4BDesktopSideNavigation",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_cr7azx3f",
                    type: "Container",
                    path: "ManageStableRolesPage.body[0].children[0].children[0]",
                    name: "AvarynDesktopNavigationBody",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_c8imz5cd",
                        type: "Column",
                        path: "ManageStableRolesPage.body[0].children[0].children[0].children[0]",
                        name: "Column",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_orbn54q9",
                            type: "Container",
                            path: "ManageStableRolesPage.body[0].children[0].children[0].children[0].children[0]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Column_x24rxi4d",
                                type: "Column",
                                path: "ManageStableRolesPage.body[0].children[0].children[0].children[0].children[0].children[0]",
                                name: "Column",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_207cxv04",
                                    type: "Text",
                                    path: "ManageStableRolesPage.body[0].children[0].children[0].children[0].children[0].children[0].children[0]",
                                    name: "Text",
                                    text: "AVARYN",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_w4ldu1ax",
                                    type: "Text",
                                    path: "ManageStableRolesPage.body[0].children[0].children[0].children[0].children[0].children[0].children[1]",
                                    name: "Text",
                                    text: "Performance",
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_r7rhh06i",
                            type: "Container",
                            path: "ManageStableRolesPage.body[0].children[0].children[0].children[0].children[1]",
                            name: "Container",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_bbpmmxxx",
                            type: "Container",
                            path: "ManageStableRolesPage.body[0].children[0].children[0].children[0].children[2]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_lcix88si",
                                type: "Row",
                                path: "ManageStableRolesPage.body[0].children[0].children[0].children[0].children[2].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_441t38s5",
                                    type: "Container",
                                    path: "ManageStableRolesPage.body[0].children[0].children[0].children[0].children[2].children[0].children[0]",
                                    name: "Container",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Button_7h9n1o1e",
                                    type: "Button",
                                    path: "ManageStableRolesPage.body[0].children[0].children[0].children[0].children[2].children[0].children[1]",
                                    name: "Button",
                                    text: "Vandaag",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_5kblvhmb",
                            type: "Container",
                            path: "ManageStableRolesPage.body[0].children[0].children[0].children[0].children[3]",
                            name: "Container",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_2xpodr8j",
                                type: "Row",
                                path: "ManageStableRolesPage.body[0].children[0].children[0].children[0].children[3].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_gmeujs1i",
                                    type: "Container",
                                    path: "ManageStableRolesPage.body[0].children[0].children[0].children[0].children[3].children[0].children[0]",
                                    name: "Container",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_reiydi24",
                                    type: "Container",
                                    path: "ManageStableRolesPage.body[0].children[0].children[0].children[0].children[3].children[0].children[1]",
                                    name: "Container",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Row_rk4rv377",
                                        type: "Row",
                                        path: "ManageStableRolesPage.body[0].children[0].children[0].children[0].children[3].children[0].children[1].children[0]",
                                        name: "Row",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_ob0vom91",
                                            type: "Container",
                                            path: "ManageStableRolesPage.body[0].children[0].children[0].children[0].children[3].children[0].children[1].children[0].children[0]",
                                            name: "Container",
                                            children: <ffai.ProjectWidgetHandle>[
                                              ffai.ProjectWidgetHandle(
                                                key: "Container_tyw0vblp",
                                                type: "Container",
                                                path: "ManageStableRolesPage.body[0].children[0].children[0].children[0].children[3].children[0].children[1].children[0].children[0].children[0]",
                                                name: "AvarynHorseshoeIcon",
                                              ),
                                            ],
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_m6y5uorm",
                                            type: "Text",
                                            path: "ManageStableRolesPage.body[0].children[0].children[0].children[0].children[3].children[0].children[1].children[0].children[1]",
                                            name: "Text",
                                            text: "Paarden",
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_imc8i0lb",
                            type: "Container",
                            path: "ManageStableRolesPage.body[0].children[0].children[0].children[0].children[4]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_5atiiurf",
                                type: "Row",
                                path: "ManageStableRolesPage.body[0].children[0].children[0].children[0].children[4].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_mjg2kr8n",
                                    type: "Container",
                                    path: "ManageStableRolesPage.body[0].children[0].children[0].children[0].children[4].children[0].children[0]",
                                    name: "Container",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Button_13kpu41c",
                                    type: "Button",
                                    path: "ManageStableRolesPage.body[0].children[0].children[0].children[0].children[4].children[0].children[1]",
                                    name: "Button",
                                    text: "Planning",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_yobcppsg",
                            type: "Container",
                            path: "ManageStableRolesPage.body[0].children[0].children[0].children[0].children[5]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_cwkgsnxc",
                                type: "Row",
                                path: "ManageStableRolesPage.body[0].children[0].children[0].children[0].children[5].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_ul89xxv2",
                                    type: "Container",
                                    path: "ManageStableRolesPage.body[0].children[0].children[0].children[0].children[5].children[0].children[0]",
                                    name: "Container",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Button_s3axbik5",
                                    type: "Button",
                                    path: "ManageStableRolesPage.body[0].children[0].children[0].children[0].children[5].children[0].children[1]",
                                    name: "Button",
                                    text: "Wedstrijden",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_ph7s995g",
                            type: "Container",
                            path: "ManageStableRolesPage.body[0].children[0].children[0].children[0].children[6]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_kvv1m52g",
                                type: "Row",
                                path: "ManageStableRolesPage.body[0].children[0].children[0].children[0].children[6].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_8z2lgtjp",
                                    type: "Container",
                                    path: "ManageStableRolesPage.body[0].children[0].children[0].children[0].children[6].children[0].children[0]",
                                    name: "Container",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Button_9oxkcf32",
                                    type: "Button",
                                    path: "ManageStableRolesPage.body[0].children[0].children[0].children[0].children[6].children[0].children[1]",
                                    name: "Button",
                                    text: "Profiel",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Spacer_gtknalp9",
                            type: "Spacer",
                            path: "ManageStableRolesPage.body[0].children[0].children[0].children[0].children[7]",
                            name: "FlexSpacer",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_xulvn9io",
                            type: "Container",
                            path: "ManageStableRolesPage.body[0].children[0].children[0].children[0].children[8]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_07bfw0w8",
                                type: "Row",
                                path: "ManageStableRolesPage.body[0].children[0].children[0].children[0].children[8].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Icon_dkmit43m",
                                    type: "Icon",
                                    path: "ManageStableRolesPage.body[0].children[0].children[0].children[0].children[8].children[0].children[0]",
                                    name: "Icon",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_xz4lafxa",
                                    type: "Column",
                                    path: "ManageStableRolesPage.body[0].children[0].children[0].children[0].children[8].children[0].children[1]",
                                    name: "Column",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_fxblw5bk",
                                        type: "Text",
                                        path: "ManageStableRolesPage.body[0].children[0].children[0].children[0].children[8].children[0].children[1].children[0]",
                                        name: "Text",
                                        text: "Local prototype",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_lycbfi79",
                                        type: "Text",
                                        path: "ManageStableRolesPage.body[0].children[0].children[0].children[0].children[8].children[0].children[1].children[1]",
                                        name: "Text",
                                        text: "Sample data only",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Column_qw9eso3k",
                type: "Column",
                path: "ManageStableRolesPage.body[0].children[1]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_6awbxf91",
                    type: "Container",
                    path: "ManageStableRolesPage.body[0].children[1].children[0]",
                    name: "Phase4BStableContextSelector",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_zm8x3p1h",
                        type: "Container",
                        path: "ManageStableRolesPage.body[0].children[1].children[0].children[0]",
                        name: "Phase4BStableContextRuntime",
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_tkz8pat6",
                    type: "Container",
                    path: "ManageStableRolesPage.body[0].children[1].children[1]",
                    name: "Phase4BrolesRuntime",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_palv5eg7",
                    type: "Container",
                    path: "ManageStableRolesPage.body[0].children[1].children[2]",
                    name: "Phase4BMobileBottomNavigation",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_n9ryp5vd",
                        type: "Container",
                        path: "ManageStableRolesPage.body[0].children[1].children[2].children[0]",
                        name: "AvarynMobileNavigationBody",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Row_wlyoax1x",
                            type: "Row",
                            path: "ManageStableRolesPage.body[0].children[1].children[2].children[0].children[0]",
                            name: "Row",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Container_zdg41exq",
                                type: "Container",
                                path: "ManageStableRolesPage.body[0].children[1].children[2].children[0].children[0].children[0]",
                                name: "Container",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_1rkwm8lt",
                                    type: "Column",
                                    path: "ManageStableRolesPage.body[0].children[1].children[2].children[0].children[0].children[0].children[0]",
                                    name: "Column",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_tdcyzq96",
                                        type: "Container",
                                        path: "ManageStableRolesPage.body[0].children[1].children[2].children[0].children[0].children[0].children[0].children[0]",
                                        name: "Container",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_c8sjasq3",
                                        type: "Icon",
                                        path: "ManageStableRolesPage.body[0].children[1].children[2].children[0].children[0].children[0].children[0].children[1]",
                                        name: "Icon",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_quave9l5",
                                        type: "Text",
                                        path: "ManageStableRolesPage.body[0].children[1].children[2].children[0].children[0].children[0].children[0].children[2]",
                                        name: "Text",
                                        text: "Vandaag",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Container_9igjm2j9",
                                type: "Container",
                                path: "ManageStableRolesPage.body[0].children[1].children[2].children[0].children[0].children[1]",
                                name: "Container",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_uldy6h9z",
                                    type: "Column",
                                    path: "ManageStableRolesPage.body[0].children[1].children[2].children[0].children[0].children[1].children[0]",
                                    name: "Column",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_m7j2oyhg",
                                        type: "Container",
                                        path: "ManageStableRolesPage.body[0].children[1].children[2].children[0].children[0].children[1].children[0].children[0]",
                                        name: "Container",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_4a2tcxa2",
                                        type: "Container",
                                        path: "ManageStableRolesPage.body[0].children[1].children[2].children[0].children[0].children[1].children[0].children[1]",
                                        name: "Container",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_gljuh2ct",
                                            type: "Container",
                                            path: "ManageStableRolesPage.body[0].children[1].children[2].children[0].children[0].children[1].children[0].children[1].children[0]",
                                            name: "AvarynHorseshoeIcon",
                                          ),
                                        ],
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_r9c55gm1",
                                        type: "Text",
                                        path: "ManageStableRolesPage.body[0].children[1].children[2].children[0].children[0].children[1].children[0].children[2]",
                                        name: "Text",
                                        text: "Paarden",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Container_usyuar4n",
                                type: "Container",
                                path: "ManageStableRolesPage.body[0].children[1].children[2].children[0].children[0].children[2]",
                                name: "Container",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_e8v52vki",
                                    type: "Column",
                                    path: "ManageStableRolesPage.body[0].children[1].children[2].children[0].children[0].children[2].children[0]",
                                    name: "Column",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_22azetwc",
                                        type: "Container",
                                        path: "ManageStableRolesPage.body[0].children[1].children[2].children[0].children[0].children[2].children[0].children[0]",
                                        name: "Container",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_bsh25jpy",
                                        type: "Icon",
                                        path: "ManageStableRolesPage.body[0].children[1].children[2].children[0].children[0].children[2].children[0].children[1]",
                                        name: "Icon",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_btciyhth",
                                        type: "Text",
                                        path: "ManageStableRolesPage.body[0].children[1].children[2].children[0].children[0].children[2].children[0].children[2]",
                                        name: "Text",
                                        text: "Planning",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Container_04ad4p3z",
                                type: "Container",
                                path: "ManageStableRolesPage.body[0].children[1].children[2].children[0].children[0].children[3]",
                                name: "Container",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_8iqv14g7",
                                    type: "Column",
                                    path: "ManageStableRolesPage.body[0].children[1].children[2].children[0].children[0].children[3].children[0]",
                                    name: "Column",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_qeqc5khs",
                                        type: "Container",
                                        path: "ManageStableRolesPage.body[0].children[1].children[2].children[0].children[0].children[3].children[0].children[0]",
                                        name: "Container",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_xktjhnrq",
                                        type: "Icon",
                                        path: "ManageStableRolesPage.body[0].children[1].children[2].children[0].children[0].children[3].children[0].children[1]",
                                        name: "Icon",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_zfknv214",
                                        type: "Text",
                                        path: "ManageStableRolesPage.body[0].children[1].children[2].children[0].children[0].children[3].children[0].children[2]",
                                        name: "Text",
                                        text: "Wedstrijden",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Container_4ycm1a16",
                                type: "Container",
                                path: "ManageStableRolesPage.body[0].children[1].children[2].children[0].children[0].children[4]",
                                name: "Container",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_kjv6zb4s",
                                    type: "Column",
                                    path: "ManageStableRolesPage.body[0].children[1].children[2].children[0].children[0].children[4].children[0]",
                                    name: "Column",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_2h7mq4ll",
                                        type: "Container",
                                        path: "ManageStableRolesPage.body[0].children[1].children[2].children[0].children[0].children[4].children[0].children[0]",
                                        name: "Container",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_kvm5qg0z",
                                        type: "Icon",
                                        path: "ManageStableRolesPage.body[0].children[1].children[2].children[0].children[0].children[4].children[0].children[1]",
                                        name: "Icon",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_bltd279e",
                                        type: "Text",
                                        path: "ManageStableRolesPage.body[0].children[1].children[2].children[0].children[0].children[4].children[0].children[2]",
                                        name: "Text",
                                        text: "Profiel",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}
