// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final personalWorkspacePageHandle = ffai.ProjectPageHandle<
  PersonalWorkspacePageParams,
  PersonalWorkspacePageState
>(
  name: "PersonalWorkspacePage",
  key: "Scaffold_jqda0spy",
  route: "persoonlijke-workspace",
  params: const PersonalWorkspacePageParams(),
  state: const PersonalWorkspacePageState(),
  widgets: PersonalWorkspacePageWidgets.tree,
);

final class PersonalWorkspacePageParams {
  const PersonalWorkspacePageParams();
}

final class PersonalWorkspacePageState {
  const PersonalWorkspacePageState();
}

abstract final class PersonalWorkspacePageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_jqda0spy",
      type: "Scaffold",
      path: "PersonalWorkspacePage",
      name: "PersonalWorkspacePage",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Row_osxmkolv",
            type: "Row",
            path: "PersonalWorkspacePage.body[0]",
            name: "Phase4BResponsiveShell",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Container_50ida7l7",
                type: "Container",
                path: "PersonalWorkspacePage.body[0].children[0]",
                name: "Phase4BDesktopSideNavigation",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_6nvbv7wx",
                    type: "Container",
                    path:
                        "PersonalWorkspacePage.body[0].children[0].children[0]",
                    name: "AvarynDesktopNavigationBody",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_gdjf9c40",
                        type: "Column",
                        path:
                            "PersonalWorkspacePage.body[0].children[0].children[0].children[0]",
                        name: "Column",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_6vowx5x3",
                            type: "Container",
                            path:
                                "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[0]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Column_mqr4ikcs",
                                type: "Column",
                                path:
                                    "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[0].children[0]",
                                name: "Column",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_hxulyrra",
                                    type: "Text",
                                    path:
                                        "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[0].children[0].children[0]",
                                    name: "Text",
                                    text: "AVARYN",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_qu31z1vi",
                                    type: "Text",
                                    path:
                                        "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[0].children[0].children[1]",
                                    name: "Text",
                                    text: "Performance",
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_3rw8eec8",
                            type: "Container",
                            path:
                                "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[1]",
                            name: "Container",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_dwgsss5t",
                            type: "Container",
                            path:
                                "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[2]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_xlfqukrx",
                                type: "Row",
                                path:
                                    "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[2].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_r06kwpz0",
                                    type: "Container",
                                    path:
                                        "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[2].children[0].children[0]",
                                    name: "Container",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Button_dfj42qwy",
                                    type: "Button",
                                    path:
                                        "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[2].children[0].children[1]",
                                    name: "Button",
                                    text: "Vandaag",
                                    triggers: const <String>["ON_TAP"],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_vbncoe72",
                            type: "Container",
                            path:
                                "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[3]",
                            name: "Container",
                            triggers: const <String>["ON_TAP"],
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_jv3gqy8k",
                                type: "Row",
                                path:
                                    "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[3].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_xucnmi5h",
                                    type: "Container",
                                    path:
                                        "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[3].children[0].children[0]",
                                    name: "Container",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_md4ymm1p",
                                    type: "Container",
                                    path:
                                        "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[3].children[0].children[1]",
                                    name: "Container",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Row_ml9kvv64",
                                        type: "Row",
                                        path:
                                            "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[3].children[0].children[1].children[0]",
                                        name: "Row",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_gbsv312o",
                                            type: "Container",
                                            path:
                                                "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[3].children[0].children[1].children[0].children[0]",
                                            name: "Container",
                                            children: <
                                              ffai.ProjectWidgetHandle
                                            >[
                                              ffai.ProjectWidgetHandle(
                                                key: "Container_af8y7891",
                                                type: "Container",
                                                path:
                                                    "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[3].children[0].children[1].children[0].children[0].children[0]",
                                                name: "AvarynHorseshoeIcon",
                                              ),
                                            ],
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_01jl2tdb",
                                            type: "Text",
                                            path:
                                                "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[3].children[0].children[1].children[0].children[1]",
                                            name: "Text",
                                            text: "Paarden",
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_dqkse1pt",
                            type: "Container",
                            path:
                                "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[4]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_awyjpaet",
                                type: "Row",
                                path:
                                    "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[4].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_hsmbftc5",
                                    type: "Container",
                                    path:
                                        "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[4].children[0].children[0]",
                                    name: "Container",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Button_64lw5u4g",
                                    type: "Button",
                                    path:
                                        "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[4].children[0].children[1]",
                                    name: "Button",
                                    text: "Planning",
                                    triggers: const <String>["ON_TAP"],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_yl1212sx",
                            type: "Container",
                            path:
                                "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[5]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_cp6n8fiv",
                                type: "Row",
                                path:
                                    "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[5].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_zsvwh0cb",
                                    type: "Container",
                                    path:
                                        "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[5].children[0].children[0]",
                                    name: "Container",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Button_gt4t5cne",
                                    type: "Button",
                                    path:
                                        "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[5].children[0].children[1]",
                                    name: "Button",
                                    text: "Profiel",
                                    triggers: const <String>["ON_TAP"],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Spacer_f1uuspab",
                            type: "Spacer",
                            path:
                                "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[6]",
                            name: "FlexSpacer",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_13fx8epz",
                            type: "Container",
                            path:
                                "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[7]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_y4bmwpus",
                                type: "Row",
                                path:
                                    "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[7].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Icon_tiz1th04",
                                    type: "Icon",
                                    path:
                                        "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[7].children[0].children[0]",
                                    name: "Icon",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_3y91qiz6",
                                    type: "Column",
                                    path:
                                        "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[7].children[0].children[1]",
                                    name: "Column",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_y8hqnmuq",
                                        type: "Text",
                                        path:
                                            "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[7].children[0].children[1].children[0]",
                                        name: "Text",
                                        text: "Besloten Alpha",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_mcmbjnw9",
                                        type: "Text",
                                        path:
                                            "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[7].children[0].children[1].children[1]",
                                        name: "Text",
                                        text: "Geen productie",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Column_ije4x1jg",
                type: "Column",
                path: "PersonalWorkspacePage.body[0].children[1]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_dv3worso",
                    type: "Container",
                    path:
                        "PersonalWorkspacePage.body[0].children[1].children[0]",
                    name: "Phase4BStableContextSelector",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_2ou4hde5",
                        type: "Container",
                        path:
                            "PersonalWorkspacePage.body[0].children[1].children[0].children[0]",
                        name: "Phase4BStableContextRuntime",
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_dcgtrgp9",
                    type: "Container",
                    path:
                        "PersonalWorkspacePage.body[0].children[1].children[1]",
                    name: "Phase4BpersonalWorkspaceRuntime",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_pusqipgd",
                    type: "Container",
                    path:
                        "PersonalWorkspacePage.body[0].children[1].children[2]",
                    name: "Phase4BMobileBottomNavigation",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_179hvqo8",
                        type: "Container",
                        path:
                            "PersonalWorkspacePage.body[0].children[1].children[2].children[0]",
                        name: "AvarynMobileNavigationBody",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Row_sbi3kg0w",
                            type: "Row",
                            path:
                                "PersonalWorkspacePage.body[0].children[1].children[2].children[0].children[0]",
                            name: "Row",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Container_epyu51yh",
                                type: "Container",
                                path:
                                    "PersonalWorkspacePage.body[0].children[1].children[2].children[0].children[0].children[0]",
                                name: "Container",
                                triggers: const <String>["ON_TAP"],
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_aqiur7h6",
                                    type: "Column",
                                    path:
                                        "PersonalWorkspacePage.body[0].children[1].children[2].children[0].children[0].children[0].children[0]",
                                    name: "Column",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_58evee9j",
                                        type: "Container",
                                        path:
                                            "PersonalWorkspacePage.body[0].children[1].children[2].children[0].children[0].children[0].children[0].children[0]",
                                        name: "Container",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_xw57s3yn",
                                        type: "Icon",
                                        path:
                                            "PersonalWorkspacePage.body[0].children[1].children[2].children[0].children[0].children[0].children[0].children[1]",
                                        name: "Icon",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_dwlfmm6x",
                                        type: "Text",
                                        path:
                                            "PersonalWorkspacePage.body[0].children[1].children[2].children[0].children[0].children[0].children[0].children[2]",
                                        name: "Text",
                                        text: "Vandaag",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Container_eyic6uwr",
                                type: "Container",
                                path:
                                    "PersonalWorkspacePage.body[0].children[1].children[2].children[0].children[0].children[1]",
                                name: "Container",
                                triggers: const <String>["ON_TAP"],
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_goqt2hd1",
                                    type: "Column",
                                    path:
                                        "PersonalWorkspacePage.body[0].children[1].children[2].children[0].children[0].children[1].children[0]",
                                    name: "Column",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_hufmdzrq",
                                        type: "Container",
                                        path:
                                            "PersonalWorkspacePage.body[0].children[1].children[2].children[0].children[0].children[1].children[0].children[0]",
                                        name: "Container",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_ji3zatqx",
                                        type: "Container",
                                        path:
                                            "PersonalWorkspacePage.body[0].children[1].children[2].children[0].children[0].children[1].children[0].children[1]",
                                        name: "Container",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_zcdhslno",
                                            type: "Container",
                                            path:
                                                "PersonalWorkspacePage.body[0].children[1].children[2].children[0].children[0].children[1].children[0].children[1].children[0]",
                                            name: "AvarynHorseshoeIcon",
                                          ),
                                        ],
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_9lgqoeo1",
                                        type: "Text",
                                        path:
                                            "PersonalWorkspacePage.body[0].children[1].children[2].children[0].children[0].children[1].children[0].children[2]",
                                        name: "Text",
                                        text: "Paarden",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Container_ufbawa79",
                                type: "Container",
                                path:
                                    "PersonalWorkspacePage.body[0].children[1].children[2].children[0].children[0].children[2]",
                                name: "Container",
                                triggers: const <String>["ON_TAP"],
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_2wi37y7g",
                                    type: "Column",
                                    path:
                                        "PersonalWorkspacePage.body[0].children[1].children[2].children[0].children[0].children[2].children[0]",
                                    name: "Column",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_hb3oolf8",
                                        type: "Container",
                                        path:
                                            "PersonalWorkspacePage.body[0].children[1].children[2].children[0].children[0].children[2].children[0].children[0]",
                                        name: "Container",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_vcoyqksv",
                                        type: "Icon",
                                        path:
                                            "PersonalWorkspacePage.body[0].children[1].children[2].children[0].children[0].children[2].children[0].children[1]",
                                        name: "Icon",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_6mipw0ib",
                                        type: "Text",
                                        path:
                                            "PersonalWorkspacePage.body[0].children[1].children[2].children[0].children[0].children[2].children[0].children[2]",
                                        name: "Text",
                                        text: "Planning",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Container_vmfrkxjq",
                                type: "Container",
                                path:
                                    "PersonalWorkspacePage.body[0].children[1].children[2].children[0].children[0].children[3]",
                                name: "Container",
                                triggers: const <String>["ON_TAP"],
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_eccwjnhx",
                                    type: "Column",
                                    path:
                                        "PersonalWorkspacePage.body[0].children[1].children[2].children[0].children[0].children[3].children[0]",
                                    name: "Column",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_me9o32hk",
                                        type: "Container",
                                        path:
                                            "PersonalWorkspacePage.body[0].children[1].children[2].children[0].children[0].children[3].children[0].children[0]",
                                        name: "Container",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_4cniyydj",
                                        type: "Icon",
                                        path:
                                            "PersonalWorkspacePage.body[0].children[1].children[2].children[0].children[0].children[3].children[0].children[1]",
                                        name: "Icon",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_f6zmaolt",
                                        type: "Text",
                                        path:
                                            "PersonalWorkspacePage.body[0].children[1].children[2].children[0].children[0].children[3].children[0].children[2]",
                                        name: "Text",
                                        text: "Profiel",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}
