// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final personalProfilePageHandle =
    ffai.ProjectPageHandle<PersonalProfilePageParams, PersonalProfilePageState>(
      name: "PersonalProfilePage",
      key: "Scaffold_b0gkhy06",
      route: "profiel",
      params: const PersonalProfilePageParams(),
      state: const PersonalProfilePageState(),
      widgets: PersonalProfilePageWidgets.tree,
    );

final class PersonalProfilePageParams {
  const PersonalProfilePageParams();
}

final class PersonalProfilePageState {
  const PersonalProfilePageState();
}

abstract final class PersonalProfilePageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_b0gkhy06",
      type: "Scaffold",
      path: "PersonalProfilePage",
      name: "PersonalProfilePage",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Row_8q20m6o8",
            type: "Row",
            path: "PersonalProfilePage.body[0]",
            name: "PersonalProfileResponsiveShell",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Container_lxir6wgg",
                type: "Container",
                path: "PersonalProfilePage.body[0].children[0]",
                name: "PersonalProfileDesktopSideNavigation",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_n9kepct8",
                    type: "Container",
                    path: "PersonalProfilePage.body[0].children[0].children[0]",
                    name: "AvarynDesktopNavigationBody",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_9t10u8f2",
                        type: "Column",
                        path:
                            "PersonalProfilePage.body[0].children[0].children[0].children[0]",
                        name: "Column",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_wh5sr4ec",
                            type: "Container",
                            path:
                                "PersonalProfilePage.body[0].children[0].children[0].children[0].children[0]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Column_urzd6t81",
                                type: "Column",
                                path:
                                    "PersonalProfilePage.body[0].children[0].children[0].children[0].children[0].children[0]",
                                name: "Column",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_qzdmu996",
                                    type: "Text",
                                    path:
                                        "PersonalProfilePage.body[0].children[0].children[0].children[0].children[0].children[0].children[0]",
                                    name: "Text",
                                    text: "AVARYN",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_t1ye3kol",
                                    type: "Text",
                                    path:
                                        "PersonalProfilePage.body[0].children[0].children[0].children[0].children[0].children[0].children[1]",
                                    name: "Text",
                                    text: "Performance",
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_8rnldjo0",
                            type: "Container",
                            path:
                                "PersonalProfilePage.body[0].children[0].children[0].children[0].children[1]",
                            name: "Container",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_kae8esd0",
                            type: "Container",
                            path:
                                "PersonalProfilePage.body[0].children[0].children[0].children[0].children[2]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_wmj1ykfa",
                                type: "Row",
                                path:
                                    "PersonalProfilePage.body[0].children[0].children[0].children[0].children[2].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_3hkfvpuy",
                                    type: "Container",
                                    path:
                                        "PersonalProfilePage.body[0].children[0].children[0].children[0].children[2].children[0].children[0]",
                                    name: "Container",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Button_81y26fgp",
                                    type: "Button",
                                    path:
                                        "PersonalProfilePage.body[0].children[0].children[0].children[0].children[2].children[0].children[1]",
                                    name: "Button",
                                    text: "Vandaag",
                                    triggers: const <String>["ON_TAP"],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_wi7r3oac",
                            type: "Container",
                            path:
                                "PersonalProfilePage.body[0].children[0].children[0].children[0].children[3]",
                            name: "Container",
                            triggers: const <String>["ON_TAP"],
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_i3j56i9y",
                                type: "Row",
                                path:
                                    "PersonalProfilePage.body[0].children[0].children[0].children[0].children[3].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_imcvpsaf",
                                    type: "Container",
                                    path:
                                        "PersonalProfilePage.body[0].children[0].children[0].children[0].children[3].children[0].children[0]",
                                    name: "Container",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_1r3ch2hd",
                                    type: "Container",
                                    path:
                                        "PersonalProfilePage.body[0].children[0].children[0].children[0].children[3].children[0].children[1]",
                                    name: "Container",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Row_n8yhkjg0",
                                        type: "Row",
                                        path:
                                            "PersonalProfilePage.body[0].children[0].children[0].children[0].children[3].children[0].children[1].children[0]",
                                        name: "Row",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_6g0wctjq",
                                            type: "Container",
                                            path:
                                                "PersonalProfilePage.body[0].children[0].children[0].children[0].children[3].children[0].children[1].children[0].children[0]",
                                            name: "Container",
                                            children: <
                                              ffai.ProjectWidgetHandle
                                            >[
                                              ffai.ProjectWidgetHandle(
                                                key: "Container_rwlzfh82",
                                                type: "Container",
                                                path:
                                                    "PersonalProfilePage.body[0].children[0].children[0].children[0].children[3].children[0].children[1].children[0].children[0].children[0]",
                                                name: "AvarynHorseshoeIcon",
                                              ),
                                            ],
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_x317aj8o",
                                            type: "Text",
                                            path:
                                                "PersonalProfilePage.body[0].children[0].children[0].children[0].children[3].children[0].children[1].children[0].children[1]",
                                            name: "Text",
                                            text: "Paarden",
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_ijedqb13",
                            type: "Container",
                            path:
                                "PersonalProfilePage.body[0].children[0].children[0].children[0].children[4]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_rwzghnl0",
                                type: "Row",
                                path:
                                    "PersonalProfilePage.body[0].children[0].children[0].children[0].children[4].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_8u6n23wu",
                                    type: "Container",
                                    path:
                                        "PersonalProfilePage.body[0].children[0].children[0].children[0].children[4].children[0].children[0]",
                                    name: "Container",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Button_49nzqd4m",
                                    type: "Button",
                                    path:
                                        "PersonalProfilePage.body[0].children[0].children[0].children[0].children[4].children[0].children[1]",
                                    name: "Button",
                                    text: "Planning",
                                    triggers: const <String>["ON_TAP"],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_hj8bj6ie",
                            type: "Container",
                            path:
                                "PersonalProfilePage.body[0].children[0].children[0].children[0].children[5]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_6uajb1iy",
                                type: "Row",
                                path:
                                    "PersonalProfilePage.body[0].children[0].children[0].children[0].children[5].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_5ey343sj",
                                    type: "Container",
                                    path:
                                        "PersonalProfilePage.body[0].children[0].children[0].children[0].children[5].children[0].children[0]",
                                    name: "Container",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Button_uk6w8tml",
                                    type: "Button",
                                    path:
                                        "PersonalProfilePage.body[0].children[0].children[0].children[0].children[5].children[0].children[1]",
                                    name: "Button",
                                    text: "Profiel",
                                    triggers: const <String>["ON_TAP"],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Spacer_ax8q4p16",
                            type: "Spacer",
                            path:
                                "PersonalProfilePage.body[0].children[0].children[0].children[0].children[6]",
                            name: "FlexSpacer",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_rqr5c65b",
                            type: "Container",
                            path:
                                "PersonalProfilePage.body[0].children[0].children[0].children[0].children[7]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_qv0p24da",
                                type: "Row",
                                path:
                                    "PersonalProfilePage.body[0].children[0].children[0].children[0].children[7].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Icon_t5r7g70w",
                                    type: "Icon",
                                    path:
                                        "PersonalProfilePage.body[0].children[0].children[0].children[0].children[7].children[0].children[0]",
                                    name: "Icon",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_naznldn6",
                                    type: "Column",
                                    path:
                                        "PersonalProfilePage.body[0].children[0].children[0].children[0].children[7].children[0].children[1]",
                                    name: "Column",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_9cmfo1s8",
                                        type: "Text",
                                        path:
                                            "PersonalProfilePage.body[0].children[0].children[0].children[0].children[7].children[0].children[1].children[0]",
                                        name: "Text",
                                        text: "Besloten Alpha",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_658w7p2u",
                                        type: "Text",
                                        path:
                                            "PersonalProfilePage.body[0].children[0].children[0].children[0].children[7].children[0].children[1].children[1]",
                                        name: "Text",
                                        text: "Geen productie",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Column_xi6dw6fn",
                type: "Column",
                path: "PersonalProfilePage.body[0].children[1]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_eow2dcnp",
                    type: "Container",
                    path: "PersonalProfilePage.body[0].children[1].children[0]",
                    name: "PersonalProfileRuntime",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_zbgwnofo",
                    type: "Container",
                    path: "PersonalProfilePage.body[0].children[1].children[1]",
                    name: "PersonalProfileMobileBottomNavigation",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_h68rs3rb",
                        type: "Container",
                        path:
                            "PersonalProfilePage.body[0].children[1].children[1].children[0]",
                        name: "AvarynMobileNavigationBody",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Row_mvmv8tcv",
                            type: "Row",
                            path:
                                "PersonalProfilePage.body[0].children[1].children[1].children[0].children[0]",
                            name: "Row",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Container_0k77j6gd",
                                type: "Container",
                                path:
                                    "PersonalProfilePage.body[0].children[1].children[1].children[0].children[0].children[0]",
                                name: "Container",
                                triggers: const <String>["ON_TAP"],
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_n2n4evob",
                                    type: "Column",
                                    path:
                                        "PersonalProfilePage.body[0].children[1].children[1].children[0].children[0].children[0].children[0]",
                                    name: "Column",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_8yil3q1z",
                                        type: "Container",
                                        path:
                                            "PersonalProfilePage.body[0].children[1].children[1].children[0].children[0].children[0].children[0].children[0]",
                                        name: "Container",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_0e726u79",
                                        type: "Icon",
                                        path:
                                            "PersonalProfilePage.body[0].children[1].children[1].children[0].children[0].children[0].children[0].children[1]",
                                        name: "Icon",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_cfbfzm4o",
                                        type: "Text",
                                        path:
                                            "PersonalProfilePage.body[0].children[1].children[1].children[0].children[0].children[0].children[0].children[2]",
                                        name: "Text",
                                        text: "Vandaag",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Container_lh2np18q",
                                type: "Container",
                                path:
                                    "PersonalProfilePage.body[0].children[1].children[1].children[0].children[0].children[1]",
                                name: "Container",
                                triggers: const <String>["ON_TAP"],
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_z0vfhibe",
                                    type: "Column",
                                    path:
                                        "PersonalProfilePage.body[0].children[1].children[1].children[0].children[0].children[1].children[0]",
                                    name: "Column",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_ggxerb05",
                                        type: "Container",
                                        path:
                                            "PersonalProfilePage.body[0].children[1].children[1].children[0].children[0].children[1].children[0].children[0]",
                                        name: "Container",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_1d59gt0l",
                                        type: "Container",
                                        path:
                                            "PersonalProfilePage.body[0].children[1].children[1].children[0].children[0].children[1].children[0].children[1]",
                                        name: "Container",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_jdmaf4v8",
                                            type: "Container",
                                            path:
                                                "PersonalProfilePage.body[0].children[1].children[1].children[0].children[0].children[1].children[0].children[1].children[0]",
                                            name: "AvarynHorseshoeIcon",
                                          ),
                                        ],
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_c1um3st5",
                                        type: "Text",
                                        path:
                                            "PersonalProfilePage.body[0].children[1].children[1].children[0].children[0].children[1].children[0].children[2]",
                                        name: "Text",
                                        text: "Paarden",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Container_izzpy2pz",
                                type: "Container",
                                path:
                                    "PersonalProfilePage.body[0].children[1].children[1].children[0].children[0].children[2]",
                                name: "Container",
                                triggers: const <String>["ON_TAP"],
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_b3hvop4h",
                                    type: "Column",
                                    path:
                                        "PersonalProfilePage.body[0].children[1].children[1].children[0].children[0].children[2].children[0]",
                                    name: "Column",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_l1qihg65",
                                        type: "Container",
                                        path:
                                            "PersonalProfilePage.body[0].children[1].children[1].children[0].children[0].children[2].children[0].children[0]",
                                        name: "Container",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_rtwoatvu",
                                        type: "Icon",
                                        path:
                                            "PersonalProfilePage.body[0].children[1].children[1].children[0].children[0].children[2].children[0].children[1]",
                                        name: "Icon",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_oiaa4xje",
                                        type: "Text",
                                        path:
                                            "PersonalProfilePage.body[0].children[1].children[1].children[0].children[0].children[2].children[0].children[2]",
                                        name: "Text",
                                        text: "Planning",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Container_av69sm2q",
                                type: "Container",
                                path:
                                    "PersonalProfilePage.body[0].children[1].children[1].children[0].children[0].children[3]",
                                name: "Container",
                                triggers: const <String>["ON_TAP"],
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_0kmpqrby",
                                    type: "Column",
                                    path:
                                        "PersonalProfilePage.body[0].children[1].children[1].children[0].children[0].children[3].children[0]",
                                    name: "Column",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_4yxssgu8",
                                        type: "Container",
                                        path:
                                            "PersonalProfilePage.body[0].children[1].children[1].children[0].children[0].children[3].children[0].children[0]",
                                        name: "Container",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_gvlqb0eg",
                                        type: "Icon",
                                        path:
                                            "PersonalProfilePage.body[0].children[1].children[1].children[0].children[0].children[3].children[0].children[1]",
                                        name: "Icon",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_2uybab1k",
                                        type: "Text",
                                        path:
                                            "PersonalProfilePage.body[0].children[1].children[1].children[0].children[0].children[3].children[0].children[2]",
                                        name: "Text",
                                        text: "Profiel",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}
