// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final personalWorkspacePageHandle = ffai.ProjectPageHandle<PersonalWorkspacePageParams, PersonalWorkspacePageState>(
  name: "PersonalWorkspacePage",
  key: "Scaffold_jqda0spy",
  route: "persoonlijke-workspace",
  params: const PersonalWorkspacePageParams(),
  state: const PersonalWorkspacePageState(),
  widgets: PersonalWorkspacePageWidgets.tree,
);

final class PersonalWorkspacePageParams {
  const PersonalWorkspacePageParams();
}

final class PersonalWorkspacePageState {
  const PersonalWorkspacePageState();
}

abstract final class PersonalWorkspacePageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_jqda0spy",
      type: "Scaffold",
      path: "PersonalWorkspacePage",
      name: "PersonalWorkspacePage",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Row_wuwnwhaw",
            type: "Row",
            path: "PersonalWorkspacePage.body[0]",
            name: "Phase4BResponsiveShell",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Container_6fcjc6yj",
                type: "Container",
                path: "PersonalWorkspacePage.body[0].children[0]",
                name: "Phase4BDesktopSideNavigation",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_py63cirx",
                    type: "Container",
                    path: "PersonalWorkspacePage.body[0].children[0].children[0]",
                    name: "AvarynDesktopNavigationBody",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_0htzuqp4",
                        type: "Column",
                        path: "PersonalWorkspacePage.body[0].children[0].children[0].children[0]",
                        name: "Column",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_w12dpbtb",
                            type: "Container",
                            path: "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[0]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Column_sre49d4e",
                                type: "Column",
                                path: "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[0].children[0]",
                                name: "Column",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_9ccuh9nx",
                                    type: "Text",
                                    path: "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[0].children[0].children[0]",
                                    name: "Text",
                                    text: "AVARYN",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_3gusbg1o",
                                    type: "Text",
                                    path: "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[0].children[0].children[1]",
                                    name: "Text",
                                    text: "Performance",
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_31hc08uu",
                            type: "Container",
                            path: "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[1]",
                            name: "Container",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_8fc8t2fb",
                            type: "Container",
                            path: "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[2]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_3jciuvdv",
                                type: "Row",
                                path: "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[2].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_j2p6cnah",
                                    type: "Container",
                                    path: "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[2].children[0].children[0]",
                                    name: "Container",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Button_hvqm706z",
                                    type: "Button",
                                    path: "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[2].children[0].children[1]",
                                    name: "Button",
                                    text: "Vandaag",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_yicjewqi",
                            type: "Container",
                            path: "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[3]",
                            name: "Container",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_259dbyfn",
                                type: "Row",
                                path: "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[3].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_x9xoedl2",
                                    type: "Container",
                                    path: "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[3].children[0].children[0]",
                                    name: "Container",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_zaqw7sm3",
                                    type: "Container",
                                    path: "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[3].children[0].children[1]",
                                    name: "Container",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Row_5u5o78pv",
                                        type: "Row",
                                        path: "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[3].children[0].children[1].children[0]",
                                        name: "Row",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_vsgonjx3",
                                            type: "Container",
                                            path: "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[3].children[0].children[1].children[0].children[0]",
                                            name: "Container",
                                            children: <ffai.ProjectWidgetHandle>[
                                              ffai.ProjectWidgetHandle(
                                                key: "Container_rjhqltpb",
                                                type: "Container",
                                                path: "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[3].children[0].children[1].children[0].children[0].children[0]",
                                                name: "AvarynHorseshoeIcon",
                                              ),
                                            ],
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_lm5l6tdk",
                                            type: "Text",
                                            path: "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[3].children[0].children[1].children[0].children[1]",
                                            name: "Text",
                                            text: "Paarden",
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_tapjbka4",
                            type: "Container",
                            path: "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[4]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_52dalnmd",
                                type: "Row",
                                path: "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[4].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_hq9z3ldl",
                                    type: "Container",
                                    path: "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[4].children[0].children[0]",
                                    name: "Container",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Button_yo8bq8ib",
                                    type: "Button",
                                    path: "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[4].children[0].children[1]",
                                    name: "Button",
                                    text: "Planning",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_dnmt2sad",
                            type: "Container",
                            path: "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[5]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_f6eq07lp",
                                type: "Row",
                                path: "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[5].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_p2ftp2c8",
                                    type: "Container",
                                    path: "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[5].children[0].children[0]",
                                    name: "Container",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Button_dc8k657r",
                                    type: "Button",
                                    path: "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[5].children[0].children[1]",
                                    name: "Button",
                                    text: "Wedstrijden",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_6vuudyce",
                            type: "Container",
                            path: "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[6]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_vxg2u7ie",
                                type: "Row",
                                path: "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[6].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_8cyc25gy",
                                    type: "Container",
                                    path: "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[6].children[0].children[0]",
                                    name: "Container",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Button_66v7uet5",
                                    type: "Button",
                                    path: "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[6].children[0].children[1]",
                                    name: "Button",
                                    text: "Profiel",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Spacer_wfuyhmsd",
                            type: "Spacer",
                            path: "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[7]",
                            name: "FlexSpacer",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_lv1zk2kb",
                            type: "Container",
                            path: "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[8]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_4wezvf6l",
                                type: "Row",
                                path: "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[8].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Icon_8h88rlmv",
                                    type: "Icon",
                                    path: "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[8].children[0].children[0]",
                                    name: "Icon",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_f5zlxecr",
                                    type: "Column",
                                    path: "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[8].children[0].children[1]",
                                    name: "Column",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_x06dc8z9",
                                        type: "Text",
                                        path: "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[8].children[0].children[1].children[0]",
                                        name: "Text",
                                        text: "Local prototype",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_w9y05ksm",
                                        type: "Text",
                                        path: "PersonalWorkspacePage.body[0].children[0].children[0].children[0].children[8].children[0].children[1].children[1]",
                                        name: "Text",
                                        text: "Sample data only",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Column_5hga3m6e",
                type: "Column",
                path: "PersonalWorkspacePage.body[0].children[1]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_c6pqive6",
                    type: "Container",
                    path: "PersonalWorkspacePage.body[0].children[1].children[0]",
                    name: "Phase4BStableContextSelector",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_rpn05gaj",
                        type: "Container",
                        path: "PersonalWorkspacePage.body[0].children[1].children[0].children[0]",
                        name: "Phase4BStableContextRuntime",
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_epiw19wl",
                    type: "Container",
                    path: "PersonalWorkspacePage.body[0].children[1].children[1]",
                    name: "Phase4BpersonalWorkspaceRuntime",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_eokbmlkw",
                    type: "Container",
                    path: "PersonalWorkspacePage.body[0].children[1].children[2]",
                    name: "Phase4BMobileBottomNavigation",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_79c38ytb",
                        type: "Container",
                        path: "PersonalWorkspacePage.body[0].children[1].children[2].children[0]",
                        name: "AvarynMobileNavigationBody",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Row_ipxsra9i",
                            type: "Row",
                            path: "PersonalWorkspacePage.body[0].children[1].children[2].children[0].children[0]",
                            name: "Row",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Container_9c1p9ect",
                                type: "Container",
                                path: "PersonalWorkspacePage.body[0].children[1].children[2].children[0].children[0].children[0]",
                                name: "Container",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_bbrneguh",
                                    type: "Column",
                                    path: "PersonalWorkspacePage.body[0].children[1].children[2].children[0].children[0].children[0].children[0]",
                                    name: "Column",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_9j43jtnu",
                                        type: "Container",
                                        path: "PersonalWorkspacePage.body[0].children[1].children[2].children[0].children[0].children[0].children[0].children[0]",
                                        name: "Container",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_2wobd7xq",
                                        type: "Icon",
                                        path: "PersonalWorkspacePage.body[0].children[1].children[2].children[0].children[0].children[0].children[0].children[1]",
                                        name: "Icon",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_ipuy5yz2",
                                        type: "Text",
                                        path: "PersonalWorkspacePage.body[0].children[1].children[2].children[0].children[0].children[0].children[0].children[2]",
                                        name: "Text",
                                        text: "Vandaag",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Container_y5cgjdrh",
                                type: "Container",
                                path: "PersonalWorkspacePage.body[0].children[1].children[2].children[0].children[0].children[1]",
                                name: "Container",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_jmgme1my",
                                    type: "Column",
                                    path: "PersonalWorkspacePage.body[0].children[1].children[2].children[0].children[0].children[1].children[0]",
                                    name: "Column",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_ktos5wv7",
                                        type: "Container",
                                        path: "PersonalWorkspacePage.body[0].children[1].children[2].children[0].children[0].children[1].children[0].children[0]",
                                        name: "Container",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_nnjhldfd",
                                        type: "Container",
                                        path: "PersonalWorkspacePage.body[0].children[1].children[2].children[0].children[0].children[1].children[0].children[1]",
                                        name: "Container",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_efd0g972",
                                            type: "Container",
                                            path: "PersonalWorkspacePage.body[0].children[1].children[2].children[0].children[0].children[1].children[0].children[1].children[0]",
                                            name: "AvarynHorseshoeIcon",
                                          ),
                                        ],
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_w0rk5v09",
                                        type: "Text",
                                        path: "PersonalWorkspacePage.body[0].children[1].children[2].children[0].children[0].children[1].children[0].children[2]",
                                        name: "Text",
                                        text: "Paarden",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Container_fifwy31k",
                                type: "Container",
                                path: "PersonalWorkspacePage.body[0].children[1].children[2].children[0].children[0].children[2]",
                                name: "Container",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_ge3twi71",
                                    type: "Column",
                                    path: "PersonalWorkspacePage.body[0].children[1].children[2].children[0].children[0].children[2].children[0]",
                                    name: "Column",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_f3bvs54j",
                                        type: "Container",
                                        path: "PersonalWorkspacePage.body[0].children[1].children[2].children[0].children[0].children[2].children[0].children[0]",
                                        name: "Container",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_ez3t22df",
                                        type: "Icon",
                                        path: "PersonalWorkspacePage.body[0].children[1].children[2].children[0].children[0].children[2].children[0].children[1]",
                                        name: "Icon",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_m6p89y5l",
                                        type: "Text",
                                        path: "PersonalWorkspacePage.body[0].children[1].children[2].children[0].children[0].children[2].children[0].children[2]",
                                        name: "Text",
                                        text: "Planning",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Container_w4q6orep",
                                type: "Container",
                                path: "PersonalWorkspacePage.body[0].children[1].children[2].children[0].children[0].children[3]",
                                name: "Container",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_ffrz7fa1",
                                    type: "Column",
                                    path: "PersonalWorkspacePage.body[0].children[1].children[2].children[0].children[0].children[3].children[0]",
                                    name: "Column",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_a20sh0pd",
                                        type: "Container",
                                        path: "PersonalWorkspacePage.body[0].children[1].children[2].children[0].children[0].children[3].children[0].children[0]",
                                        name: "Container",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_kube7rag",
                                        type: "Icon",
                                        path: "PersonalWorkspacePage.body[0].children[1].children[2].children[0].children[0].children[3].children[0].children[1]",
                                        name: "Icon",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_o2v0qxpk",
                                        type: "Text",
                                        path: "PersonalWorkspacePage.body[0].children[1].children[2].children[0].children[0].children[3].children[0].children[2]",
                                        name: "Text",
                                        text: "Wedstrijden",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Container_1qspjbzt",
                                type: "Container",
                                path: "PersonalWorkspacePage.body[0].children[1].children[2].children[0].children[0].children[4]",
                                name: "Container",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_j1vkys8r",
                                    type: "Column",
                                    path: "PersonalWorkspacePage.body[0].children[1].children[2].children[0].children[0].children[4].children[0]",
                                    name: "Column",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_y1ondox6",
                                        type: "Container",
                                        path: "PersonalWorkspacePage.body[0].children[1].children[2].children[0].children[0].children[4].children[0].children[0]",
                                        name: "Container",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_hfv3b5tn",
                                        type: "Icon",
                                        path: "PersonalWorkspacePage.body[0].children[1].children[2].children[0].children[0].children[4].children[0].children[1]",
                                        name: "Icon",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_9f43i7bu",
                                        type: "Text",
                                        path: "PersonalWorkspacePage.body[0].children[1].children[2].children[0].children[0].children[4].children[0].children[2]",
                                        name: "Text",
                                        text: "Profiel",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}
