// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final planningPageHandle = ffai.ProjectPageHandle<PlanningPageParams, PlanningPageState>(
  name: "PlanningPage",
  key: "Scaffold_aukt1zt2",
  route: "planning",
  params: const PlanningPageParams(),
  state: const PlanningPageState(),
  widgets: PlanningPageWidgets.tree,
);

final class PlanningPageParams {
  const PlanningPageParams();
}

final class PlanningPageState {
  const PlanningPageState();
}

abstract final class PlanningPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_aukt1zt2",
      type: "Scaffold",
      path: "PlanningPage",
      name: "PlanningPage",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Row_0ik5geoc",
            type: "Row",
            path: "PlanningPage.body[0]",
            name: "Phase4C7ResponsiveShell",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Container_orlsb2f3",
                type: "Container",
                path: "PlanningPage.body[0].children[0]",
                name: "Phase4C7DesktopSideNavigation",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_r68hw7f6",
                    type: "Container",
                    path: "PlanningPage.body[0].children[0].children[0]",
                    name: "AvarynDesktopNavigationBody",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_2jw01n02",
                        type: "Column",
                        path: "PlanningPage.body[0].children[0].children[0].children[0]",
                        name: "Column",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_owlejhim",
                            type: "Container",
                            path: "PlanningPage.body[0].children[0].children[0].children[0].children[0]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Column_959q91uj",
                                type: "Column",
                                path: "PlanningPage.body[0].children[0].children[0].children[0].children[0].children[0]",
                                name: "Column",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_zgvi9q4m",
                                    type: "Text",
                                    path: "PlanningPage.body[0].children[0].children[0].children[0].children[0].children[0].children[0]",
                                    name: "Text",
                                    text: "AVARYN",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_qg7xp4p2",
                                    type: "Text",
                                    path: "PlanningPage.body[0].children[0].children[0].children[0].children[0].children[0].children[1]",
                                    name: "Text",
                                    text: "Performance",
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_mabtjusj",
                            type: "Container",
                            path: "PlanningPage.body[0].children[0].children[0].children[0].children[1]",
                            name: "Container",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_r9lzhzwl",
                            type: "Container",
                            path: "PlanningPage.body[0].children[0].children[0].children[0].children[2]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_s8009mcg",
                                type: "Row",
                                path: "PlanningPage.body[0].children[0].children[0].children[0].children[2].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_tgmq6beh",
                                    type: "Container",
                                    path: "PlanningPage.body[0].children[0].children[0].children[0].children[2].children[0].children[0]",
                                    name: "Container",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Button_kshf7os7",
                                    type: "Button",
                                    path: "PlanningPage.body[0].children[0].children[0].children[0].children[2].children[0].children[1]",
                                    name: "Button",
                                    text: "Vandaag",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_gkcr3zrk",
                            type: "Container",
                            path: "PlanningPage.body[0].children[0].children[0].children[0].children[3]",
                            name: "Container",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_9swht6mk",
                                type: "Row",
                                path: "PlanningPage.body[0].children[0].children[0].children[0].children[3].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_bpzjlcs0",
                                    type: "Container",
                                    path: "PlanningPage.body[0].children[0].children[0].children[0].children[3].children[0].children[0]",
                                    name: "Container",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_yqtiuyur",
                                    type: "Container",
                                    path: "PlanningPage.body[0].children[0].children[0].children[0].children[3].children[0].children[1]",
                                    name: "Container",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Row_ukt43szd",
                                        type: "Row",
                                        path: "PlanningPage.body[0].children[0].children[0].children[0].children[3].children[0].children[1].children[0]",
                                        name: "Row",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_mgl7owq7",
                                            type: "Container",
                                            path: "PlanningPage.body[0].children[0].children[0].children[0].children[3].children[0].children[1].children[0].children[0]",
                                            name: "Container",
                                            children: <ffai.ProjectWidgetHandle>[
                                              ffai.ProjectWidgetHandle(
                                                key: "Container_28gj4hlj",
                                                type: "Container",
                                                path: "PlanningPage.body[0].children[0].children[0].children[0].children[3].children[0].children[1].children[0].children[0].children[0]",
                                                name: "AvarynHorseshoeIcon",
                                              ),
                                            ],
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_7dcuh0c4",
                                            type: "Text",
                                            path: "PlanningPage.body[0].children[0].children[0].children[0].children[3].children[0].children[1].children[0].children[1]",
                                            name: "Text",
                                            text: "Paarden",
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_102clovr",
                            type: "Container",
                            path: "PlanningPage.body[0].children[0].children[0].children[0].children[4]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_3b5nqq50",
                                type: "Row",
                                path: "PlanningPage.body[0].children[0].children[0].children[0].children[4].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_z1bpeh2g",
                                    type: "Container",
                                    path: "PlanningPage.body[0].children[0].children[0].children[0].children[4].children[0].children[0]",
                                    name: "Container",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Button_sxlc4rai",
                                    type: "Button",
                                    path: "PlanningPage.body[0].children[0].children[0].children[0].children[4].children[0].children[1]",
                                    name: "Button",
                                    text: "Voeding",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_rdhnek8i",
                            type: "Container",
                            path: "PlanningPage.body[0].children[0].children[0].children[0].children[5]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_n329hd87",
                                type: "Row",
                                path: "PlanningPage.body[0].children[0].children[0].children[0].children[5].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_7j74pyid",
                                    type: "Container",
                                    path: "PlanningPage.body[0].children[0].children[0].children[0].children[5].children[0].children[0]",
                                    name: "Container",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Button_hyt0virx",
                                    type: "Button",
                                    path: "PlanningPage.body[0].children[0].children[0].children[0].children[5].children[0].children[1]",
                                    name: "Button",
                                    text: "Planning",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_x39gq0zp",
                            type: "Container",
                            path: "PlanningPage.body[0].children[0].children[0].children[0].children[6]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_r17orn0f",
                                type: "Row",
                                path: "PlanningPage.body[0].children[0].children[0].children[0].children[6].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_5kqn19sx",
                                    type: "Container",
                                    path: "PlanningPage.body[0].children[0].children[0].children[0].children[6].children[0].children[0]",
                                    name: "Container",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Button_o1t3er0x",
                                    type: "Button",
                                    path: "PlanningPage.body[0].children[0].children[0].children[0].children[6].children[0].children[1]",
                                    name: "Button",
                                    text: "Profiel",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Spacer_lnu4lsb5",
                            type: "Spacer",
                            path: "PlanningPage.body[0].children[0].children[0].children[0].children[7]",
                            name: "FlexSpacer",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_misqxk04",
                            type: "Container",
                            path: "PlanningPage.body[0].children[0].children[0].children[0].children[8]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_uh9ig94a",
                                type: "Row",
                                path: "PlanningPage.body[0].children[0].children[0].children[0].children[8].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Icon_mqkes3gp",
                                    type: "Icon",
                                    path: "PlanningPage.body[0].children[0].children[0].children[0].children[8].children[0].children[0]",
                                    name: "Icon",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_ymfx6uu3",
                                    type: "Column",
                                    path: "PlanningPage.body[0].children[0].children[0].children[0].children[8].children[0].children[1]",
                                    name: "Column",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_axwtxs9x",
                                        type: "Text",
                                        path: "PlanningPage.body[0].children[0].children[0].children[0].children[8].children[0].children[1].children[0]",
                                        name: "Text",
                                        text: "Besloten Alpha",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_fglpqs8u",
                                        type: "Text",
                                        path: "PlanningPage.body[0].children[0].children[0].children[0].children[8].children[0].children[1].children[1]",
                                        name: "Text",
                                        text: "Geen productie",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Container_ayif70bi",
                type: "Container",
                path: "PlanningPage.body[0].children[1]",
                name: "Phase4C7OperationalColumnBounds",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Column_4fey3kea",
                    type: "Column",
                    path: "PlanningPage.body[0].children[1].children[0]",
                    name: "Column",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_gghwn7e5",
                        type: "Container",
                        path: "PlanningPage.body[0].children[1].children[0].children[0]",
                        name: "Phase4C7StableContextSelector",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_nnciq3jn",
                            type: "Container",
                            path: "PlanningPage.body[0].children[1].children[0].children[0].children[0]",
                            name: "Phase4C7StableContextRuntime",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_nkf18glg",
                        type: "Container",
                        path: "PlanningPage.body[0].children[1].children[0].children[1]",
                        name: "Phase4C7OperationalRuntime",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_jz1sdt25",
                        type: "Container",
                        path: "PlanningPage.body[0].children[1].children[0].children[2]",
                        name: "Phase4C7MobileBottomNavigation",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_yudfzmsf",
                            type: "Container",
                            path: "PlanningPage.body[0].children[1].children[0].children[2].children[0]",
                            name: "AvarynMobileNavigationBody",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_rtrjwgni",
                                type: "Row",
                                path: "PlanningPage.body[0].children[1].children[0].children[2].children[0].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_5cnm2z0g",
                                    type: "Container",
                                    path: "PlanningPage.body[0].children[1].children[0].children[2].children[0].children[0].children[0]",
                                    name: "Container",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Column_8ds6em43",
                                        type: "Column",
                                        path: "PlanningPage.body[0].children[1].children[0].children[2].children[0].children[0].children[0].children[0]",
                                        name: "Column",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_o5lvbzre",
                                            type: "Container",
                                            path: "PlanningPage.body[0].children[1].children[0].children[2].children[0].children[0].children[0].children[0].children[0]",
                                            name: "Container",
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Icon_km5jymmh",
                                            type: "Icon",
                                            path: "PlanningPage.body[0].children[1].children[0].children[2].children[0].children[0].children[0].children[0].children[1]",
                                            name: "Icon",
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_rx970qjr",
                                            type: "Text",
                                            path: "PlanningPage.body[0].children[1].children[0].children[2].children[0].children[0].children[0].children[0].children[2]",
                                            name: "Text",
                                            text: "Vandaag",
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_0w2svwua",
                                    type: "Container",
                                    path: "PlanningPage.body[0].children[1].children[0].children[2].children[0].children[0].children[1]",
                                    name: "Container",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Column_k3h03n9d",
                                        type: "Column",
                                        path: "PlanningPage.body[0].children[1].children[0].children[2].children[0].children[0].children[1].children[0]",
                                        name: "Column",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_c07qbkbp",
                                            type: "Container",
                                            path: "PlanningPage.body[0].children[1].children[0].children[2].children[0].children[0].children[1].children[0].children[0]",
                                            name: "Container",
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_n77koi92",
                                            type: "Container",
                                            path: "PlanningPage.body[0].children[1].children[0].children[2].children[0].children[0].children[1].children[0].children[1]",
                                            name: "Container",
                                            children: <ffai.ProjectWidgetHandle>[
                                              ffai.ProjectWidgetHandle(
                                                key: "Container_6bwjqa4x",
                                                type: "Container",
                                                path: "PlanningPage.body[0].children[1].children[0].children[2].children[0].children[0].children[1].children[0].children[1].children[0]",
                                                name: "AvarynHorseshoeIcon",
                                              ),
                                            ],
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_cpfphmp7",
                                            type: "Text",
                                            path: "PlanningPage.body[0].children[1].children[0].children[2].children[0].children[0].children[1].children[0].children[2]",
                                            name: "Text",
                                            text: "Paarden",
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_wdb2xka7",
                                    type: "Container",
                                    path: "PlanningPage.body[0].children[1].children[0].children[2].children[0].children[0].children[2]",
                                    name: "Container",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Column_k1g1l787",
                                        type: "Column",
                                        path: "PlanningPage.body[0].children[1].children[0].children[2].children[0].children[0].children[2].children[0]",
                                        name: "Column",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_aok8yzdr",
                                            type: "Container",
                                            path: "PlanningPage.body[0].children[1].children[0].children[2].children[0].children[0].children[2].children[0].children[0]",
                                            name: "Container",
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Icon_elpx6x69",
                                            type: "Icon",
                                            path: "PlanningPage.body[0].children[1].children[0].children[2].children[0].children[0].children[2].children[0].children[1]",
                                            name: "Icon",
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_0q80d756",
                                            type: "Text",
                                            path: "PlanningPage.body[0].children[1].children[0].children[2].children[0].children[0].children[2].children[0].children[2]",
                                            name: "Text",
                                            text: "Voeding",
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_5rvonkrx",
                                    type: "Container",
                                    path: "PlanningPage.body[0].children[1].children[0].children[2].children[0].children[0].children[3]",
                                    name: "Container",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Column_dx4hj8zg",
                                        type: "Column",
                                        path: "PlanningPage.body[0].children[1].children[0].children[2].children[0].children[0].children[3].children[0]",
                                        name: "Column",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_brp64ahl",
                                            type: "Container",
                                            path: "PlanningPage.body[0].children[1].children[0].children[2].children[0].children[0].children[3].children[0].children[0]",
                                            name: "Container",
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Icon_bn2bgnul",
                                            type: "Icon",
                                            path: "PlanningPage.body[0].children[1].children[0].children[2].children[0].children[0].children[3].children[0].children[1]",
                                            name: "Icon",
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_d2068nlo",
                                            type: "Text",
                                            path: "PlanningPage.body[0].children[1].children[0].children[2].children[0].children[0].children[3].children[0].children[2]",
                                            name: "Text",
                                            text: "Planning",
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_cr1bzo23",
                                    type: "Container",
                                    path: "PlanningPage.body[0].children[1].children[0].children[2].children[0].children[0].children[4]",
                                    name: "Container",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Column_ppmapzyh",
                                        type: "Column",
                                        path: "PlanningPage.body[0].children[1].children[0].children[2].children[0].children[0].children[4].children[0]",
                                        name: "Column",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_wpcjvdqc",
                                            type: "Container",
                                            path: "PlanningPage.body[0].children[1].children[0].children[2].children[0].children[0].children[4].children[0].children[0]",
                                            name: "Container",
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Icon_7uvtw914",
                                            type: "Icon",
                                            path: "PlanningPage.body[0].children[1].children[0].children[2].children[0].children[0].children[4].children[0].children[1]",
                                            name: "Icon",
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_1hu4w2pl",
                                            type: "Text",
                                            path: "PlanningPage.body[0].children[1].children[0].children[2].children[0].children[0].children[4].children[0].children[2]",
                                            name: "Text",
                                            text: "Profiel",
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}
