// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final stablePickerPageHandle = ffai.ProjectPageHandle<StablePickerPageParams, StablePickerPageState>(
  name: "StablePickerPage",
  key: "Scaffold_nd0rvjum",
  route: "stallen",
  params: const StablePickerPageParams(),
  state: const StablePickerPageState(),
  widgets: StablePickerPageWidgets.tree,
);

final class StablePickerPageParams {
  const StablePickerPageParams();
}

final class StablePickerPageState {
  const StablePickerPageState();
}

abstract final class StablePickerPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_nd0rvjum",
      type: "Scaffold",
      path: "StablePickerPage",
      name: "StablePickerPage",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Row_ljmogcgo",
            type: "Row",
            path: "StablePickerPage.body[0]",
            name: "Phase4BResponsiveShell",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Container_1cxryfke",
                type: "Container",
                path: "StablePickerPage.body[0].children[0]",
                name: "Phase4BDesktopSideNavigation",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_kfgk5fgn",
                    type: "Container",
                    path: "StablePickerPage.body[0].children[0].children[0]",
                    name: "AvarynDesktopNavigationBody",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_mnmqwdbo",
                        type: "Column",
                        path: "StablePickerPage.body[0].children[0].children[0].children[0]",
                        name: "Column",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_iwp0pefo",
                            type: "Container",
                            path: "StablePickerPage.body[0].children[0].children[0].children[0].children[0]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Column_39nxj04a",
                                type: "Column",
                                path: "StablePickerPage.body[0].children[0].children[0].children[0].children[0].children[0]",
                                name: "Column",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_b8y1fyn9",
                                    type: "Text",
                                    path: "StablePickerPage.body[0].children[0].children[0].children[0].children[0].children[0].children[0]",
                                    name: "Text",
                                    text: "AVARYN",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_8ma5ub5e",
                                    type: "Text",
                                    path: "StablePickerPage.body[0].children[0].children[0].children[0].children[0].children[0].children[1]",
                                    name: "Text",
                                    text: "Performance",
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_ix9uie2z",
                            type: "Container",
                            path: "StablePickerPage.body[0].children[0].children[0].children[0].children[1]",
                            name: "Container",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_uuxu23yg",
                            type: "Container",
                            path: "StablePickerPage.body[0].children[0].children[0].children[0].children[2]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_5ib2ik55",
                                type: "Row",
                                path: "StablePickerPage.body[0].children[0].children[0].children[0].children[2].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_g65qzi5r",
                                    type: "Container",
                                    path: "StablePickerPage.body[0].children[0].children[0].children[0].children[2].children[0].children[0]",
                                    name: "Container",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Button_k3idzt6n",
                                    type: "Button",
                                    path: "StablePickerPage.body[0].children[0].children[0].children[0].children[2].children[0].children[1]",
                                    name: "Button",
                                    text: "Vandaag",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_7auxw4ga",
                            type: "Container",
                            path: "StablePickerPage.body[0].children[0].children[0].children[0].children[3]",
                            name: "Container",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_14im3uon",
                                type: "Row",
                                path: "StablePickerPage.body[0].children[0].children[0].children[0].children[3].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_in2a96jm",
                                    type: "Container",
                                    path: "StablePickerPage.body[0].children[0].children[0].children[0].children[3].children[0].children[0]",
                                    name: "Container",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_k9igapj9",
                                    type: "Container",
                                    path: "StablePickerPage.body[0].children[0].children[0].children[0].children[3].children[0].children[1]",
                                    name: "Container",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Row_p8mnu4jr",
                                        type: "Row",
                                        path: "StablePickerPage.body[0].children[0].children[0].children[0].children[3].children[0].children[1].children[0]",
                                        name: "Row",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_lg1ahpmp",
                                            type: "Container",
                                            path: "StablePickerPage.body[0].children[0].children[0].children[0].children[3].children[0].children[1].children[0].children[0]",
                                            name: "Container",
                                            children: <ffai.ProjectWidgetHandle>[
                                              ffai.ProjectWidgetHandle(
                                                key: "Container_zf3aibil",
                                                type: "Container",
                                                path: "StablePickerPage.body[0].children[0].children[0].children[0].children[3].children[0].children[1].children[0].children[0].children[0]",
                                                name: "AvarynHorseshoeIcon",
                                              ),
                                            ],
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_zzijr262",
                                            type: "Text",
                                            path: "StablePickerPage.body[0].children[0].children[0].children[0].children[3].children[0].children[1].children[0].children[1]",
                                            name: "Text",
                                            text: "Paarden",
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_j7h31vkq",
                            type: "Container",
                            path: "StablePickerPage.body[0].children[0].children[0].children[0].children[4]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_fevaftb2",
                                type: "Row",
                                path: "StablePickerPage.body[0].children[0].children[0].children[0].children[4].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_pd0b7kgz",
                                    type: "Container",
                                    path: "StablePickerPage.body[0].children[0].children[0].children[0].children[4].children[0].children[0]",
                                    name: "Container",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Button_zbiat0cl",
                                    type: "Button",
                                    path: "StablePickerPage.body[0].children[0].children[0].children[0].children[4].children[0].children[1]",
                                    name: "Button",
                                    text: "Planning",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_pu116axn",
                            type: "Container",
                            path: "StablePickerPage.body[0].children[0].children[0].children[0].children[5]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_r8z3acke",
                                type: "Row",
                                path: "StablePickerPage.body[0].children[0].children[0].children[0].children[5].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_jzmzhykw",
                                    type: "Container",
                                    path: "StablePickerPage.body[0].children[0].children[0].children[0].children[5].children[0].children[0]",
                                    name: "Container",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Button_zsgenmsu",
                                    type: "Button",
                                    path: "StablePickerPage.body[0].children[0].children[0].children[0].children[5].children[0].children[1]",
                                    name: "Button",
                                    text: "Wedstrijden",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_2befq782",
                            type: "Container",
                            path: "StablePickerPage.body[0].children[0].children[0].children[0].children[6]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_muwcniie",
                                type: "Row",
                                path: "StablePickerPage.body[0].children[0].children[0].children[0].children[6].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_0l0gjgco",
                                    type: "Container",
                                    path: "StablePickerPage.body[0].children[0].children[0].children[0].children[6].children[0].children[0]",
                                    name: "Container",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Button_i15r4skb",
                                    type: "Button",
                                    path: "StablePickerPage.body[0].children[0].children[0].children[0].children[6].children[0].children[1]",
                                    name: "Button",
                                    text: "Profiel",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Spacer_hy3um5xx",
                            type: "Spacer",
                            path: "StablePickerPage.body[0].children[0].children[0].children[0].children[7]",
                            name: "FlexSpacer",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_4hf1nxbb",
                            type: "Container",
                            path: "StablePickerPage.body[0].children[0].children[0].children[0].children[8]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_22qt5nsr",
                                type: "Row",
                                path: "StablePickerPage.body[0].children[0].children[0].children[0].children[8].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Icon_kqyvlowk",
                                    type: "Icon",
                                    path: "StablePickerPage.body[0].children[0].children[0].children[0].children[8].children[0].children[0]",
                                    name: "Icon",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_dkeg0i5t",
                                    type: "Column",
                                    path: "StablePickerPage.body[0].children[0].children[0].children[0].children[8].children[0].children[1]",
                                    name: "Column",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_oq467vcl",
                                        type: "Text",
                                        path: "StablePickerPage.body[0].children[0].children[0].children[0].children[8].children[0].children[1].children[0]",
                                        name: "Text",
                                        text: "Local prototype",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_ngk817ji",
                                        type: "Text",
                                        path: "StablePickerPage.body[0].children[0].children[0].children[0].children[8].children[0].children[1].children[1]",
                                        name: "Text",
                                        text: "Sample data only",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Column_r790d9qe",
                type: "Column",
                path: "StablePickerPage.body[0].children[1]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_k5zsd1a8",
                    type: "Container",
                    path: "StablePickerPage.body[0].children[1].children[0]",
                    name: "Phase4BStableContextSelector",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_k5j5yedh",
                        type: "Container",
                        path: "StablePickerPage.body[0].children[1].children[0].children[0]",
                        name: "Phase4BStableContextRuntime",
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_7ifke8hw",
                    type: "Container",
                    path: "StablePickerPage.body[0].children[1].children[1]",
                    name: "Phase4BstablePickerRuntime",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_cqny7qq3",
                    type: "Container",
                    path: "StablePickerPage.body[0].children[1].children[2]",
                    name: "Phase4BMobileBottomNavigation",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_o7cpacei",
                        type: "Container",
                        path: "StablePickerPage.body[0].children[1].children[2].children[0]",
                        name: "AvarynMobileNavigationBody",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Row_jve6bi32",
                            type: "Row",
                            path: "StablePickerPage.body[0].children[1].children[2].children[0].children[0]",
                            name: "Row",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Container_fs0fxg1v",
                                type: "Container",
                                path: "StablePickerPage.body[0].children[1].children[2].children[0].children[0].children[0]",
                                name: "Container",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_wdhsatnw",
                                    type: "Column",
                                    path: "StablePickerPage.body[0].children[1].children[2].children[0].children[0].children[0].children[0]",
                                    name: "Column",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_fg31xx16",
                                        type: "Container",
                                        path: "StablePickerPage.body[0].children[1].children[2].children[0].children[0].children[0].children[0].children[0]",
                                        name: "Container",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_qkd7c4x6",
                                        type: "Icon",
                                        path: "StablePickerPage.body[0].children[1].children[2].children[0].children[0].children[0].children[0].children[1]",
                                        name: "Icon",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_alusjics",
                                        type: "Text",
                                        path: "StablePickerPage.body[0].children[1].children[2].children[0].children[0].children[0].children[0].children[2]",
                                        name: "Text",
                                        text: "Vandaag",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Container_eme4c3ny",
                                type: "Container",
                                path: "StablePickerPage.body[0].children[1].children[2].children[0].children[0].children[1]",
                                name: "Container",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_wshvhgwa",
                                    type: "Column",
                                    path: "StablePickerPage.body[0].children[1].children[2].children[0].children[0].children[1].children[0]",
                                    name: "Column",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_ud1dylyn",
                                        type: "Container",
                                        path: "StablePickerPage.body[0].children[1].children[2].children[0].children[0].children[1].children[0].children[0]",
                                        name: "Container",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_0w1k3tof",
                                        type: "Container",
                                        path: "StablePickerPage.body[0].children[1].children[2].children[0].children[0].children[1].children[0].children[1]",
                                        name: "Container",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_91b930sk",
                                            type: "Container",
                                            path: "StablePickerPage.body[0].children[1].children[2].children[0].children[0].children[1].children[0].children[1].children[0]",
                                            name: "AvarynHorseshoeIcon",
                                          ),
                                        ],
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_etxd7yx4",
                                        type: "Text",
                                        path: "StablePickerPage.body[0].children[1].children[2].children[0].children[0].children[1].children[0].children[2]",
                                        name: "Text",
                                        text: "Paarden",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Container_g67o0faf",
                                type: "Container",
                                path: "StablePickerPage.body[0].children[1].children[2].children[0].children[0].children[2]",
                                name: "Container",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_0mnojcus",
                                    type: "Column",
                                    path: "StablePickerPage.body[0].children[1].children[2].children[0].children[0].children[2].children[0]",
                                    name: "Column",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_cxgt1su6",
                                        type: "Container",
                                        path: "StablePickerPage.body[0].children[1].children[2].children[0].children[0].children[2].children[0].children[0]",
                                        name: "Container",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_64kx9cvd",
                                        type: "Icon",
                                        path: "StablePickerPage.body[0].children[1].children[2].children[0].children[0].children[2].children[0].children[1]",
                                        name: "Icon",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_plaeffwa",
                                        type: "Text",
                                        path: "StablePickerPage.body[0].children[1].children[2].children[0].children[0].children[2].children[0].children[2]",
                                        name: "Text",
                                        text: "Planning",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Container_uy9uz4jw",
                                type: "Container",
                                path: "StablePickerPage.body[0].children[1].children[2].children[0].children[0].children[3]",
                                name: "Container",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_117j65ed",
                                    type: "Column",
                                    path: "StablePickerPage.body[0].children[1].children[2].children[0].children[0].children[3].children[0]",
                                    name: "Column",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_lzpbvesr",
                                        type: "Container",
                                        path: "StablePickerPage.body[0].children[1].children[2].children[0].children[0].children[3].children[0].children[0]",
                                        name: "Container",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_ehhsfthg",
                                        type: "Icon",
                                        path: "StablePickerPage.body[0].children[1].children[2].children[0].children[0].children[3].children[0].children[1]",
                                        name: "Icon",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_o2o3abhu",
                                        type: "Text",
                                        path: "StablePickerPage.body[0].children[1].children[2].children[0].children[0].children[3].children[0].children[2]",
                                        name: "Text",
                                        text: "Wedstrijden",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Container_qfi420yu",
                                type: "Container",
                                path: "StablePickerPage.body[0].children[1].children[2].children[0].children[0].children[4]",
                                name: "Container",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_hdp6vqba",
                                    type: "Column",
                                    path: "StablePickerPage.body[0].children[1].children[2].children[0].children[0].children[4].children[0]",
                                    name: "Column",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_upkgfnr5",
                                        type: "Container",
                                        path: "StablePickerPage.body[0].children[1].children[2].children[0].children[0].children[4].children[0].children[0]",
                                        name: "Container",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_wupt66s3",
                                        type: "Icon",
                                        path: "StablePickerPage.body[0].children[1].children[2].children[0].children[0].children[4].children[0].children[1]",
                                        name: "Icon",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_5lyuxbnu",
                                        type: "Text",
                                        path: "StablePickerPage.body[0].children[1].children[2].children[0].children[0].children[4].children[0].children[2]",
                                        name: "Text",
                                        text: "Profiel",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}
