// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final stableDetailsPageHandle = ffai.ProjectPageHandle<StableDetailsPageParams, StableDetailsPageState>(
  name: "StableDetailsPage",
  key: "Scaffold_jjo5uu05",
  route: "stal",
  params: const StableDetailsPageParams(),
  state: const StableDetailsPageState(),
  widgets: StableDetailsPageWidgets.tree,
);

final class StableDetailsPageParams {
  const StableDetailsPageParams();
}

final class StableDetailsPageState {
  const StableDetailsPageState();
}

abstract final class StableDetailsPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_jjo5uu05",
      type: "Scaffold",
      path: "StableDetailsPage",
      name: "StableDetailsPage",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_fh14xloe",
            type: "Container",
            path: "StableDetailsPage.body[0]",
            name: "C009StableAccountShell",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_tzhf2ja6",
                type: "Column",
                path: "StableDetailsPage.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_3kip98sw",
                    type: "Container",
                    path: "StableDetailsPage.body[0].children[0].children[0]",
                    name: "C009StableAccountHeader",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_ouu456y4",
                        type: "Column",
                        path: "StableDetailsPage.body[0].children[0].children[0].children[0]",
                        name: "Column",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_tvgxekzh",
                            type: "Text",
                            path: "StableDetailsPage.body[0].children[0].children[0].children[0].children[0]",
                            name: "Text",
                            text: "Stalaccount",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_ek5058o8",
                            type: "Text",
                            path: "StableDetailsPage.body[0].children[0].children[0].children[0].children[1]",
                            name: "Text",
                            text: "Zelfstandige organisatie · expliciete capabilities · één Organization Authority",
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_fo4ijrf0",
                    type: "Container",
                    path: "StableDetailsPage.body[0].children[0].children[1]",
                    name: "C009StableAccountRuntime",
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}
