// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final stableInvitationPageHandle = ffai.ProjectPageHandle<StableInvitationPageParams, StableInvitationPageState>(
  name: "StableInvitationPage",
  key: "Scaffold_v1b9a0wn",
  route: "uitnodiging",
  params: const StableInvitationPageParams(),
  state: const StableInvitationPageState(),
  widgets: StableInvitationPageWidgets.tree,
);

final class StableInvitationPageParams {
  const StableInvitationPageParams();
}

final class StableInvitationPageState {
  const StableInvitationPageState();
}

abstract final class StableInvitationPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_v1b9a0wn",
      type: "Scaffold",
      path: "StableInvitationPage",
      name: "StableInvitationPage",
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Container_j18bwwoe",
            type: "Container",
            path: "StableInvitationPage.body[0]",
            name: "C009StableAccountShell",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_bxio7xxn",
                type: "Column",
                path: "StableInvitationPage.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_dh9v0hnl",
                    type: "Container",
                    path: "StableInvitationPage.body[0].children[0].children[0]",
                    name: "C009StableAccountHeader",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_1gyqotwe",
                        type: "Column",
                        path: "StableInvitationPage.body[0].children[0].children[0].children[0]",
                        name: "Column",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_4l4p6b37",
                            type: "Text",
                            path: "StableInvitationPage.body[0].children[0].children[0].children[0].children[0]",
                            name: "Text",
                            text: "Stalaccount",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_1956luc4",
                            type: "Text",
                            path: "StableInvitationPage.body[0].children[0].children[0].children[0].children[1]",
                            name: "Text",
                            text: "Zelfstandige organisatie · expliciete capabilities · één Organization Authority",
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_jnr7ehkx",
                    type: "Container",
                    path: "StableInvitationPage.body[0].children[0].children[1]",
                    name: "C009StableAccountRuntime",
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}
