// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final todayDashboardPageHandle = ffai.ProjectPageHandle<TodayDashboardPageParams, TodayDashboardPageState>(
  name: "TodayDashboardPage",
  key: "Scaffold_ftur3dgc",
  route: "today",
  params: const TodayDashboardPageParams(),
  state: const TodayDashboardPageState(),
  widgets: TodayDashboardPageWidgets.tree,
);

final class TodayDashboardPageParams {
  const TodayDashboardPageParams();
}

final class TodayDashboardPageState {
  const TodayDashboardPageState();
  ffai.ProjectStateFieldHandle get selectedHorse =>
      const ffai.ProjectStateFieldHandle(
        name: "selectedHorse",
        key: "dfvcgq34",
        typeName: "String",
      );
}

abstract final class TodayDashboardPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_ftur3dgc",
      type: "Scaffold",
      path: "TodayDashboardPage",
      name: "TodayDashboardPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Row_knmj63im",
            type: "Row",
            path: "TodayDashboardPage.body[0]",
            name: "Phase4C7ResponsiveShell",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Container_ckqzkatn",
                type: "Container",
                path: "TodayDashboardPage.body[0].children[0]",
                name: "Phase4C7DesktopSideNavigation",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_oic8bcrn",
                    type: "Container",
                    path: "TodayDashboardPage.body[0].children[0].children[0]",
                    name: "AvarynDesktopNavigationBody",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_ym2pmieu",
                        type: "Column",
                        path: "TodayDashboardPage.body[0].children[0].children[0].children[0]",
                        name: "Column",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_kszytm8x",
                            type: "Container",
                            path: "TodayDashboardPage.body[0].children[0].children[0].children[0].children[0]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Column_cngchhls",
                                type: "Column",
                                path: "TodayDashboardPage.body[0].children[0].children[0].children[0].children[0].children[0]",
                                name: "Column",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_cp0ohar2",
                                    type: "Text",
                                    path: "TodayDashboardPage.body[0].children[0].children[0].children[0].children[0].children[0].children[0]",
                                    name: "Text",
                                    text: "AVARYN",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_7oysk8wk",
                                    type: "Text",
                                    path: "TodayDashboardPage.body[0].children[0].children[0].children[0].children[0].children[0].children[1]",
                                    name: "Text",
                                    text: "Performance",
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_7rfooehk",
                            type: "Container",
                            path: "TodayDashboardPage.body[0].children[0].children[0].children[0].children[1]",
                            name: "Container",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_ln8zj2z5",
                            type: "Container",
                            path: "TodayDashboardPage.body[0].children[0].children[0].children[0].children[2]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_wa47rcrb",
                                type: "Row",
                                path: "TodayDashboardPage.body[0].children[0].children[0].children[0].children[2].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_44wwra1u",
                                    type: "Container",
                                    path: "TodayDashboardPage.body[0].children[0].children[0].children[0].children[2].children[0].children[0]",
                                    name: "Container",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Button_yensytc3",
                                    type: "Button",
                                    path: "TodayDashboardPage.body[0].children[0].children[0].children[0].children[2].children[0].children[1]",
                                    name: "Button",
                                    text: "Vandaag",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_mfocs0q1",
                            type: "Container",
                            path: "TodayDashboardPage.body[0].children[0].children[0].children[0].children[3]",
                            name: "Container",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_9aumz68l",
                                type: "Row",
                                path: "TodayDashboardPage.body[0].children[0].children[0].children[0].children[3].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_4f4i3r0d",
                                    type: "Container",
                                    path: "TodayDashboardPage.body[0].children[0].children[0].children[0].children[3].children[0].children[0]",
                                    name: "Container",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_eodxmmis",
                                    type: "Container",
                                    path: "TodayDashboardPage.body[0].children[0].children[0].children[0].children[3].children[0].children[1]",
                                    name: "Container",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Row_pv9qxnv0",
                                        type: "Row",
                                        path: "TodayDashboardPage.body[0].children[0].children[0].children[0].children[3].children[0].children[1].children[0]",
                                        name: "Row",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_ayl9mum1",
                                            type: "Container",
                                            path: "TodayDashboardPage.body[0].children[0].children[0].children[0].children[3].children[0].children[1].children[0].children[0]",
                                            name: "Container",
                                            children: <ffai.ProjectWidgetHandle>[
                                              ffai.ProjectWidgetHandle(
                                                key: "Container_d1p0poq3",
                                                type: "Container",
                                                path: "TodayDashboardPage.body[0].children[0].children[0].children[0].children[3].children[0].children[1].children[0].children[0].children[0]",
                                                name: "AvarynHorseshoeIcon",
                                              ),
                                            ],
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_ize5l85m",
                                            type: "Text",
                                            path: "TodayDashboardPage.body[0].children[0].children[0].children[0].children[3].children[0].children[1].children[0].children[1]",
                                            name: "Text",
                                            text: "Paarden",
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_krjsmmjz",
                            type: "Container",
                            path: "TodayDashboardPage.body[0].children[0].children[0].children[0].children[4]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_z1nmo7po",
                                type: "Row",
                                path: "TodayDashboardPage.body[0].children[0].children[0].children[0].children[4].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_8xg0cym5",
                                    type: "Container",
                                    path: "TodayDashboardPage.body[0].children[0].children[0].children[0].children[4].children[0].children[0]",
                                    name: "Container",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Button_t70a3482",
                                    type: "Button",
                                    path: "TodayDashboardPage.body[0].children[0].children[0].children[0].children[4].children[0].children[1]",
                                    name: "Button",
                                    text: "Voeding",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_57xpp04k",
                            type: "Container",
                            path: "TodayDashboardPage.body[0].children[0].children[0].children[0].children[5]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_bp81ona8",
                                type: "Row",
                                path: "TodayDashboardPage.body[0].children[0].children[0].children[0].children[5].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_l9n1pfmp",
                                    type: "Container",
                                    path: "TodayDashboardPage.body[0].children[0].children[0].children[0].children[5].children[0].children[0]",
                                    name: "Container",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Button_vfx3tmg2",
                                    type: "Button",
                                    path: "TodayDashboardPage.body[0].children[0].children[0].children[0].children[5].children[0].children[1]",
                                    name: "Button",
                                    text: "Planning",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_bpzbir97",
                            type: "Container",
                            path: "TodayDashboardPage.body[0].children[0].children[0].children[0].children[6]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_syzccjx5",
                                type: "Row",
                                path: "TodayDashboardPage.body[0].children[0].children[0].children[0].children[6].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_i6uemb8m",
                                    type: "Container",
                                    path: "TodayDashboardPage.body[0].children[0].children[0].children[0].children[6].children[0].children[0]",
                                    name: "Container",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Button_sioltmh2",
                                    type: "Button",
                                    path: "TodayDashboardPage.body[0].children[0].children[0].children[0].children[6].children[0].children[1]",
                                    name: "Button",
                                    text: "Profiel",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Spacer_93h08pyc",
                            type: "Spacer",
                            path: "TodayDashboardPage.body[0].children[0].children[0].children[0].children[7]",
                            name: "FlexSpacer",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_xmff230c",
                            type: "Container",
                            path: "TodayDashboardPage.body[0].children[0].children[0].children[0].children[8]",
                            name: "Container",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_1nxavmas",
                                type: "Row",
                                path: "TodayDashboardPage.body[0].children[0].children[0].children[0].children[8].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Icon_7lazrmpk",
                                    type: "Icon",
                                    path: "TodayDashboardPage.body[0].children[0].children[0].children[0].children[8].children[0].children[0]",
                                    name: "Icon",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_w0amx8c5",
                                    type: "Column",
                                    path: "TodayDashboardPage.body[0].children[0].children[0].children[0].children[8].children[0].children[1]",
                                    name: "Column",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_v0tyiuhe",
                                        type: "Text",
                                        path: "TodayDashboardPage.body[0].children[0].children[0].children[0].children[8].children[0].children[1].children[0]",
                                        name: "Text",
                                        text: "Besloten Alpha",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_6gi0gm3b",
                                        type: "Text",
                                        path: "TodayDashboardPage.body[0].children[0].children[0].children[0].children[8].children[0].children[1].children[1]",
                                        name: "Text",
                                        text: "Geen productie",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Container_4yasira9",
                type: "Container",
                path: "TodayDashboardPage.body[0].children[1]",
                name: "Phase4C7OperationalColumnBounds",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Column_m01vtfpx",
                    type: "Column",
                    path: "TodayDashboardPage.body[0].children[1].children[0]",
                    name: "Column",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_vqeel8ow",
                        type: "Container",
                        path: "TodayDashboardPage.body[0].children[1].children[0].children[0]",
                        name: "Phase4C7StableContextSelector",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_dsxpugp6",
                            type: "Container",
                            path: "TodayDashboardPage.body[0].children[1].children[0].children[0].children[0]",
                            name: "Phase4C7StableContextRuntime",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_fkqvosdy",
                        type: "Container",
                        path: "TodayDashboardPage.body[0].children[1].children[0].children[1]",
                        name: "Phase4C7OperationalRuntime",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_i0bkh31a",
                        type: "Container",
                        path: "TodayDashboardPage.body[0].children[1].children[0].children[2]",
                        name: "Phase4C7MobileBottomNavigation",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_z0bga6sv",
                            type: "Container",
                            path: "TodayDashboardPage.body[0].children[1].children[0].children[2].children[0]",
                            name: "AvarynMobileNavigationBody",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_n0fd0z94",
                                type: "Row",
                                path: "TodayDashboardPage.body[0].children[1].children[0].children[2].children[0].children[0]",
                                name: "Row",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_t5fkh64b",
                                    type: "Container",
                                    path: "TodayDashboardPage.body[0].children[1].children[0].children[2].children[0].children[0].children[0]",
                                    name: "Container",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Column_47a73jo5",
                                        type: "Column",
                                        path: "TodayDashboardPage.body[0].children[1].children[0].children[2].children[0].children[0].children[0].children[0]",
                                        name: "Column",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_i6fut192",
                                            type: "Container",
                                            path: "TodayDashboardPage.body[0].children[1].children[0].children[2].children[0].children[0].children[0].children[0].children[0]",
                                            name: "Container",
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Icon_66ocrfh5",
                                            type: "Icon",
                                            path: "TodayDashboardPage.body[0].children[1].children[0].children[2].children[0].children[0].children[0].children[0].children[1]",
                                            name: "Icon",
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_d4ne0zok",
                                            type: "Text",
                                            path: "TodayDashboardPage.body[0].children[1].children[0].children[2].children[0].children[0].children[0].children[0].children[2]",
                                            name: "Text",
                                            text: "Vandaag",
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_kujkhmzj",
                                    type: "Container",
                                    path: "TodayDashboardPage.body[0].children[1].children[0].children[2].children[0].children[0].children[1]",
                                    name: "Container",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Column_p6tniwd4",
                                        type: "Column",
                                        path: "TodayDashboardPage.body[0].children[1].children[0].children[2].children[0].children[0].children[1].children[0]",
                                        name: "Column",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_y1epbjvd",
                                            type: "Container",
                                            path: "TodayDashboardPage.body[0].children[1].children[0].children[2].children[0].children[0].children[1].children[0].children[0]",
                                            name: "Container",
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_9p8c49b4",
                                            type: "Container",
                                            path: "TodayDashboardPage.body[0].children[1].children[0].children[2].children[0].children[0].children[1].children[0].children[1]",
                                            name: "Container",
                                            children: <ffai.ProjectWidgetHandle>[
                                              ffai.ProjectWidgetHandle(
                                                key: "Container_usz95tw7",
                                                type: "Container",
                                                path: "TodayDashboardPage.body[0].children[1].children[0].children[2].children[0].children[0].children[1].children[0].children[1].children[0]",
                                                name: "AvarynHorseshoeIcon",
                                              ),
                                            ],
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_yugmdaw2",
                                            type: "Text",
                                            path: "TodayDashboardPage.body[0].children[1].children[0].children[2].children[0].children[0].children[1].children[0].children[2]",
                                            name: "Text",
                                            text: "Paarden",
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_xna4zcvq",
                                    type: "Container",
                                    path: "TodayDashboardPage.body[0].children[1].children[0].children[2].children[0].children[0].children[2]",
                                    name: "Container",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Column_k2fzbdbu",
                                        type: "Column",
                                        path: "TodayDashboardPage.body[0].children[1].children[0].children[2].children[0].children[0].children[2].children[0]",
                                        name: "Column",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_42wjw29r",
                                            type: "Container",
                                            path: "TodayDashboardPage.body[0].children[1].children[0].children[2].children[0].children[0].children[2].children[0].children[0]",
                                            name: "Container",
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Icon_ygnn6w8k",
                                            type: "Icon",
                                            path: "TodayDashboardPage.body[0].children[1].children[0].children[2].children[0].children[0].children[2].children[0].children[1]",
                                            name: "Icon",
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_75t3e2oh",
                                            type: "Text",
                                            path: "TodayDashboardPage.body[0].children[1].children[0].children[2].children[0].children[0].children[2].children[0].children[2]",
                                            name: "Text",
                                            text: "Voeding",
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_jgnv07ed",
                                    type: "Container",
                                    path: "TodayDashboardPage.body[0].children[1].children[0].children[2].children[0].children[0].children[3]",
                                    name: "Container",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Column_ugsyxfdl",
                                        type: "Column",
                                        path: "TodayDashboardPage.body[0].children[1].children[0].children[2].children[0].children[0].children[3].children[0]",
                                        name: "Column",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_jo8gwy5a",
                                            type: "Container",
                                            path: "TodayDashboardPage.body[0].children[1].children[0].children[2].children[0].children[0].children[3].children[0].children[0]",
                                            name: "Container",
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Icon_p8doyxxf",
                                            type: "Icon",
                                            path: "TodayDashboardPage.body[0].children[1].children[0].children[2].children[0].children[0].children[3].children[0].children[1]",
                                            name: "Icon",
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_dt4bwpmr",
                                            type: "Text",
                                            path: "TodayDashboardPage.body[0].children[1].children[0].children[2].children[0].children[0].children[3].children[0].children[2]",
                                            name: "Text",
                                            text: "Planning",
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_ovhk2yte",
                                    type: "Container",
                                    path: "TodayDashboardPage.body[0].children[1].children[0].children[2].children[0].children[0].children[4]",
                                    name: "Container",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Column_rkxbgwr4",
                                        type: "Column",
                                        path: "TodayDashboardPage.body[0].children[1].children[0].children[2].children[0].children[0].children[4].children[0]",
                                        name: "Column",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_yl8dpofk",
                                            type: "Container",
                                            path: "TodayDashboardPage.body[0].children[1].children[0].children[2].children[0].children[0].children[4].children[0].children[0]",
                                            name: "Container",
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Icon_hoi452u0",
                                            type: "Icon",
                                            path: "TodayDashboardPage.body[0].children[1].children[0].children[2].children[0].children[0].children[4].children[0].children[1]",
                                            name: "Icon",
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_asyg4iu5",
                                            type: "Text",
                                            path: "TodayDashboardPage.body[0].children[1].children[0].children[2].children[0].children[0].children[4].children[0].children[2]",
                                            name: "Text",
                                            text: "Profiel",
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}
