import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createHorseResidency} from '../../../apps/avaryn/src/horse-residency.js';
import {createActivityEditor} from '../../../apps/avaryn/src/activity-form.js';
import {createAuthorityTransfer} from '../../../apps/avaryn/src/authority-transfer.js';
import {browserDay} from '../../../apps/avaryn/src/browser-clock.js';
import {createAccountCore} from '../../../apps/avaryn/src/account-core.js';
import {createTeamCore,invitationToken} from '../../../apps/avaryn/src/team-core.js';
import {esc,icon} from '../../../apps/avaryn/src/components.js';

// Evaluate the complete production controller with injected I/O. No copied controller logic.
const controllerSource=readFileSync(new URL('../../../apps/avaryn/src/backend-controller.js',import.meta.url),'utf8');
const factorySource=controllerSource.replace(/^import .*;\n/gm,'').replace('export function createBackendController','function createBackendController');
const dependencyNames=['createHorseResidency','createActivityEditor','createAuthorityTransfer','browserDay','PRODUCT','createAccountCore','createTeamCore','createBackendClient','createFeedingEditor','renderTaskForm','renderAuth','consumeEmailCallback','taskToday','taskFormValues','renderLogin','loginPending','getPersona','canPlan','canCreateTask','canEditFeeding','esc','icon','INITIAL_STATE','initFacilities'];
const injectedFactory=new Function(...dependencyNames,`${factorySource}\nreturn createBackendController;`);
const tick=async()=>{for(let i=0;i<5;i++)await new Promise(resolve=>setImmediate(resolve));};
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};};
const decode=s=>String(s??'').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&');
function fixture(){return {today:'2026-09-11',selectedDay:'2026-09-11',route:'today',theme:'light',horses:[],activities:[],tasks:[],feeding:{},team:[{id:'profile-member',membershipId:'membership-1',rowVersion:4,roleCode:'groom',name:'<Member>',initials:'MM',role:'Groom'}],stableName:'Stal',backend:{connected:true,actor:{id:'actor-a'},organizationId:'org-a',organization:{id:'org-a',name:'Stal',row_version:3,primary_authority_profile_id:'profile-primary'},profile:{profile_id:'profile-a',row_version:7,first_name:'Voor',last_name:'Naam',locale:'nl-NL',time_zone:'Europe/Amsterdam',theme_mode:'dark',onboarding_completed_at:'2026-09-01',onboarding_intent:'individualHorse',avatar_object_path:'avatar/current'},capabilities:{canManage:true,canViewTeam:true},permissionCodes:{'organization.invitations.manage':true,'organization.memberships.manage':true,'organization.roles.manage':true},roles:[{code:'manager',name:'Beheerder'},{code:'groom',name:'Verzorger'}],invitations:[{id:'invite-1',status:'pending',row_version:2,recipient_label:'Ontvanger',role_name:'Groom',expires_at:'2026-09-18'}],organizations:[{id:'org-a',name:'Stal'},{id:'org-b',name:'Andere stal'}],todayDate:'2026-09-11',todayItems:[]}};}
function harness(t){
 let state=fixture(),form=null;const shown=[],toasts=[],calls=[],loads=[],stored=[],navigations=[];let rpcImpl=async()=>null,loadImpl=async()=>structuredClone(state),view=0;
 const modal={open:false,dataset:{viewId:'0'},contains:f=>modal.open&&form===f&&f.isConnected};
 const old=new Map(['document','FormData','localStorage','location','history'].map(k=>[k,Object.getOwnPropertyDescriptor(globalThis,k)]));
 const errorNode=()=>({textContent:'',append(text){this.textContent+=text;},setAttribute(){},scrollIntoView(){},insertAdjacentHTML(){}});
 function showModal(title,body='',buttons='',caption=''){
  if(form)form.isConnected=false;modal.open=true;modal.dataset.viewId=String(++view);shown.push({title,body,buttons,caption});
  const match=body.match(/<form\b([^>]*)>/);form=null;if(!match)return;
  const attrs=match[1],controls=[];const dataset={};for(const m of attrs.matchAll(/data-([\w-]+)="([^"]*)"/g))dataset[m[1].replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=decode(m[2]);
  for(const m of body.matchAll(/<(input|textarea|select)\b([^>]*)(?:>([\s\S]*?)<\/\1>|>)/g)){
   const name=m[2].match(/\bname="([^"]+)"/)?.[1];if(!name)continue;
   let value=m[2].match(/\bvalue="([^"]*)"/)?.[1]||'';
   if(m[1]==='textarea')value=m[3]||'';
   if(m[1]==='select'){const opts=[...(m[3]||'').matchAll(/<option([^>]*)>([^<]*)<\/option>/g)];const opt=opts.find(o=>/\bselected\b/.test(o[1]))||opts[0];value=opt?.[1].match(/value="([^"]*)"/)?.[1]??opt?.[2]??'';}
   controls.push({name,value:decode(value),tagName:m[1].toUpperCase(),disabled:/\bdisabled\b/.test(m[2]),type:m[2].match(/type="([^"]*)"/)?.[1]||'text'});
  }
  const submit={tagName:'BUTTON',type:'submit',disabled:false};controls.push(submit);let error=errorNode();
  form={getAttribute(name){return name==='id'?this.id:null;},id:attrs.match(/\bid="([^"]+)"/)?.[1],dataset,controls,isConnected:true,querySelector:q=>q==='.form-error'?error:q.includes('submit')?submit:controls.find(c=>q===`[name="${c.name}"]`)||null,querySelectorAll:()=>controls,prepend:e=>{error=e;},closest:q=>q==='#modal'?modal:null};
 }
 globalThis.document={querySelector:q=>q==='#modal'?modal:q==='#modal form'?form:null,getElementById:id=>id==='modal'?modal:form?.id===id?form:null,createElement:errorNode};
 // Native successful-control semantics: disabled values are absent on retries.
 globalThis.FormData=class{constructor(f){this.entries=f.controls.filter(c=>c.name&&!c.disabled).map(c=>[c.name,c.value]);}[Symbol.iterator](){return this.entries[Symbol.iterator]();}get(k){return this.entries.find(([name])=>name===k)?.[1]??null;}};
 globalThis.localStorage={getItem:()=>null,setItem:(k,v)=>stored.push([k,v]),removeItem(){}};
 globalThis.location={origin:'https://app.avaryn.example',pathname:'/',href:'https://app.avaryn.example/'};
 globalThis.history={state:null,replaceState:(...args)=>stored.push(['history',args])};
 const client={requestRpc:async(name,args,options)=>{calls.push({name,args,options});return rpcImpl(name,args,options);},load:async args=>{loads.push(args);return loadImpl(args);},logout:async()=>{}};
 const controller=injectedFactory(createHorseResidency,createActivityEditor,createAuthorityTransfer,browserDay,{demo:false,apiBase:'/api'},createAccountCore,createTeamCore,()=>client,()=>({handleAction:()=>false,handleSubmit:()=>false}),()=>'',()=>'',()=>null,s=>s.today,x=>x,()=>'',()=>'',s=>s.backend.actor,()=>true,()=>true,()=>true,esc,icon,{},()=>{})({getState:()=>state,setState:s=>{state=s;},render(){},save(){},navigate:route=>{navigations.push(route);state.route=route;modal.open=false;if(form)form.isConnected=false;},showModal,closeModal:()=>{modal.open=false;if(form)form.isConnected=false;},toast:text=>toasts.push(text)});
 t.after(()=>{for(const [key,desc] of old)if(desc)Object.defineProperty(globalThis,key,desc);else delete globalThis[key];});
 return {controller,shown,toasts,calls,loads,stored,navigations,modal,get state(){return state;},set state(s){state=s;},get form(){return form;},rpc:fn=>{rpcImpl=fn;},readback:fn=>{loadImpl=fn;},showModal,open:(action,data={})=>controller.handleAction(action,{dataset:data}),fill(values,f=form){for(const [k,v] of Object.entries(values)){const c=f.controls.find(c=>c.name===k);assert.ok(c,`rendered field ${k}`);c.value=v;}},async submit(f=form){controller.handleSubmit(f,{preventDefault(){}});await tick();},async settle(){await tick();}};
}

function horse(h){h.open('new-horse');h.fill({name:'  Eigen paard  ',officialName:'',birthDate:'',sex:'unknown',breed:'',discipline:'',level:'',notes:'Volledige notitie'});}
function profile(h){h.open('edit-profile');h.fill({firstName:' Nieuwe ',lastName:' Naam ',phone:'',intent:'individualHorse'});}
test('horse form uses canonical optional fields and exact 200-character official-name limit',async t=>{const h=harness(t);horse(h);assert.match(h.shown.at(-1).body,/name="officialName"[^>]*maxlength="200"/);h.rpc(async()=>[{horse_id:'horse-new'}]);await h.submit();const c=h.calls[0];assert.equal(c.name,'create_canonical_horse_profile');assert.equal(c.options.write,true);assert.equal(c.args.p_display_name,'Eigen paard');for(const key of ['p_official_name','p_birth_date','p_color','p_chip_number','p_passport_number','p_passport_valid_until'])assert.equal(c.args[key],null);assert.equal(c.args.p_notes,'Volledige notitie');assert.equal(h.loads.length,1);});
test('new horse navigates only after readback and selects server-returned horse',async t=>{const h=harness(t);horse(h);h.rpc(async()=>[{horse_id:'horse-new'}]);h.readback(async()=>({...structuredClone(h.state),horses:[{id:'horse-new'}]}));await h.submit();assert.equal(h.state.horseId,'horse-new');assert.deepEqual(h.navigations,['horse-overview']);});
for(const result of [null,[],{}])test(`horse missing acknowledgement ${JSON.stringify(result)} is uncertain, not success`,async t=>{const h=harness(t);horse(h);h.rpc(async()=>result);await h.submit();assert.equal(h.toasts.length,0);assert.equal(h.loads.length,0);assert.equal(h.form.dataset.uncertain,'true');});
test('unknown horse-write result retries same complete payload and request despite disabled native FormData',async t=>{const h=harness(t);horse(h);let count=0;h.rpc(async()=>{if(!count++)throw Object.assign(Error('Verbinding verbroken'),{uncertain:true});return [{horse_id:'horse-new'}];});await h.submit();const f=h.form;assert.equal(f.controls.find(c=>c.name==='name').disabled,true);await h.submit(f);assert.equal(h.calls.length,2);assert.deepEqual(h.calls[1],h.calls[0]);assert.equal(h.toasts.length,1);});
test('acknowledged horse write plus failed readback retries only readback',async t=>{const h=harness(t);horse(h);h.rpc(async()=>[{horse_id:'horse-new'}]);let count=0;h.readback(async()=>{if(!count++)throw Error('Readback offline');return structuredClone(h.state);});await h.submit();assert.equal(h.toasts.length,0);await h.submit();assert.equal(h.calls.length,1);assert.equal(h.loads.length,2);assert.equal(h.toasts.length,1);});
test('known server rejection restores input and a changed retry receives a fresh request ID',async t=>{const h=harness(t);horse(h);let count=0;h.rpc(async()=>{if(!count++)throw Object.assign(Error('Naam ongeldig'),{code:'22023'});return [{horse_id:'horse-new'}];});await h.submit();assert.equal(h.form.controls.find(c=>c.name==='name').disabled,false);assert.equal(h.form.dataset.requestId,undefined);h.fill({name:'Andere naam'});await h.submit();assert.notEqual(h.calls[0].args.p_correlation_id,h.calls[1].args.p_correlation_id);assert.equal(h.calls[1].args.p_display_name,'Andere naam');});
test('busy duplicate submission sends one write',async t=>{const h=harness(t);horse(h);const d=deferred();h.rpc(()=>d.promise);await h.submit();await h.submit();assert.equal(h.calls.length,1);d.resolve([{horse_id:'horse-new'}]);await h.settle();});
test('late horse acknowledgement after logout cannot reload, navigate, or report success',async t=>{const h=harness(t);horse(h);const d=deferred();h.rpc(()=>d.promise);await h.submit();h.open('logout');d.resolve([{horse_id:'horse-new'}]);await h.settle();assert.equal(h.loads.length,0);assert.equal(h.toasts.length,0);assert.equal(h.state.backend,undefined);});
test('late readback after logout cannot restore account or navigate',async t=>{const h=harness(t);horse(h);const saved=structuredClone(h.state),d=deferred();h.rpc(async()=>[{horse_id:'horse-new'}]);h.readback(()=>d.promise);await h.submit();h.open('logout');d.resolve(saved);await h.settle();assert.equal(h.state.backend,undefined);assert.equal(h.toasts.length,0);});
test('create stable uses canonical JSON acknowledgement and target organization readback',async t=>{const h=harness(t);h.open('create-stable');h.fill({name:' Nieuwe stal ',location:'Eigen locatie'});h.rpc(async()=>({organization_id:'org-new'}));await h.submit();assert.equal(h.calls[0].name,'create_c010_stable');assert.equal(h.calls[0].args.p_name,'Nieuwe stal');assert.equal(h.loads[0].organizationId,'org-new');assert.deepEqual(h.navigations,['stable']);});
test('stable edit passes captured row version, organization and actual editable fields',async t=>{const h=harness(t);h.open('manage-stable');h.fill({name:'Naam',location:'Locatie',address:'Straat',locality:'Plaats'});h.rpc(async()=>({organization_id:'org-a'}));await h.submit();const p=h.calls[0].args;assert.equal(p.p_organization_id,'org-a');assert.equal(p.p_expected_row_version,3);assert.equal(p.p_address_line,'Straat');assert.equal(p.p_locality,'Plaats');});
test('non-manager cannot open stable editing',t=>{const h=harness(t);h.state.backend.capabilities.canManage=false;h.open('manage-stable');assert.equal(h.form,null);});
test('profile save preserves server preferences and media path, trims names, completes onboarding',async t=>{const h=harness(t);profile(h);h.rpc(async()=>[{result_code:'updated',profile_id:'profile-a',row_version:8}]);await h.submit();const p=h.calls[0].args;assert.equal(h.calls[0].name,'update_current_account_profile');assert.equal(p.p_expected_row_version,7);assert.equal(p.p_first_name,'Nieuwe');assert.equal(p.p_last_name,'Naam');assert.equal(p.p_theme_mode,'dark');assert.equal(p.p_time_zone,'Europe/Amsterdam');assert.equal(p.p_avatar_object_path,'avatar/current');assert.equal(p.p_complete_onboarding,true);});
test('missing profile acknowledgement must not report successful save',async t=>{const h=harness(t);profile(h);h.rpc(async()=>null);await h.submit();assert.equal(h.toasts.length,0);assert.equal(h.form.dataset.uncertain,'true');});
test('old account form cannot write after actor changes',async t=>{const h=harness(t);profile(h);const old=h.form;h.state.backend={...h.state.backend,actor:{id:'actor-b'},profile:{...h.state.backend.profile,profile_id:'profile-b'}};h.rpc(async()=>[{result_code:'updated',profile_id:'profile-b',row_version:8}]);await h.submit(old);assert.equal(h.calls.length,0);});
test('old stable form cannot write its content to newly selected stable',async t=>{const h=harness(t);h.open('manage-stable');h.fill({name:'Stal A draft',location:'A',address:'',locality:''});const old=h.form;h.state.backend={...h.state.backend,organizationId:'org-b'};h.rpc(async()=>({organization_id:'org-b'}));await h.submit(old);assert.equal(h.calls.length,0);});
test('detached old form cannot execute another write after replacement',async t=>{const h=harness(t);horse(h);const old=h.form;h.open('edit-profile');h.rpc(async()=>[{horse_id:'horse-new'}]);await h.submit(old);assert.equal(h.calls.length,0);});
test('a stale profile form is rejected across a real logout and A-to-B-to-A session epoch',async t=>{const h=harness(t);profile(h);const old=h.form,saved=structuredClone(h.state);h.open('logout');h.state={...saved,backend:{...saved.backend,actor:{id:'actor-b'}}};h.open('edit-profile');h.open('logout');h.state=saved;h.open('edit-profile');h.rpc(async()=>[{result_code:'updated',profile_id:'profile-a',row_version:8}]);await h.submit(old);assert.equal(h.calls.length,0);});

test('canonical no_change profile acknowledgement at the same version is successful after readback',async t=>{const h=harness(t);h.open('edit-profile');h.rpc(async()=>[{result_code:'no_change',profile_id:'profile-a',row_version:7}]);await h.submit();assert.equal(h.loads.length,1);assert.deepEqual(h.toasts,['Je gegevens zijn opgeslagen.']);});
