import test from 'node:test';
import assert from 'node:assert/strict';
import {createActivityEditor} from '../../../apps/avaryn/src/activity-form.js';
import {createBackendClient} from '../../../apps/avaryn/src/backend-client.js';
const uid=n=>`10000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const A=uid(1),B=uid(2),H=uid(3),H2=uid(4),ITEM=uid(5),C=uid(6),DAY='2026-09-11';
const tick=()=>new Promise(r=>setImmediate(r));
const defer=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};};
const activity=()=>({id:ITEM,horseId:H,itemKind:'training',title:'Training',note:'Volledige bestaande instructie',date:DAY,time:'10:00',end:'11:00',endDate:'2026-09-12',rowVersion:7,participantProfileIds:[A,C]});
const state=()=>({route:'planning',selectedDay:DAY,today:DAY,horseId:H,horses:[{id:H,name:'Orion'},{id:H2,name:'Nova'}],activities:[activity()],backend:{connected:true,userId:A,actor:{id:A,name:'Own actor'},organizationId:null,capabilities:{canPlan:true},horseCapabilities:{[H]:{planning:true},[H2]:{planning:true}}}});
const candidates=(horse=H,manage=true)=>({horse_id:horse,can_manage:manage,candidates:manage?[{profile_id:B,profile_name:'Chosen participant'}]:[]});
const unescape=s=>s.replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&');
function fixture(t,{initial=state(),api,save,onAccessLost}={}){
 let current=initial,form=null,html='',view=0,closed=0;const reads=[],writes=[],errors=[],toasts=[],operations=[],accessLost=[];
 const previous={document:globalThis.document,FormData:globalThis.FormData},NativeFormData=globalThis.FormData;
 // Use native FormData storage/get/getAll semantics, including repeated checked
 // names and omission of the disabled existing-horse selector.
 globalThis.FormData=class{constructor(form){const data=new NativeFormData();for(const [key,value] of Object.entries(form.values)){if(key==='horseId'&&form.horseDisabled)continue;for(const v of Array.isArray(value)?value:[value])data.append(key,v);}return data;}};
 const modal={open:false,dataset:{viewId:''},contains:f=>f===form,querySelector:s=>s==='form'?form:null};
 globalThis.document={getElementById:id=>id==='modal'?modal:form?.id===id?form:null};
 t.after(()=>{globalThis.document=previous.document;globalThis.FormData=previous.FormData;});
 function disconnect(){if(form)form.isConnected=false;}
 function showModal(title,body){
  disconnect();html=body;modal.open=true;modal.dataset.viewId=String(++view);
  const f={id:body.match(/<form id="([^"]+)"/)?.[1]||'other',dataset:{},isConnected:true,values:{horseId:H,itemKind:'training'},listeners:{},horseDisabled:/name="horseId" disabled/.test(body),getAttribute:k=>k==='id'?f.id:null,addEventListener:(name,fn)=>{f.listeners[name]=fn;}};
  for(const m of body.matchAll(/<input name="([^"]+)" value="([^"]*)"/g))f.values[m[1]]=unescape(m[2]);
  f.values.note=unescape(body.match(/<textarea name="note"[^>]*>([\s\S]*?)<\/textarea>/)?.[1]||'');
  f.values.itemKind=body.match(/<option value="([^"]+)" selected>/g)?.map(v=>v.match(/value="([^"]+)"/)[1]).find(v=>!v.includes('-'))||'training';
  f.submit={disabled:true};f.box={_html:'',get innerHTML(){return this._html;},set innerHTML(value){this._html=value;f.values.participantProfileIds=[...value.matchAll(/name="participantProfileIds" value="([^"]+)" checked/g)].map(v=>v[1]);}};
  f.querySelector=s=>s==='[data-activity-participants]'?f.box:s==='button[type="submit"]'?f.submit:null;form=f;
 }
 const controller=createActivityEditor({getState:()=>current,showModal,closeModal(){closed++;modal.open=false;disconnect();},toast:v=>toasts.push(v),formError:(f,e)=>{errors.push(e);f.error=e;},onAccessLost:async error=>{accessLost.push(error);if(onAccessLost)await onAccessLost(error);},client:{requestRpc:async(name,params,options)=>{reads.push({name,params,options});return api?api(name,params):candidates(params.p_horse_id);},saveActivity:async(input,id)=>{writes.push({input:structuredClone(input),id});return save?save(input,id):{schedule_item_id:ITEM,row_version:8};}},perform(f,op,message,route){
  if(f.dataset.busy==='true')return;f.dataset.busy='true';f.dataset.requestId||=crypto.randomUUID();operations.push({op,message,route});
  Promise.resolve().then(()=>op(f.dataset.requestId,()=>true)).catch(error=>{errors.push(error);f.dataset.uncertain=error.uncertain?'true':'false';if(!error.uncertain)delete f.dataset.requestId;}).finally(()=>{f.dataset.busy='false';});
 }});
 return {controller,reads,writes,errors,toasts,operations,accessLost,modal,get form(){return form;},get html(){return html;},get closed(){return closed;},setState:s=>{current=s;},
  open(id){controller.handleAction(id?'edit-activity':'new-activity',{dataset:id?{id}:{}});return form;},
  submit(values={},f=form){Object.assign(f.values,values);let prevented=false;const handled=controller.handleSubmit(f,{preventDefault(){prevented=true;}});return {handled,prevented};},
  changeHorse(value){form.values.horseId=value;form.listeners.change({target:{name:'horseId',value}});},retry(){controller.handleAction('activity-retry-participants',{closest:()=>form});},dismiss(){modal.open=false;disconnect();},unrelated(){showModal('Other','<form id="other-form"></form>');}
 };
}
const valid={title:'Nieuw plan',date:DAY,time:'15:00',end:'16:00',endDate:DAY,itemKind:'training'};
test('new activity fetches exact scoped read-only candidates and never broad team membership',async t=>{const h=fixture(t);h.open();assert.equal(h.form.submit.disabled,true);await tick();assert.deepEqual(h.reads,[{name:'list_c010_horse_collaboration',params:{p_horse_id:H},options:{write:false}}]);assert.match(h.form.box.innerHTML,/Chosen participant/);assert.equal(h.form.submit.disabled,false);assert.equal(h.writes.length,0);});
test('native FormData repeated selections are retained in one explicit participant array',async t=>{const h=fixture(t);h.open();await tick();h.submit({...valid,participantProfileIds:[A,B]});await tick();assert.deepEqual(h.writes[0].input.participantProfileIds,[A,B]);assert.equal(h.operations[0].route,'planning');assert.match(h.writes[0].id,/^[\da-f-]{36}$/);});
test('editing preserves exact notes, participants, CAS, existing horse and multiday dates',async t=>{const h=fixture(t);h.open(ITEM);await tick();assert.match(h.html,/Volledige bestaande instructie/);assert.match(h.form.box.innerHTML,/Bestaande betrokkene/);assert.equal(h.form.horseDisabled,true);h.submit();await tick();const p=h.writes[0].input;assert.equal(p.horseId,H);assert.equal(p.note,activity().note);assert.deepEqual(p.participantProfileIds,[A,C]);assert.equal(p.rowVersion,7);assert.equal(p.id,ITEM);assert.equal(p.endDate,'2026-09-12');});
test('planning-only access can create for self but cannot infer new participants from team roles',async t=>{const s=state();s.team=[{id:B,name:'Not a candidate'}];s.functionProfiles={[A]:['manager']};const h=fixture(t,{initial:s,api:(_,p)=>candidates(p.p_horse_id,false)});h.open();await tick();assert.doesNotMatch(h.form.box.innerHTML,/Chosen|Not a candidate|checkbox/);h.submit({...valid,participantProfileIds:[B]});await tick();assert.deepEqual(h.writes[0].input.participantProfileIds,[A]);});
test('editing without candidate-management permission retains old participants despite missing checkbox values',async t=>{const h=fixture(t,{api:(_,p)=>candidates(p.p_horse_id,false)});h.open(ITEM);await tick();h.submit({participantProfileIds:[]});await tick();assert.deepEqual(h.writes[0].input.participantProfileIds,[A,C]);});
test('unchecked explicit selection sends empty list, allowing canonical self default',async t=>{const h=fixture(t);h.open();await tick();h.submit({...valid,participantProfileIds:[]});await tick();assert.deepEqual(h.writes[0].input.participantProfileIds,[]);});
test('forged participant UUID is rejected before mutation',async t=>{const h=fixture(t);h.open();await tick();h.submit({...valid,participantProfileIds:[uid(90)]});await tick();assert.equal(h.writes.length,0);assert.match(h.errors[0].message,/opgehaalde lijst/);});
for(const stateType of ['demo','no-right'])test(stateType+' cannot invoke candidates by function preference',async t=>{const s=state();s.functionProfiles={[A]:['manager','trainer']};if(stateType==='demo')s.backend.connected=false;else s.backend.horseCapabilities={};const h=fixture(t,{initial:s});h.open();await tick();assert.equal(h.reads.length,0);assert.equal(h.form,null);});
test('horse switch reloads candidates in place, retains note/date and drops old horse participant selection',async t=>{const h=fixture(t,{api:(_,p)=>({horse_id:p.p_horse_id,can_manage:true,candidates:[{profile_id:p.p_horse_id===H?B:C,profile_name:p.p_horse_id===H?'First':'Second'}]})});h.open();await tick();const form=h.form;Object.assign(form.values,{...valid,note:'Keep draft',participantProfileIds:[B]});h.changeHorse(H2);await tick();assert.equal(h.form,form);assert.equal(form.values.note,'Keep draft');assert.match(form.box.innerHTML,/Second/);assert.doesNotMatch(form.box.innerHTML,/First/);h.submit();await tick();assert.equal(h.writes[0].input.horseId,H2);assert.deepEqual(h.writes[0].input.participantProfileIds,[A]);});
test('slow previous-horse response cannot replace current candidates',async t=>{const gate=defer(),h=fixture(t,{api:(_,p)=>p.p_horse_id===H?gate.promise:candidates(H2)});h.open();h.changeHorse(H2);await tick();const html=h.form.box.innerHTML;gate.resolve({horse_id:H,can_manage:true,candidates:[{profile_id:C,profile_name:'Old private candidate'}]});await tick();assert.equal(h.form.box.innerHTML,html);assert.doesNotMatch(html,/Old private/);});
test('failed candidate read keeps draft and requires successful explicit retry',async t=>{let tries=0;const h=fixture(t,{api:(_,p)=>{if(tries++===0)throw Error('Synthetic unavailable');return candidates(p.p_horse_id);}});h.open();Object.assign(h.form.values,valid,{note:'Draft kept'});await tick();h.submit();assert.equal(h.writes.length,0);assert.equal(h.form.submit.disabled,true);h.retry();await tick();assert.equal(h.form.values.note,'Draft kept');assert.equal(h.form.submit.disabled,false);h.submit();await tick();assert.equal(h.writes[0].input.note,'Draft kept');});
test('authoritative candidate access loss closes sheet and delegates real context refresh',async t=>{const error=Object.assign(Error('Not available'),{status:403,accessLost:true});const h=fixture(t,{api:()=>{throw error;}});h.open();await tick();assert.equal(h.modal.open,false);assert.deepEqual(h.accessLost,[error]);assert.equal(h.writes.length,0);});
test('failed access-refresh hook is contained and cannot reopen the old private form',async t=>{const h=fixture(t,{api:()=>{throw Object.assign(Error('Denied'),{status:403});},onAccessLost:()=>{throw Error('Refresh unavailable');}});h.open();await tick();assert.equal(h.modal.open,false);assert.equal(h.writes.length,0);assert.match(h.toasts.at(-1),/Meld je opnieuw aan/);});
test('mismatched candidate horse fails closed without displaying names',async t=>{const h=fixture(t,{api:()=>({horse_id:H2,can_manage:true,candidates:[{profile_id:B,profile_name:'Foreign private'}]})});h.open();await tick();assert.equal(h.form.submit.disabled,true);assert.doesNotMatch(h.form.box.innerHTML,/Foreign private/);h.submit(valid);assert.equal(h.writes.length,0);});
for(const change of ['actor','day','organization','timezone'])test(change+' change invalidates old form and late candidate result',async t=>{const gate=defer(),h=fixture(t,{api:()=>gate.promise});const form=h.open();const s=state();if(change==='actor')s.backend.actor.id=B;else if(change==='day')s.selectedDay='2026-09-12';else if(change==='timezone')s.backend.calendar={time_zone:'America/Los_Angeles'};else s.backend.organizationId=uid(20);h.setState(s);h.controller.syncContext();assert.equal(h.modal.open,false);gate.resolve(candidates());await tick();h.submit(valid,form);assert.equal(h.writes.length,0);});
test('A→B→A closes old form and cannot resurrect lookup',async t=>{const gate=defer(),h=fixture(t,{api:()=>gate.promise});const form=h.open(),b=state();b.backend.actor.id=B;h.setState(b);h.controller.syncContext();h.setState(state());h.controller.syncContext();gate.resolve(candidates());await tick();h.submit(valid,form);assert.equal(h.writes.length,0);assert.equal(h.modal.open,false);});
test('dismissed/replaced modal is not overwritten by candidate callback',async t=>{const gate=defer(),h=fixture(t,{api:()=>gate.promise});h.open();h.unrelated();const html=h.html;gate.resolve(candidates());await tick();assert.equal(h.html,html);assert.equal(h.form.id,'other-form');});
test('duplicate submit is serialized by existing perform contract',async t=>{const gate=defer(),h=fixture(t,{save:()=>gate.promise});h.open();await tick();h.submit(valid);h.submit(valid);await tick();assert.equal(h.writes.length,1);gate.resolve();await tick();});
test('uncertain retry keeps same payload/request including disabled checkbox values',async t=>{let tries=0;const h=fixture(t,{save:()=>{if(tries++===0)throw Object.assign(Error('Synthetic timeout'),{uncertain:true});}});h.open();await tick();h.submit({...valid,note:'Original',participantProfileIds:[B]});await tick();h.submit({note:'Changed',participantProfileIds:[]});await tick();assert.deepEqual(h.writes[0],h.writes[1]);});
test('known CAS failure allows deliberate corrected payload and fresh request ID',async t=>{let tries=0;const h=fixture(t,{save:()=>{if(tries++===0)throw Object.assign(Error('Version conflict'),{status:409,code:'STALE_SCHEDULE_VERSION'});}});h.open(ITEM);await tick();h.submit();await tick();h.submit({note:'Changed'});await tick();assert.notEqual(h.writes[0].id,h.writes[1].id);assert.equal(h.writes[1].input.note,'Changed');assert.equal(h.writes[1].input.rowVersion,7);});
test('SQL participant rejection passes unchanged to authoritative generic error gate',async t=>{const error=Object.assign(Error('Denied'),{code:'SCHEDULE_PARTICIPANT_NOT_ALLOWED',status:403,accessLost:true});const h=fixture(t,{save:()=>{throw error;}});h.open();await tick();h.submit({...valid,participantProfileIds:[B]});await tick();assert.equal(h.errors.at(-1),error);});
test('invalid dates and reversed interval are refused; optional empty end is preserved',async t=>{const h=fixture(t);h.open();await tick();h.submit({...valid,date:'2026-02-30'});h.submit({...valid,end:'14:00'});assert.equal(h.writes.length,0);h.submit({...valid,end:''});await tick();assert.equal(h.writes[0].input.end,'');});
test('candidate names, horse names, title and note are HTML escaped',async t=>{const s=state();s.horses[0].name='<img src=x>';s.activities[0].note='</textarea><script>x</script>';s.activities[0].title='" onfocus="x';const h=fixture(t,{initial:s,api:(_,p)=>({horse_id:p.p_horse_id,can_manage:true,candidates:[{profile_id:B,profile_name:'<img src=y>'}]})});h.open(ITEM);await tick();assert.doesNotMatch(h.html,/<script>|<img/);assert.doesNotMatch(h.form.box.innerHTML,/<img/);assert.match(h.form.box.innerHTML,/&lt;img/);});
test('real client preserves exact instants/CAS and serializes explicit participants to canonical upsert',async()=>{
 const calls=[],memory=new Map(),old=activity();
 const client=createBackendClient({storage:{getItem:k=>memory.get(k),setItem:(k,v)=>memory.set(k,v),removeItem:k=>memory.delete(k)},fetchImpl:async(path,options)=>{
  const body=options.body?JSON.parse(options.body):null;calls.push({path,body});
  if(path.includes('grant_type=password'))return Response.json({access_token:'synthetic-access',refresh_token:'synthetic-refresh',expires_at:Date.now()/1000+3600,user:{id:A}});
  const n=path.split('/').at(-1),map={get_current_account_profile:[{profile_id:A,profile_status:'active',display_name:'Actor'}],get_c010_personal_day:{on_date:DAY,calendar:{today_date:DAY},items:[]},list_c010_stables:[],list_c010_horses:[{horse_id:H,display_name:'Horse',lifecycle_status:'active',can_edit:true,can_manage_planning:true}],get_canonical_horse_workspace:{},get_canonical_horse_feeding:{plans:[]},list_c010_horse_schedule:[{schedule_item_id:ITEM,horse_id:H,item_kind:'training',title:old.title,instruction:old.note,state:'planned',row_version:7,scheduled_start_at:DAY+'T08:00:14.321Z',scheduled_end_at:'2026-09-12T09:00:14.321Z',participant_profile_ids:[A,C]}]};
  return Response.json(n==='upsert_c010_horse_schedule_item'?{schedule_item_id:ITEM,row_version:8}:map[n]);
 }});
 await client.login('synthetic@example.invalid','synthetic');await client.load();await client.saveActivity({...old,participantProfileIds:[A,B]},uid(50));const p=calls.at(-1).body;
 assert.deepEqual(p.p_participant_profile_ids,[A,B]);assert.equal(p.p_expected_row_version,7);assert.equal(p.p_instruction,old.note);assert.equal(p.p_scheduled_start_at,DAY+'T08:00:14.321Z');assert.equal(p.p_scheduled_end_at,'2026-09-12T09:00:14.321Z');assert.equal(p.p_request_id,uid(50));assert.equal(Object.hasOwn(p,'p_actor_id'),false);
});
