import test from 'node:test';
import assert from 'node:assert/strict';
import {createHorseResidency} from '../../../apps/avaryn/src/horse-residency.js';

// Actual controller/render functions; only DOM, the shared perform gate and RPC
// I/O are injected. Every asserted mutation executes the production callback.
const id=n=>`10000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const A=id(1),B=id(2),H=id(3),R=id(4),O=id(5),OTHER=id(6),BOX=id(7),BUSY=id(8),RID=id(9);
const decode=s=>String(s??'').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&');
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};};
function fixture(){return {horseId:H,route:'horse-overview',today:'2026-09-11',horses:[{id:H,name:'Eigen <paard>',rowVersion:97,lifecycleStatus:'active'}],functionProfiles:{[A]:['owner','manager']},backend:{connected:true,actor:{id:A,roleKind:'manager'},organizationId:O,organizations:[{id:O,name:'Eigen stal'},{id:OTHER,name:'Andere stal'}],capabilities:{canManage:true},permissionCodes:{'organization.residencies.manage':true}}};}
const collaboration=()=>({horse_id:H,can_manage:true,current_residency:{id:R,organization_id:O,organization_name:'Stal <A>',location_name:'Eigen locatie',row_version:4},stable_options:[{organization_id:O,name:'Stal <A>',location_name:'Eigen locatie'},{organization_id:OTHER,name:'Andere "stal"',location_name:''}]});
const places=()=>({profile_id:A,organization_id:O,resources:[{id:BOX,kind:'stall',name:'Box <1>',status:'available',occupied:false},{id:BUSY,kind:'stall',name:'Bezet',status:'available',occupied:true}],placements:[{resourceId:BUSY,horseId:null,note:'',redacted:true}],placementVersions:{[H]:7}});
function harness(t){
 let state=fixture(),form=null,view=0,collab=collaboration(),workspace=places(),write=async()=>null,custom=null;
 const calls=[],shown=[],operations=[],toasts=[];
 const modal={open:false,dataset:{viewId:'0'},contains:f=>modal.open&&f===form&&f.isConnected};
 const descriptors=new Map(['document','FormData'].map(k=>[k,Object.getOwnPropertyDescriptor(globalThis,k)]));
 function showModal(title,body='',buttons='',caption=''){
  if(form)form.isConnected=false;modal.open=true;modal.dataset.viewId=String(++view);shown.push({title,body,buttons,caption});form=null;
  const match=body.match(/<form\b([^>]*)>/);if(!match)return;
  const controls=[];
  for(const m of body.matchAll(/<(input|textarea|select)\b([^>]*)(?:>([\s\S]*?)<\/\1>|>)/g)){
   const name=m[2].match(/\bname="([^"]+)"/)?.[1];if(!name)continue;let value=m[2].match(/\bvalue="([^"]*)"/)?.[1]||'';
   if(m[1]==='textarea')value=m[3]||'';
   if(m[1]==='select'){const opts=[...(m[3]||'').matchAll(/<option([^>]*)>([^<]*)<\/option>/g)],o=opts.find(o=>/\bselected\b/.test(o[1]))||opts[0];value=o?.[1].match(/value="([^"]*)"/)?.[1]??o?.[2]??'';}
   controls.push({name,value:decode(value),disabled:false});
  }
  let error=null;
  form={id:match[1].match(/id="([^"]+)"/)[1],dataset:{},controls,isConnected:true,querySelector:q=>q==='.form-error'?error:controls.find(c=>q===`[name="${c.name}"]`)||null,prepend:e=>{error=e;}};
 }
 globalThis.document={querySelector:q=>q==='#modal'?modal:q==='#modal form'?form:null,getElementById:which=>form?.id===which?form:null,createElement:()=>({textContent:'',setAttribute(){},scrollIntoView(){}})};
 globalThis.FormData=class{constructor(f){this.values=f.controls.filter(c=>!c.disabled).map(c=>[c.name,c.value]);}[Symbol.iterator](){return this.values[Symbol.iterator]();}};
 const apiRequest=async(name,args,options)=>{calls.push({name,args:structuredClone(args),options});if(custom)return custom(name,args,options);if(options.write)return write(name,args);return structuredClone(name==='list_c010_horse_collaboration'?collab:workspace);};
 const controller=createHorseResidency({getState:()=>state,showModal,apiRequest,toast:s=>toasts.push(s),perform:(form,operation,success,route)=>operations.push({form,operation,success,route})});
 t.after(()=>{for(const [k,d] of descriptors)if(d)Object.defineProperty(globalThis,k,d);else delete globalThis[k];});
 return {controller,calls,shown,operations,toasts,modal,showModal,get state(){return state;},set state(v){state=v;},get form(){return form;},get collaboration(){return collab;},set collaboration(v){collab=v;},get workspace(){return workspace;},set workspace(v){workspace=v;},write:fn=>{write=fn;},request:fn=>{custom=fn;},open:placement=>controller.open(H,placement),
  fill(values,f=form){for(const [name,value] of Object.entries(values)){const c=f.controls.find(c=>c.name===name);assert.ok(c,`rendered ${name}`);c.value=value;}},
  submit(f=form){return controller.handleSubmit(f,{preventDefault(){}});},run:(requestId=RID,isCurrent=()=>true)=>operations.at(-1).operation(requestId,isCurrent),get writes(){return calls.filter(c=>c.options.write);}};
}
function acceptResidency(h){h.write(async(name,p)=>{assert.equal(name,'set_c010_horse_residency');h.collaboration.current_residency=p.p_stable_organization_id?{id:id(20),organization_id:p.p_stable_organization_id,organization_name:'Andere stal',row_version:1}:null;return {horse_id:H,residency_id:p.p_stable_organization_id?id(20):null,organization_id:p.p_stable_organization_id,row_version:p.p_stable_organization_id?1:undefined,status:p.p_stable_organization_id?'active':'unlinked'};});}
function acceptPlace(h){h.write(async(name,p)=>{assert.equal(name,'set_c010_horse_place');const row_version=(p.p_expected_row_version||0)+1;h.workspace.placementVersions[H]=row_version;h.workspace.placements=h.workspace.placements.filter(p=>p.horseId!==H);if(p.p_stable_place_id)h.workspace.placements.push({horseId:H,resourceId:p.p_stable_place_id,rowVersion:row_version,note:p.p_note,redacted:false});return {horse_id:H,resource_id:p.p_stable_place_id,row_version,status:p.p_stable_place_id?'active':'ended'};});}

test('disconnected or unknown horse entry performs no read and shows no private modal',async t=>{const h=harness(t);h.state.backend.connected=false;await h.open();assert.equal(h.calls.length,0);h.state.backend.connected=true;await h.controller.open(id(99));assert.equal(h.shown.length,0);});
test('residency uses fresh server options and escapes names, attributes and location',async t=>{const h=harness(t);h.collaboration.stable_options[0].location_name='<script>x</script>';await h.open();assert.equal(h.calls[0].name,'list_c010_horse_collaboration');assert.deepEqual(h.calls[0].args,{p_horse_id:H});const html=h.shown.at(-1).body;assert.match(html,/Eigen &lt;paard&gt;/);assert.match(html,/&lt;script&gt;/);assert.match(html,/Andere &quot;stal&quot;/);assert.doesNotMatch(html,/<script>/);});
test('personal owner can select residency without organization management',async t=>{const h=harness(t);h.state.backend.organizationId=null;h.state.backend.permissionCodes={};h.state.backend.capabilities.canManage=false;await h.open();assert.equal(h.form.id,'core-residency-form');assert.doesNotMatch(h.shown.at(-1).body,/data-action="horse-placement"/);});
test('manager preference never overrides server horse management refusal',async t=>{const h=harness(t);h.collaboration.can_manage=false;await h.open();assert.equal(h.form,null);assert.match(h.shown.at(-1).body,/paardbeheerder/);assert.equal(h.writes.length,0);});
test('no accessible stable produces honest empty guidance and no fabricated option',async t=>{const h=harness(t);h.collaboration.stable_options=[];h.collaboration.current_residency=null;await h.open();assert.match(h.shown.at(-1).body,/geen andere toegankelijke stallen/);assert.equal((h.shown.at(-1).body.match(/<option /g)||[]).length,1);h.submit();assert.equal(h.operations.length,0);});
test('closed/replaced modal ignores a late successful residency read',async t=>{const h=harness(t),d=deferred();h.request(()=>d.promise);const p=h.open();h.showModal('Nieuw scherm','Geen formulier');d.resolve(collaboration());await p;assert.equal(h.shown.at(-1).title,'Nieuw scherm');assert.equal(h.form,null);});
test('late rejected read does not replace a newer modal',async t=>{const h=harness(t),d=deferred();h.request(()=>d.promise);const p=h.open();h.showModal('Ander scherm');d.reject(Error('secret debug text'));await p;assert.equal(h.shown.at(-1).title,'Ander scherm');assert.equal(JSON.stringify(h.shown).includes('secret debug text'),false);});
test('actor change in place invalidates pending read',async t=>{const h=harness(t),d=deferred();h.request(()=>d.promise);const p=h.open();h.state.backend.actor.id=B;d.resolve(collaboration());await p;assert.equal(h.form,null);});
test('A to B to A with new backend objects never revives pending read',async t=>{const h=harness(t),d=deferred();h.request(()=>d.promise);const p=h.open();h.state.backend={...h.state.backend,actor:{id:B}};h.state.backend={...h.state.backend,actor:{id:A}};d.resolve(collaboration());await p;assert.equal(h.form,null);});
test('collaboration response for another horse is rejected',async t=>{const h=harness(t);h.collaboration.horse_id=id(99);await h.open();assert.equal(h.form,null);assert.equal(h.shown.at(-1).title,'Gegevens niet geladen');});
test('existing residency outside current options stays selected and cannot silently unlink',async t=>{const h=harness(t);h.collaboration.stable_options=[];await h.open();assert.equal(h.form.controls[0].value,O);h.submit();assert.equal(h.operations.length,0);assert.match(h.form.querySelector('.form-error').textContent,/al de huidige/);});
test('residency saves only canonical residency CAS and request ID, then checks exact readback',async t=>{const h=harness(t);await h.open();h.fill({organizationId:OTHER});h.submit();acceptResidency(h);await h.run();assert.deepEqual(h.writes[0].args,{p_horse_id:H,p_stable_organization_id:OTHER,p_expected_residency_row_version:4,p_request_id:RID});assert.equal(h.form.dataset.resultHorseId,H);assert.deepEqual(h.calls.map(c=>c.name),['list_c010_horse_collaboration','set_c010_horse_residency','list_c010_horse_collaboration']);assert.equal(h.state.backend.organizationId,O);});
test('new horse residency sends null CAS, never horse profile row version',async t=>{const h=harness(t);h.collaboration.current_residency=null;await h.open();h.fill({organizationId:O});h.submit();acceptResidency(h);await h.run();assert.equal(h.writes[0].args.p_expected_residency_row_version,null);assert.equal(h.state.horses[0].rowVersion,97);});
test('unlink requires unlinked acknowledgement and no residency after readback',async t=>{const h=harness(t);await h.open();h.fill({organizationId:''});h.submit();acceptResidency(h);await h.run();assert.equal(h.writes[0].args.p_stable_organization_id,null);assert.equal(h.collaboration.current_residency,null);});
test('unknown destination cannot bypass the server-provided selection list',async t=>{const h=harness(t);await h.open();h.fill({organizationId:id(99)});h.submit();assert.equal(h.operations.length,0);assert.match(h.form.querySelector('.form-error').textContent,/uit de lijst/);});
for(const bad of [null,{horse_id:H,residency_id:R,organization_id:O,status:'active',row_version:5},{horse_id:H,residency_id:R,organization_id:OTHER,status:'active',row_version:0}])test(`missing/mismatched residency acknowledgement is uncertain: ${JSON.stringify(bad)}`,async t=>{const h=harness(t);await h.open();h.fill({organizationId:OTHER});h.submit();h.write(async()=>bad);await assert.rejects(h.run(),e=>e.uncertain===true);assert.equal(h.form.dataset.resultHorseId,undefined);});
test('acknowledgement without matching persisted residency cannot claim success',async t=>{const h=harness(t);await h.open();h.fill({organizationId:OTHER});h.submit();h.write(async()=>({horse_id:H,residency_id:id(20),organization_id:OTHER,status:'active',row_version:1}));await assert.rejects(h.run(),e=>e.uncertain===true);assert.equal(h.form.dataset.resultHorseId,undefined);});
test('known acknowledged write plus failed readback retries only the read with original draft',async t=>{const h=harness(t);await h.open();h.fill({organizationId:OTHER});h.submit();let n=0;h.request(async(name,args,options)=>{if(options.write)return {horse_id:H,residency_id:id(20),organization_id:OTHER,status:'active',row_version:1};if(++n===1)throw Error('network');return {...collaboration(),current_residency:{id:id(20),organization_id:OTHER,row_version:1}};});await assert.rejects(h.run(),e=>e.uncertain===true);h.form.dataset.uncertain='true';h.fill({organizationId:''});h.form.controls.forEach(c=>c.disabled=true);h.submit();await h.run();assert.equal(h.writes.length,1);assert.equal(h.form.dataset.resultHorseId,H);});
test('unknown write result preserves original payload on same-ID retry despite disabled controls',async t=>{const h=harness(t);await h.open();h.fill({organizationId:OTHER});h.submit();h.write(async()=>{throw Object.assign(Error('timeout'),{uncertain:true});});await assert.rejects(h.run());h.form.dataset.uncertain='true';h.fill({organizationId:''});h.form.controls.forEach(c=>c.disabled=true);h.submit();acceptResidency(h);await h.run();assert.deepEqual(h.writes[0].args,h.writes[1].args);});
test('detached form and changed stable cannot submit',async t=>{const h=harness(t);await h.open();const old=h.form;h.showModal('Ander formulier');h.submit(old);assert.equal(h.operations.length,0);await h.open();h.state.backend.organizationId=OTHER;h.submit();assert.equal(h.operations.length,0);});
test('late write after account replacement cannot publish horse selection or read old account',async t=>{const h=harness(t);await h.open();h.fill({organizationId:OTHER});h.submit();const d=deferred();h.write(()=>d.promise);const p=h.run();h.state.backend={...h.state.backend,actor:{id:B}};d.resolve({horse_id:H,residency_id:id(20),organization_id:OTHER,status:'active',row_version:1});await assert.rejects(p,e=>e.code==='STALE_CONTEXT');assert.equal(h.form.dataset.resultHorseId,undefined);assert.equal(h.calls.length,2);});
test('placement requires actual place permission even with manager function or persona',async t=>{const h=harness(t);h.state.backend.permissionCodes={};await h.open(true);assert.equal(h.form,null);assert.equal(h.calls.length,1);assert.match(h.shown.at(-1).body,/stalbeheerder/);});
test('separate place permission works without horse.manage or generic organization.edit',async t=>{const h=harness(t);h.collaboration.can_manage=false;h.state.backend.capabilities.canManage=false;await h.open(true);assert.equal(h.form.id,'core-horse-place-form');assert.equal(h.calls[1].name,'get_c010_facility_workspace');});
test('placement first needs residency and never silently creates one',async t=>{const h=harness(t);h.collaboration.current_residency=null;await h.open(true);assert.equal(h.form,null);assert.match(h.shown.at(-1).buttons,/data-action="horse-residency"/);assert.equal(h.writes.length,0);});
test('different selected stable offers existing scope switch without reading wrong workspace',async t=>{const h=harness(t);h.collaboration.current_residency.organization_id=OTHER;await h.open(true);assert.equal(h.calls.length,1);assert.match(h.shown.at(-1).buttons,new RegExp(`data-id="${OTHER}"`));});
test('placement filters occupied/redacted/non-box/unavailable resources and requires deliberate choice',async t=>{const h=harness(t);h.workspace.resources.push({id:id(21),kind:'arena',name:'Rijbak',status:'available'},{id:id(22),kind:'stall',name:'Onderhoud',status:'maintenance'},{id:id(23),kind:'stall',name:'Redactie',status:'available',occupied:false});h.workspace.placements.push({resourceId:id(23),horseId:null,redacted:true});await h.open(true);const body=h.shown.at(-1).body;assert.match(body,/Box &lt;1&gt;/);for(const name of ['Bezet','Rijbak','Onderhoud','Redactie'])assert.equal(body.includes(`>${name}</option>`),false);assert.equal(h.form.controls[0].value,'');h.submit();assert.equal(h.operations.length,0);});
test('new placement uses authoritative ended-placement version plus full note and exact readback',async t=>{const h=harness(t);await h.open(true);h.fill({resourceId:BOX,note:'Volledige instructie\nTweede regel'});h.submit();acceptPlace(h);await h.run();assert.deepEqual(h.writes[0].args,{p_organization_id:O,p_horse_id:H,p_stable_place_id:BOX,p_expected_row_version:7,p_note:'Volledige instructie\nTweede regel',p_request_id:RID});assert.equal(h.workspace.placementVersions[H],8);});
test('first placement sends null when no prior horse placement exists',async t=>{const h=harness(t);h.workspace.placementVersions={};await h.open(true);h.fill({resourceId:BOX,note:''});h.submit();acceptPlace(h);await h.run();assert.equal(h.writes[0].args.p_expected_row_version,null);});
test('forged occupied selection or revoked place capability cannot invoke mutation',async t=>{const h=harness(t);await h.open(true);h.fill({resourceId:BUSY});h.submit();assert.equal(h.operations.length,0);h.fill({resourceId:BOX});h.state.backend.permissionCodes={};h.submit();assert.equal(h.operations.length,0);});
test('existing own occupied box remains selectable; note is escaped and full',async t=>{const h=harness(t);h.workspace.resources[0].occupied=true;h.workspace.placements.push({horseId:H,resourceId:BOX,rowVersion:7,note:'<instructie>\nRegel twee'});await h.open(true);assert.equal(h.form.controls[0].value,BOX);assert.match(h.shown.at(-1).body,/&lt;instructie&gt;\nRegel twee/);});
test('freeing own box uses ended state and preserves residency',async t=>{const h=harness(t);h.workspace.placements.push({horseId:H,resourceId:BOX,rowVersion:7,note:'Oud'});await h.open(true);assert.doesNotMatch(h.shown.at(-1).body,/<select name="resourceId" required/);h.fill({resourceId:'',note:''});h.submit();acceptPlace(h);await h.run();assert.equal(h.writes[0].args.p_stable_place_id,null);assert.equal(h.collaboration.current_residency.id,R);});
test('unavailable current box is not silently freed by default form value',async t=>{const h=harness(t);h.workspace.resources[0].status='maintenance';h.workspace.placements.push({horseId:H,resourceId:BOX,rowVersion:7,note:'Oud'});await h.open(true);assert.equal(h.form.controls[0].value,BOX);h.submit();assert.equal(h.operations.length,0);});
test('wrong destination/status/version in placement acknowledgement is uncertain',async t=>{const h=harness(t);await h.open(true);h.fill({resourceId:BOX});h.submit();h.write(async()=>({horse_id:H,resource_id:BUSY,row_version:8,status:'active'}));await assert.rejects(h.run(),e=>e.uncertain===true);});
test('placement readback must retain full instruction, not merely horse ID',async t=>{const h=harness(t);await h.open(true);h.fill({resourceId:BOX,note:'Exacte tekst'});h.submit();h.write(async()=>{h.workspace.placementVersions[H]=8;h.workspace.placements.push({horseId:H,resourceId:BOX,rowVersion:8,note:'Verkeerde tekst'});return {horse_id:H,resource_id:BOX,row_version:8,status:'active'};});await assert.rejects(h.run(),e=>e.uncertain===true);assert.equal(h.form.dataset.resultHorseId,undefined);});
test('workspace identity mismatch cannot reveal or edit another actor/stable view',async t=>{const h=harness(t);h.workspace.profile_id=B;await h.open(true);assert.equal(h.form,null);assert.equal(h.shown.at(-1).title,'Gegevens niet geladen');});
test('no free box reports empty state without inventing a place',async t=>{const h=harness(t);h.workspace.resources=[];await h.open(true);assert.equal(h.form,null);assert.match(h.shown.at(-1).body,/geen beschikbare stalplaats/);});
