import test from 'node:test';
import assert from 'node:assert/strict';
import {createPilotWorker,isPublishableKey,limitedBytes,PILOT_PROJECT,PILOT_UPSTREAM,NATIVE_ORIGINS} from '../../../apps/avaryn/server/worker.js';
import routes from '../../../apps/avaryn/config/rpc-routes.json' with {type:'json'};
import release from '../../../apps/avaryn/config/release.json' with {type:'json'};
import capacitor from '../../../apps/avaryn/capacitor.config.json' with {type:'json'};

const ORIGIN='https://alpha.avaryn.example',KEY='sb_publishable_synthetic_only_unit_test_1234',JWT='Bearer synthetic.user.jwt';
const ID='10000000-0000-4000-8000-000000000001',ID2='10000000-0000-4000-8000-000000000002';
const json=(body,status=200,headers={})=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json',...headers}});
const legacy=payload=>'eyJhbGciOiJIUzI1NiJ9.'+Buffer.from(JSON.stringify(payload)).toString('base64url')+'.synthetic';
const media=(kind='sign',variant='original')=>`/api/storage/v1/object/${kind}/horse-media/canonical/${ID}/${ID2}/${variant}?token=synthetic.signed.token`;
function harness(options={}){
 const upstream=[],assets=[];
 const env={APP_ORIGIN:ORIGIN,SUPABASE_PUBLISHABLE_KEY:KEY,ASSETS:{fetch:async r=>{assets.push(r);return new Response('<html>AVARYN</html>',{headers:{'content-type':'text/html','cache-control':'public, max-age=999','set-cookie':'static-cookie=not-forwarded'}});}}};
 const worker=createPilotWorker({fetchImpl:async(url,init)=>{upstream.push({url,init});return options.upstream?options.upstream(url,init):json({ok:true});},timeoutMs:options.timeoutMs||20000});
 const request=(path,options={})=>{
  const {method='POST',headers={},body,origin=ORIGIN,auth=JWT}=options;
  const h=new Headers(headers);if(origin!==null)h.set('origin',origin);if(auth!==null)h.set('authorization',auth);
  if(!h.has('content-type'))h.set('content-type','application/json');
  return new Request(ORIGIN+path,{method,headers:h,body:['GET','HEAD'].includes(method)?undefined:body??'{}',...((body instanceof ReadableStream)?{duplex:'half'}:{})});
 };
 return {worker,env,upstream,assets,request,call:(path,options)=>worker.fetch(request(path,options),env)};
}
async function expectCode(response,status,code){assert.equal(response.status,status);assert.equal((await response.json()).code,code);assert.equal(response.headers.get('cache-control'),'no-store');}

test('runtime binds build candidate to fixed managed pilot and exposes no runtime key',async()=>{
 const h=harness(),r=await h.call('/runtime.json',{method:'GET',auth:null,origin:null});const body=await r.json();assert.deepEqual(body,{candidate:release.candidate,backendProject:PILOT_PROJECT,localOnly:false});assert.equal(JSON.stringify(body).includes(KEY),false);assert.equal(h.upstream.length,0);
});
test('runtime HEAD is bodyless and private-cache-safe',async()=>{const h=harness(),r=await h.call('/runtime.json',{method:'HEAD',auth:null});assert.equal(await r.text(),'');assert.equal(r.status,200);assert.equal(r.headers.get('cache-control'),'no-store');});
test('release version metadata matches product configuration, never synthetic account hints',async()=>{const h=harness(),r=await h.call('/version.json',{method:'GET',auth:null});assert.deepEqual(await r.json(),{...release,apiBase:'/api',demo:false});});
test('public app shell is available without preview identity or Supabase session',async()=>{const h=harness(),r=await h.call('/',{method:'GET',auth:null,origin:null});assert.equal(r.status,200);assert.equal(h.assets.length,1);assert.equal(r.headers.get('set-cookie'),null);assert.equal(r.headers.get('cache-control'),'no-store');assert.match(r.headers.get('content-security-policy'),/frame-ancestors 'none'/);});
test('missing or foreign APP_ORIGIN fails closed instead of trusting Host or forwarded host',async()=>{for(const value of [undefined,'*','http://alpha.avaryn.example','https://alpha.avaryn.example/','https://localhost','https://alpha.avaryn.example:8443','https://alpha.avaryn.example/path']){const h=harness();h.env.APP_ORIGIN=value;await expectCode(await h.call('/runtime.json',{method:'GET'}),503,'PILOT_CONFIGURATION_REQUIRED');assert.equal(h.upstream.length,0);}});
test('publishable and pilot anon keys are supported, privileged/foreign keys refused',()=>{
 assert.equal(isPublishableKey(KEY),true);assert.equal(isPublishableKey(legacy({role:'anon',ref:PILOT_PROJECT})),true);
 for(const value of [null,'sb_secret_synthetic_only_123456',legacy({role:'service_role',ref:PILOT_PROJECT}),legacy({role:'authenticated',ref:PILOT_PROJECT}),legacy({role:'anon',ref:'otherproject'}),'opaque','bad\nheader'])assert.equal(isPublishableKey(value),false);
});
test('service-role misconfiguration cannot reach even the app-shell binding',async()=>{const h=harness();h.env.SUPABASE_PUBLISHABLE_KEY=legacy({role:'service_role',ref:PILOT_PROJECT});await expectCode(await h.call('/',{method:'GET'}),503,'PILOT_CONFIGURATION_REQUIRED');assert.equal(h.assets.length,0);});
test('foreign URL host and spoofed Host are rejected before fetching',async()=>{const h=harness();await expectCode(await h.worker.fetch(new Request('https://foreign.example/runtime.json'),h.env),403,'HOST_REFUSED');await expectCode(await h.call('/runtime.json',{method:'GET',headers:{Host:'foreign.example'}}),403,'HOST_REFUSED');assert.equal(h.assets.length+h.upstream.length,0);});
test('native origin list derives exactly from current Capacitor platform settings',()=>{assert.equal(capacitor.appId,'com.mycompany.avarynalpha');assert.deepEqual(NATIVE_ORIGINS,['capacitor://localhost','https://localhost']);assert.equal(NATIVE_ORIGINS.includes('com.mycompany.avarynalpha://auth'),false);});
for(const origin of ['https://foreign.example','null','http://localhost','https://localhost:443','capacitor://127.0.0.1','com.mycompany.avarynalpha://auth'])test('foreign/noncanonical origin denied: '+origin,async()=>{const h=harness();await expectCode(await h.call('/api/auth/v1/signup',{origin,auth:null}),403,'ORIGIN_REFUSED');assert.equal(h.upstream.length,0);});
for(const origin of [ORIGIN,...NATIVE_ORIGINS])test('exact allowed origin preflight and authenticated request: '+origin,async()=>{
 const h=harness();const p=await h.call('/api/rest/v1/rpc/list_c010_horses',{method:'OPTIONS',origin,auth:null,headers:{'access-control-request-method':'POST','access-control-request-headers':'Authorization, Content-Type, X-Supabase-Api-Version'}});
 assert.equal(p.status,204);assert.equal(p.headers.get('access-control-allow-origin'),origin);assert.equal(p.headers.get('access-control-allow-credentials'),null);
 const r=await h.call('/api/rest/v1/rpc/list_c010_horses',{origin,headers:{'sec-fetch-site':origin===ORIGIN?'same-origin':'cross-site'}});assert.equal(r.status,200);assert.equal(r.headers.get('access-control-allow-origin'),origin);assert.equal(h.upstream.length,1);
});
test('invalid preflight methods, paths or custom secret headers are refused',async()=>{for(const [path,method,asked] of [['/api/rest/v1/private_table','POST','content-type'],['/api/rest/v1/rpc/list_c010_horses','DELETE','authorization'],['/api/rest/v1/rpc/list_c010_horses','POST','x-avaryn-preview-secret']]){const h=harness();await expectCode(await h.call(path,{method:'OPTIONS',auth:null,headers:{'access-control-request-method':method,'access-control-request-headers':asked}}),403,'PREFLIGHT_REFUSED');assert.equal(h.upstream.length,0);}});
test('web cross-site context cannot claim a same-origin request',async()=>{const h=harness();await expectCode(await h.call('/api/rest/v1/rpc/list_c010_horses',{headers:{'sec-fetch-site':'cross-site'}}),403,'ORIGIN_REFUSED');});
test('state-changing request without explicit allowed Origin is refused',async()=>{const h=harness();await expectCode(await h.call('/api/auth/v1/token?grant_type=password',{origin:null,auth:null}),403,'ORIGIN_REQUIRED');assert.equal(h.upstream.length,0);});
test('every configured RPC goes to the fixed pilot with unchanged JSON parameters',async()=>{
 const h=harness();h.env.UPSTREAM='https://untrusted.example';h.env.PREVIEW_UPSTREAM='http://127.0.0.1:1';
 for(const name of routes){const r=await h.call('/api/rest/v1/rpc/'+name,{body:'{"p_probe":"synthetic"}'});assert.equal(r.status,200);const sent=h.upstream.at(-1);assert.equal(sent.url,PILOT_UPSTREAM+'/rest/v1/rpc/'+name);assert.deepEqual(JSON.parse(new TextDecoder().decode(sent.init.body)),{p_probe:'synthetic'});}
 assert.equal(h.upstream.length,routes.length);
});
for(const path of ['/api/rest/v1/rpc/list_c010_horses','/api/auth/v1/user','/api/auth/v1/logout?scope=local','/api/functions/v1/media-assets',media()])test('protected endpoint requires user bearer: '+path.split('?')[0],async()=>{const h=harness();await expectCode(await h.call(path,{auth:null,method:path.includes('/user')||path.includes('/storage/')?'GET':'POST'}),401,'AUTH_REQUIRED');assert.equal(h.upstream.length,0);});
test('caller keys, cookies and proxy/identity headers never reach pilot',async()=>{
 const h=harness();await h.call('/api/rest/v1/rpc/list_c010_horses',{headers:{apikey:'caller-key',Cookie:'private-session',Origin:ORIGIN,'X-Forwarded-Host':'foreign','X-Forwarded-For':'1.2.3.4','X-Avaryn-Preview-Secret':'stale-secret','Oai-Authenticated-User-Id':'forged','Prefer':'return=representation','X-Supabase-Api-Version':'spoofed','Referer':ORIGIN+'/?token=private'}});
 const sent=h.upstream[0].init;assert.deepEqual(Object.fromEntries(sent.headers),{'apikey':KEY,authorization:JWT,'content-type':'application/json','x-supabase-api-version':'2024-01-01'});assert.equal(sent.redirect,'manual');assert.equal(sent.credentials,'omit');
});
test('public password/refresh and self-registration flows do not require a tester list',async()=>{
 const h=harness();for(const path of ['/auth/v1/token?grant_type=password','/auth/v1/token?grant_type=refresh_token','/auth/v1/signup','/auth/v1/recover','/auth/v1/resend','/auth/v1/verify']){const r=await h.call('/api'+path,{auth:null,body:'{"email":"own-registration@example.test"}'});assert.equal(r.status,200);assert.equal(h.upstream.at(-1).init.headers.has('authorization'),false);}assert.equal(h.upstream.length,6);
});
test('ordinary logout is local scope; global/other/missing scopes are not exposed',async()=>{const h=harness();assert.equal((await h.call('/api/auth/v1/logout?scope=local')).status,200);for(const query of ['','?scope=global','?scope=others','?scope=local&scope=global','?scope=local&extra=1'])await expectCode(await h.call('/api/auth/v1/logout'+query),404,'NOT_FOUND');assert.equal(h.upstream.length,1);});
test('admin, direct tables, arbitrary Edge, SMTP and extra query surfaces stay closed',async()=>{const h=harness();for(const path of ['/api/auth/v1/admin/users','/api/auth/v1/settings','/api/auth/v1/token?grant_type=client_credentials','/api/auth/v1/signup?redirect_to=https://foreign.example','/api/rest/v1/profiles','/api/rest/v1/rpc/unknown','/api/rest/v1/rpc/list_c010_horses?select=*','/api/functions/v1/arbitrary','/api/functions/v1/stable-invitations','/api/storage/v1/bucket','/api/mail'])assert.equal((await h.call(path)).status,404);assert.equal(h.upstream.length,0);});
test('encoded path separators, double encodings and nested paths cannot reach an upstream route',async()=>{const h=harness();for(const path of ['/api/rest/v1/rpc%2flist_c010_horses','/api/%252e%252e/auth/v1/user','/api//auth/v1/user','/api/rest/v1/rpc/list_c010_horses/extra'])assert.ok([400,404].includes((await h.call(path)).status));assert.equal(h.upstream.length,0);});
test('invalid JSON, array/scalar bodies and compressed content are refused before upstream',async()=>{const h=harness();for(const body of ['{bad','[]','null','"string"'])await expectCode(await h.call('/api/auth/v1/signup',{body,auth:null}),400,'INVALID_REQUEST');await expectCode(await h.call('/api/auth/v1/signup',{body:'{}',headers:{'content-encoding':'gzip'},auth:null}),415,'CONTENT_ENCODING_REFUSED');assert.equal(h.upstream.length,0);});
test('canonical media actions only and explicit personal delete only',async()=>{
 const h=harness();for(const action of ['canonical_create','canonical_finalize','canonical_download'])assert.equal((await h.call('/api/functions/v1/media-assets',{body:JSON.stringify({action})})).status,200);
 await expectCode(await h.call('/api/functions/v1/media-assets',{body:'{"action":"service_finalize"}'}),400,'UNKNOWN_ACTION');
 for(const body of [{},{action:'resume',request_id:ID},{action:'delete',request_id:ID,other:true}])await expectCode(await h.call('/api/functions/v1/delete-account',{body:JSON.stringify(body)}),400,'DELETION_CONFIRMATION_REQUIRED');
 assert.equal((await h.call('/api/functions/v1/delete-account',{body:JSON.stringify({action:'delete',request_id:ID})})).status,200);assert.equal(h.upstream.length,4);
});
for(const type of ['image/png','image/jpeg','image/webp'])test('signed upload exact bucket/variant preserves '+type+' bytes',async()=>{const h=harness(),bytes=new Uint8Array([1,2,3,4]);const r=await h.call(media('upload/sign'),{method:'PUT',headers:{'content-type':type},body:bytes});assert.equal(r.status,200);assert.deepEqual(h.upstream[0].init.body,bytes);assert.equal(h.upstream[0].init.headers.get('content-type'),type);});
test('signed download returns exact bytes and strips remote cache/cookie/location-like state',async()=>{const bytes=new Uint8Array([137,80,78,71]);const h=harness({upstream:()=>new Response(bytes,{headers:{'content-type':'image/png','set-cookie':'private','cache-control':'public,max-age=600','x-internal-secret':'not-forwarded'}})});const r=await h.call(media(),{method:'GET'});assert.deepEqual(new Uint8Array(await r.arrayBuffer()),bytes);assert.equal(r.headers.get('set-cookie'),null);assert.equal(r.headers.get('x-internal-secret'),null);assert.equal(r.headers.get('cache-control'),'no-store');});
test('other bucket/variant, missing/extra tokens, public storage and media HEAD are closed',async()=>{const h=harness();for(const path of [media().replace('horse-media','avatars'),media().replace('original','preview'),media().split('?')[0],media()+'&extra=1',media()+'&token=other',media().replace('/object/sign/','/object/public/')])assert.equal((await h.call(path,{method:'GET'})).status,404);assert.equal((await h.call(media(),{method:'HEAD'})).status,404);assert.equal(h.upstream.length,0);});
test('upload MIME and declared/actual JSON size limits reject before forwarding',async()=>{const h=harness();await expectCode(await h.call(media('upload/sign'),{method:'PUT',headers:{'content-type':'text/plain'},body:'invalid'}),415,'PHOTO_INPUT_INVALID');await expectCode(await h.call('/api/auth/v1/signup',{auth:null,headers:{'content-length':String(1024*1024+1)}}),413,'REQUEST_TOO_LARGE');await expectCode(await h.call('/api/auth/v1/signup',{auth:null,body:'x'.repeat(1024*1024+1)}),413,'REQUEST_TOO_LARGE');assert.equal(h.upstream.length,0);});
test('thumbnail one MiB and original ten MiB caps are independent',async()=>{const h=harness();await expectCode(await h.call(media('upload/sign','thumbnail'),{method:'PUT',headers:{'content-type':'image/png'},body:new Uint8Array(1024*1024+1)}),413,'REQUEST_TOO_LARGE');assert.equal((await h.call(media('upload/sign','original'),{method:'PUT',headers:{'content-type':'image/png'},body:new Uint8Array(1024*1024+1)})).status,200);await expectCode(await h.call(media('upload/sign','original'),{method:'PUT',headers:{'content-type':'image/png','content-length':String(10*1024*1024+1)},body:new Uint8Array(1)}),413,'REQUEST_TOO_LARGE');assert.equal(h.upstream.length,1);});
test('slow upload body has absolute deadline and cancellation, with no upstream call',async()=>{let cancelled=false;const h=harness({timeoutMs:15}),body=new ReadableStream({start(c){c.enqueue(new TextEncoder().encode('{'));},cancel(){cancelled=true;}});await expectCode(await h.call('/api/auth/v1/signup',{auth:null,body}),408,'REQUEST_TIMEOUT');assert.equal(cancelled,true);assert.equal(h.upstream.length,0);});
test('nonresponding fetch is bounded even when an injected transport ignores AbortSignal',async()=>{const h=harness({timeoutMs:15,upstream:()=>new Promise(()=>{})});await expectCode(await h.call('/api/auth/v1/signup',{auth:null}),504,'UPSTREAM_TIMEOUT');assert.equal(h.upstream[0].init.signal.aborted,true);});
test('slow response stream is cancelled within total proxy deadline',async()=>{let cancelled=false;const h=harness({timeoutMs:15,upstream:()=>new Response(new ReadableStream({start(c){c.enqueue(new Uint8Array([123]));},cancel(){cancelled=true;}}),{headers:{'content-type':'application/json'}})});await expectCode(await h.call('/api/auth/v1/signup',{auth:null}),504,'UPSTREAM_TIMEOUT');assert.equal(cancelled,true);});
test('oversized response is cancelled and never partially exposed',async()=>{let cancelled=false;const h=harness({upstream:()=>new Response(new ReadableStream({start(c){c.enqueue(new Uint8Array(10*1024*1024+1));},cancel(){cancelled=true;}}))});await expectCode(await h.call('/api/rest/v1/rpc/list_c010_horses'),502,'RESPONSE_TOO_LARGE');assert.equal(cancelled,true);});
test('any upstream redirect/Location is rejected and is never followed',async()=>{for(const [status,location] of [[302,'https://foreign.example/'],[307,PILOT_UPSTREAM+'/auth/v1/user'],[200,'/unexpected']]){const h=harness({upstream:()=>new Response('',{status,headers:{location}})});await expectCode(await h.call('/api/auth/v1/signup',{auth:null}),502,'UPSTREAM_REDIRECT_REFUSED');assert.equal(h.upstream.length,1);}});
test('transport errors never expose keys, signed URLs or internal error text',async()=>{const h=harness({upstream:()=>{throw Error(KEY+' '+PILOT_UPSTREAM+media()+' private-error');}});const r=await h.call('/api/auth/v1/signup',{auth:null}),body=await r.text();assert.equal(r.status,503);for(const part of [KEY,PILOT_UPSTREAM,'synthetic.signed.token','private-error'])assert.equal(body.includes(part),false);});
test('Auth/CAS/pending codes and JSON remain intact with private headers discarded',async()=>{for(const [status,body] of [[400,{code:'invalid_credentials'}],[409,{code:'PT409',message:'STALE_TASK_VERSION'}],[202,{code:'ACCOUNT_DELETION_PENDING',request_id:ID}]]){const h=harness({upstream:()=>json(body,status,{'set-cookie':'nope','x-supabase-api-version':'2024-01-01','access-control-allow-origin':'*'})});const r=await h.call('/api/rest/v1/rpc/list_c010_horses');assert.equal(r.status,status);assert.deepEqual(await r.json(),body);assert.equal(r.headers.get('access-control-allow-origin'),ORIGIN);assert.equal(r.headers.get('set-cookie'),null);}});
test('local logout 204 remains bodyless',async()=>{const h=harness({upstream:()=>new Response(null,{status:204})}),r=await h.call('/api/auth/v1/logout?scope=local');assert.equal(r.status,204);assert.equal(await r.text(),'');});
test('HTML returned from signed media is not exposed as an image',async()=>{const h=harness({upstream:()=>new Response('<script>x</script>',{headers:{'content-type':'text/html'}})});await expectCode(await h.call(media(),{method:'GET'}),502,'INVALID_MEDIA_RESPONSE');});
test('only current derived public filenames/assets/licenses enter the asset binding',async()=>{const h=harness();for(const path of ['/app-ABCDEFG1.js','/chunk-A1B2C3D4.js','/menu-ui.css','/assets/orion.png','/assets/fonts/Inter.ttf','/assets/fonts/inter-OFL.txt'])assert.equal((await h.call(path,{method:'GET',auth:null})).status,200);assert.equal(h.assets.length,6);});
test('private/source/config/test/metadata files cannot be returned by ASSETS',async()=>{const h=harness();for(const path of ['/.env','/server/worker.js','/config/release.json','/build-manifest.json','/_preview/toegang','/private/accounts.json','/test/unit.js','/app.js','/app-ABCDEFG1.js.map','/assets/private/key.txt','/assets/.env','/dump.sql','/backup.tar.gz','/unknown-route'])assert.equal((await h.call(path,{method:'GET',auth:null})).status,404);assert.equal(h.assets.length,0);});
test('cold callback/document paths fetch canonical root, stripping token queries and all identity headers',async()=>{const h=harness();for(const path of ['/auth/callback?token_hash=private-code&type=email','/auth/reset-password?token_hash=private-code&type=recovery','/uitnodiging?invitation=one-time','/index.html']){const r=await h.call(path,{method:'GET',headers:{cookie:'private'},auth:JWT});assert.equal(r.status,200);const sent=h.assets.at(-1);assert.equal(sent.url,ORIGIN+'/');assert.deepEqual([...sent.headers],[]);assert.equal(r.headers.get('location'),null);}});
for(const path of ['/','/index.html','/auth/callback','/auth/reset-password','/uitnodiging'])test('external document navigation loads only the existing shell: '+path,async()=>{
 const h=harness(),r=await h.call(path+'?token_hash=synthetic-email-code&type=email',{method:'GET',origin:null,auth:null,headers:{'sec-fetch-site':'cross-site','sec-fetch-mode':'navigate','sec-fetch-dest':'document','referer':'https://mail.google.com/mail/','cookie':'synthetic-browser-cookie'}});
 assert.equal(r.status,200);assert.equal(await r.text(),'<html>AVARYN</html>');assert.equal(h.upstream.length,0);assert.equal(h.assets.length,1);assert.equal(h.assets[0].url,ORIGIN+'/');assert.equal(h.assets[0].method,'GET');assert.deepEqual([...h.assets[0].headers],[]);assert.equal(r.headers.get('access-control-allow-origin'),null);assert.equal(r.headers.get('cache-control'),'no-store');assert.equal(r.headers.get('referrer-policy'),'no-referrer');assert.equal(r.headers.get('location'),null);
});
test('foreign Origin on shell navigation neither grants CORS nor forwards tokens or user headers',async()=>{
 const h=harness(),r=await h.call('/auth/callback?token_hash=synthetic-email-code&type=email',{method:'GET',origin:'https://mail.google.com',headers:{'sec-fetch-site':'cross-site','sec-fetch-mode':'navigate','sec-fetch-dest':'document',cookie:'synthetic-cookie',apikey:'synthetic-caller-key'}});
 assert.equal(r.status,200);assert.equal(r.headers.get('access-control-allow-origin'),null);assert.equal(r.headers.get('access-control-allow-credentials'),null);assert.equal(h.upstream.length,0);assert.equal(h.assets[0].url,ORIGIN+'/');assert.deepEqual([...h.assets[0].headers],[]);
});
test('cross-site shell fetches, frames and non-GET methods remain refused',async()=>{
 for(const [method,mode,dest] of [['GET',null,null],['GET','cors','document'],['GET','no-cors','document'],['GET','navigate','iframe'],['GET','navigate','empty'],['GET','navigate',null],['POST','navigate','document'],['HEAD','navigate','document'],['OPTIONS','navigate','document']]){
  const h=harness(),headers={'sec-fetch-site':'cross-site'};if(mode)headers['sec-fetch-mode']=mode;if(dest)headers['sec-fetch-dest']=dest;
  await expectCode(await h.call('/auth/callback',{method,origin:null,auth:null,headers}),403,'ORIGIN_REFUSED');assert.equal(h.assets.length+h.upstream.length,0);
 }
});
test('navigation metadata never opens cross-site API, runtime, assets or unknown shell paths',async()=>{
 const headers={'sec-fetch-site':'cross-site','sec-fetch-mode':'navigate','sec-fetch-dest':'document'};
 for(const [path,method] of [['/api/auth/v1/user','GET'],[media(),'GET'],['/api/auth/v1/signup','POST'],['/api/rest/v1/rpc/list_c010_horses','POST'],['/api/functions/v1/delete-account','POST'],['/runtime.json','GET'],['/version.json','GET'],['/app-ABCDEFG1.js','GET'],['/assets/orion.png','GET'],['/auth/callback/extra','GET'],['/unknown-route','GET']]){
  const h=harness();await expectCode(await h.call(path,{method,headers}),403,'ORIGIN_REFUSED');assert.equal(h.assets.length+h.upstream.length,0);
 }
});
test('document navigation cannot bypass host and malformed-path checks',async()=>{
 const h=harness(),headers={'sec-fetch-site':'cross-site','sec-fetch-mode':'navigate','sec-fetch-dest':'document'};
 await expectCode(await h.worker.fetch(new Request('https://foreign.example/auth/callback',{headers}),h.env),403,'HOST_REFUSED');
 await expectCode(await h.call('/auth/callback',{method:'GET',origin:null,headers:{...headers,Host:'foreign.example'}}),403,'HOST_REFUSED');
 await expectCode(await h.call('/auth%2fcallback',{method:'GET',origin:null,headers}),400,'INVALID_PATH');assert.equal(h.assets.length+h.upstream.length,0);
});
test('ASSETS redirect and exception are contained without secret leakage',async()=>{const h=harness();h.env.ASSETS.fetch=async()=>new Response('',{status:307,headers:{location:'https://foreign.example/'}});await expectCode(await h.call('/',{method:'GET'}),502,'ASSET_REDIRECT_REFUSED');h.env.ASSETS.fetch=async()=>{throw Error(KEY);};const r=await h.call('/',{method:'GET'});assert.equal(r.status,503);assert.equal((await r.text()).includes(KEY),false);});
test('HEAD assets discard unexpected response streams without reading or retaining bytes',async()=>{let cancelled=false;const h=harness();h.env.ASSETS.fetch=async()=>new Response(new ReadableStream({cancel(){cancelled=true;}}));const r=await h.call('/',{method:'HEAD',auth:null});assert.equal(r.status,200);assert.equal(await r.text(),'');assert.equal(cancelled,true);});
test('already-expired stream read cancels without a dangling rejected read',async()=>{let cancelled=false;const c=new AbortController();c.abort();const stream=new ReadableStream({cancel(){cancelled=true;}});await assert.rejects(limitedBytes(stream,1024,c.signal),e=>e.code==='TIMEOUT');assert.equal(cancelled,true);});
