import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createHorseResidency} from '../../../apps/avaryn/src/horse-residency.js';
import {createActivityEditor} from '../../../apps/avaryn/src/activity-form.js';
import {createAuthorityTransfer} from '../../../apps/avaryn/src/authority-transfer.js';
import {browserDay} from '../../../apps/avaryn/src/browser-clock.js';
import {createAccountCore} from '../../../apps/avaryn/src/account-core.js';
import {createTeamCore,invitationToken} from '../../../apps/avaryn/src/team-core.js';
import {esc,icon} from '../../../apps/avaryn/src/components.js';

// Evaluate the complete production controller with injected I/O. No copied controller logic.
const controllerSource=readFileSync(new URL('../../../apps/avaryn/src/backend-controller.js',import.meta.url),'utf8');
const factorySource=controllerSource.replace(/^import .*;\n/gm,'').replace('export function createBackendController','function createBackendController');
const dependencyNames=['createHorseResidency','createActivityEditor','createAuthorityTransfer','browserDay','PRODUCT','createAccountCore','createTeamCore','createBackendClient','createFeedingEditor','renderTaskForm','renderAuth','consumeEmailCallback','taskToday','taskFormValues','renderLogin','loginPending','getPersona','canPlan','canCreateTask','canEditFeeding','esc','icon','INITIAL_STATE','initFacilities'];
const injectedFactory=new Function(...dependencyNames,`${factorySource}\nreturn createBackendController;`);
const tick=async()=>{for(let i=0;i<5;i++)await new Promise(resolve=>setImmediate(resolve));};
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};};
const decode=s=>String(s??'').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&');
function fixture(){return {today:'2026-09-11',selectedDay:'2026-09-11',route:'today',theme:'light',horses:[],activities:[],tasks:[],feeding:{},team:[{id:'profile-member',membershipId:'membership-1',rowVersion:4,roleCode:'groom',name:'<Member>',initials:'MM',role:'Groom'}],stableName:'Stal',backend:{connected:true,actor:{id:'actor-a'},organizationId:'org-a',organization:{id:'org-a',name:'Stal',row_version:3,primary_authority_profile_id:'profile-primary'},profile:{profile_id:'profile-a',row_version:7,first_name:'Voor',last_name:'Naam',locale:'nl-NL',time_zone:'Europe/Amsterdam',theme_mode:'dark',onboarding_completed_at:'2026-09-01',onboarding_intent:'individualHorse',avatar_object_path:'avatar/current'},capabilities:{canManage:true,canViewTeam:true},permissionCodes:{'organization.invitations.manage':true,'organization.memberships.manage':true,'organization.roles.manage':true},roles:[{code:'manager',name:'Beheerder'},{code:'groom',name:'Verzorger'}],invitations:[{id:'invite-1',status:'pending',row_version:2,recipient_label:'Ontvanger',role_name:'Groom',expires_at:'2026-09-18'}],organizations:[{id:'org-a',name:'Stal'},{id:'org-b',name:'Andere stal'}],todayDate:'2026-09-11',todayItems:[]}};}
function harness(t){
 let state=fixture(),form=null;const shown=[],toasts=[],calls=[],loads=[],stored=[],navigations=[];let rpcImpl=async()=>null,loadImpl=async()=>structuredClone(state),view=0;
 const modal={open:false,dataset:{viewId:'0'},contains:f=>modal.open&&form===f&&f.isConnected};
 const old=new Map(['document','FormData','localStorage','location','history'].map(k=>[k,Object.getOwnPropertyDescriptor(globalThis,k)]));
 const errorNode=()=>({textContent:'',append(text){this.textContent+=text;},setAttribute(){},scrollIntoView(){},insertAdjacentHTML(){}});
 function showModal(title,body='',buttons='',caption=''){
  if(form)form.isConnected=false;modal.open=true;modal.dataset.viewId=String(++view);shown.push({title,body,buttons,caption});
  const match=body.match(/<form\b([^>]*)>/);form=null;if(!match)return;
  const attrs=match[1],controls=[];const dataset={};for(const m of attrs.matchAll(/data-([\w-]+)="([^"]*)"/g))dataset[m[1].replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=decode(m[2]);
  for(const m of body.matchAll(/<(input|textarea|select)\b([^>]*)(?:>([\s\S]*?)<\/\1>|>)/g)){
   const name=m[2].match(/\bname="([^"]+)"/)?.[1];if(!name)continue;
   let value=m[2].match(/\bvalue="([^"]*)"/)?.[1]||'';
   if(m[1]==='textarea')value=m[3]||'';
   if(m[1]==='select'){const opts=[...(m[3]||'').matchAll(/<option([^>]*)>([^<]*)<\/option>/g)];const opt=opts.find(o=>/\bselected\b/.test(o[1]))||opts[0];value=opt?.[1].match(/value="([^"]*)"/)?.[1]??opt?.[2]??'';}
   controls.push({name,value:decode(value),tagName:m[1].toUpperCase(),disabled:/\bdisabled\b/.test(m[2]),type:m[2].match(/type="([^"]*)"/)?.[1]||'text'});
  }
  const submit={tagName:'BUTTON',type:'submit',disabled:false};controls.push(submit);let error=errorNode();
  form={getAttribute(name){return name==='id'?this.id:null;},id:attrs.match(/\bid="([^"]+)"/)?.[1],dataset,controls,isConnected:true,querySelector:q=>q==='.form-error'?error:q.includes('submit')?submit:controls.find(c=>q===`[name="${c.name}"]`)||null,querySelectorAll:()=>controls,prepend:e=>{error=e;},closest:q=>q==='#modal'?modal:null};
 }
 globalThis.document={querySelector:q=>q==='#modal'?modal:q==='#modal form'?form:null,getElementById:id=>id==='modal'?modal:form?.id===id?form:null,createElement:errorNode};
 // Native successful-control semantics: disabled values are absent on retries.
 globalThis.FormData=class{constructor(f){this.entries=f.controls.filter(c=>c.name&&!c.disabled).map(c=>[c.name,c.value]);}[Symbol.iterator](){return this.entries[Symbol.iterator]();}get(k){return this.entries.find(([name])=>name===k)?.[1]??null;}};
 globalThis.localStorage={getItem:()=>null,setItem:(k,v)=>stored.push([k,v]),removeItem(){}};
 globalThis.location={origin:'https://app.avaryn.example',pathname:'/',href:'https://app.avaryn.example/'};
 globalThis.history={state:null,replaceState:(...args)=>stored.push(['history',args])};
 const client={requestRpc:async(name,args,options)=>{calls.push({name,args,options});return rpcImpl(name,args,options);},load:async args=>{loads.push(args);return loadImpl(args);},logout:async()=>{}};
 const controller=injectedFactory(createHorseResidency,createActivityEditor,createAuthorityTransfer,browserDay,{demo:false,apiBase:'/api'},createAccountCore,createTeamCore,()=>client,()=>({handleAction:()=>false,handleSubmit:()=>false}),()=>'',()=>'',()=>null,s=>s.today,x=>x,()=>'',()=>'',s=>s.backend.actor,()=>true,()=>true,()=>true,esc,icon,{},()=>{})({getState:()=>state,setState:s=>{state=s;},render(){},save(){},navigate:route=>{navigations.push(route);state.route=route;modal.open=false;if(form)form.isConnected=false;},showModal,closeModal:()=>{modal.open=false;if(form)form.isConnected=false;},toast:text=>toasts.push(text)});
 t.after(()=>{for(const [key,desc] of old)if(desc)Object.defineProperty(globalThis,key,desc);else delete globalThis[key];});
 return {controller,shown,toasts,calls,loads,stored,navigations,modal,get state(){return state;},set state(s){state=s;},get form(){return form;},rpc:fn=>{rpcImpl=fn;},readback:fn=>{loadImpl=fn;},showModal,open:(action,data={})=>controller.handleAction(action,{dataset:data}),fill(values,f=form){for(const [k,v] of Object.entries(values)){const c=f.controls.find(c=>c.name===k);assert.ok(c,`rendered field ${k}`);c.value=v;}},async submit(f=form){controller.handleSubmit(f,{preventDefault(){}});await tick();},async settle(){await tick();}};
}

const TOKEN='a'.repeat(64),OTHER='b'.repeat(64),ORIGIN='https://app.avaryn.example';
function invite(h){h.open('team-invite');h.fill({email:' target@example.invalid ',role:'groom'});}
async function response(h){h.open('open-invitation');h.fill({invitation:TOKEN});h.rpc(async name=>name==='preview_organization_invitation'?[{organization_id:'org-a',organization_name:'Eigen stal',role_name:'Groom'}]:[{status:'accepted'}]);await h.submit();assert.equal(h.form.id,'core-invite-response-form');}
test('invitation accepts only exact local application origin/path and one token',()=>{assert.equal(invitationToken(TOKEN,ORIGIN),TOKEN);assert.equal(invitationToken(`${ORIGIN}/uitnodiging?invitation=${TOKEN}`,ORIGIN),TOKEN);for(const value of [`https://foreign.example/uitnodiging?invitation=${TOKEN}`,`${ORIGIN}/other?invitation=${TOKEN}`,`${ORIGIN}/uitnodiging?invitation=${TOKEN}#x`,`${ORIGIN}/uitnodiging?invitation=${TOKEN}&invitation=${OTHER}`,`${ORIGIN}/uitnodiging?invitation=${TOKEN}&extra=1`,'short',TOKEN.toUpperCase()])assert.equal(invitationToken(value,ORIGIN),null);});
test('invitation role options are server catalog values and exact target email is sent',async t=>{const h=harness(t);invite(h);assert.match(h.shown.at(-1).body,/value="groom"/);assert.doesNotMatch(h.shown.at(-1).body,/value="owner"/);h.rpc(async()=>({invitation_id:'invite-new',invitation_token:TOKEN}));await h.submit();const c=h.calls[0];assert.equal(c.name,'create_c010_stable_invitation');assert.equal(c.args.p_organization_id,'org-a');assert.equal(c.args.p_target_email,'target@example.invalid');assert.equal(c.args.p_role_code,'groom');assert.equal(c.options.write,true);assert.ok(Date.parse(c.args.p_expires_at)>Date.now());});
test('invitation management and team listing respect separate current server capabilities',t=>{const h=harness(t);h.state.backend.permissionCodes['organization.invitations.manage']=false;h.open('team-invite');assert.equal(h.form,null);h.state.backend.capabilities.canViewTeam=false;h.open('team');assert.equal(h.shown.length,0);});
test('primary authority cannot be offered membership mutation',t=>{const h=harness(t);h.state.backend.organization.primary_authority_profile_id='profile-member';h.open('team-member',{id:'membership-1'});assert.equal(h.form,null);h.open('team');assert.doesNotMatch(h.shown.at(-1).body,/data-action="team-member"/);});
test('memberships permission without role permission exposes revoke, not role mutation',t=>{const h=harness(t);h.state.backend.permissionCodes['organization.roles.manage']=false;h.open('team-member',{id:'membership-1'});assert.match(h.shown.at(-1).body,/value="revoke"/);assert.doesNotMatch(h.shown.at(-1).body,/name="role"|value="role"/);});
test('member names and role labels are HTML escaped in rendered team',t=>{const h=harness(t);h.open('team');assert.match(h.shown.at(-1).body,/&lt;Member&gt;/);assert.doesNotMatch(h.shown.at(-1).body,/<Member>/);});
test('role mutation uses captured membership CAS and server-selected role',async t=>{const h=harness(t);h.open('team-member',{id:'membership-1'});h.fill({role:'groom',change:'role'});h.rpc(async()=>({organization_id:'org-a',membership_id:'membership-1',membership_row_version:5,role_code:'groom',status:'ended',row_version:5}));await h.submit();assert.equal(h.calls[0].name,'set_c010_team_role');assert.equal(h.calls[0].args.p_expected_membership_row_version,4);assert.equal(h.calls[0].args.p_role_code,'groom');});
test('membership revoke uses its distinct canonical version parameter',async t=>{const h=harness(t);h.open('team-member',{id:'membership-1'});h.fill({change:'revoke'});h.rpc(async()=>({organization_id:'org-a',membership_id:'membership-1',membership_row_version:5,role_code:'groom',status:'ended',row_version:5}));await h.submit();assert.equal(h.calls[0].name,'revoke_c010_membership');assert.equal(h.calls[0].args.p_expected_row_version,4);assert.equal(h.calls[0].args.p_role_code,undefined);});
test('unknown invitation write retries exact email/role/expiry/request with disabled controls',async t=>{const h=harness(t);invite(h);let count=0;h.rpc(async()=>{if(!count++)throw Object.assign(Error('Connection interrupted'),{uncertain:true});return {invitation_id:'invite-new',invitation_token:TOKEN};});await h.submit();const old=h.form;assert.equal(old.controls.find(c=>c.name==='email').disabled,true);await h.submit(old);assert.equal(h.calls.length,2);assert.deepEqual(h.calls[1],h.calls[0]);assert.equal(h.shown.at(-1).title,'Uitnodiging klaar');});
test('successful invitation plus failed readback does not create twice or lose one-time link',async t=>{const h=harness(t);invite(h);h.rpc(async()=>({invitation_id:'invite-new',invitation_token:TOKEN}));let count=0;h.readback(async()=>{if(!count++)throw Error('readback unavailable');return structuredClone(h.state);});await h.submit();const old=h.form;assert.equal(h.toasts.length,0);await h.submit(old);assert.equal(h.calls.length,1);assert.match(h.shown.at(-1).body,new RegExp(TOKEN));assert.equal(h.loads.length,2);});
test('invitation success exposes token only in current modal, no email-send claim or persistence',async t=>{const h=harness(t);invite(h);h.rpc(async()=>({invitation_id:'invite-new',invitation_token:TOKEN}));await h.submit();assert.match(h.shown.at(-1).body,/Er is geen e-mail verstuurd/);assert.equal(JSON.stringify(h.stored).includes(TOKEN),false);assert.equal(JSON.stringify(h.toasts).includes(TOKEN),false);h.open('team');assert.equal(JSON.stringify(h.shown.at(-1)).includes(TOKEN),false);});
test('idempotent create acknowledgement without recoverable token does not invent a link',async t=>{const h=harness(t);invite(h);h.rpc(async()=>({invitation_id:'invite-new',invitation_token:null}));await h.submit();assert.equal(h.shown.at(-1).title,'Open uitnodiging');assert.doesNotMatch(h.shown.at(-1).body,/\/uitnodiging\?/);});
test('preview is read-only and late result cannot replace a different modal',async t=>{const h=harness(t);h.open('open-invitation');h.fill({invitation:TOKEN});const d=deferred();h.rpc(()=>d.promise);await h.submit();h.open('team-invite');d.resolve([{organization_id:'org-a',organization_name:'Late',role_name:'Groom'}]);await h.settle();assert.equal(h.form.id,'core-invite-form');assert.equal(h.calls[0].options.write,false);});
test('late invitation preview after actor change never exposes preview details',async t=>{const h=harness(t);h.open('open-invitation');h.fill({invitation:TOKEN});const d=deferred();h.rpc(()=>d.promise);await h.submit();h.state.backend.actor.id='actor-b';d.resolve([{organization_id:'org-a',organization_name:'Hidden',role_name:'Groom'}]);await h.settle();assert.equal(h.shown.length,1);});
test('accepted one-time invitation reload failure retries readback, not consumed token',async t=>{const h=harness(t);await response(h);let count=0;h.readback(async()=>{if(!count++)throw Error('readback unavailable');return structuredClone(h.state);});await h.submit();const f=h.form;assert.equal(f.dataset.uncertain,'true');await h.submit(f);assert.equal(h.calls.filter(c=>c.name==='respond_stable_invitation').length,1);assert.equal(h.calls.at(-1).args.p_action,'accept');assert.equal(h.loads.at(-1).organizationId,'org-a');});
test('invalid invitation response acknowledgement is uncertain with no success',async t=>{const h=harness(t);await response(h);h.rpc(async()=>[{status:'pending'}]);await h.submit();assert.equal(h.toasts.length,0);assert.equal(h.form.dataset.uncertain,'true');});
test('revocation requires revoked server acknowledgement; accepted or expired is not a success',async t=>{const h=harness(t);h.open('team-revoke-invite',{id:'invite-1'});h.rpc(async()=>[{row_version:3,status:'accepted',applied:false}]);await h.submit();assert.equal(h.toasts.length,0);assert.match(h.form.querySelector('.form-error').textContent,/gewijzigd|actuele/);});
test('revoked invitation acknowledgement reports success after readback',async t=>{const h=harness(t);h.open('team-revoke-invite',{id:'invite-1'});h.rpc(async()=>[{row_version:3,status:'revoked',applied:true}]);await h.submit();assert.equal(h.loads.length,1);assert.deepEqual(h.toasts,['Uitnodiging ingetrokken.']);assert.equal(h.calls[0].args.p_expected_row_version,2);});
test('old team form cannot submit into a different actor or organization',async t=>{const h=harness(t);invite(h);const f=h.form;h.state.backend.actor.id='actor-b';await h.submit(f);assert.equal(h.calls.length,0);h.state.backend.actor.id='actor-a';h.state.backend.organizationId='org-b';await h.submit(f);assert.equal(h.calls.length,0);});
test('replaced invitation form cannot later create another invitation in the same scope',async t=>{const h=harness(t);invite(h);const f=h.form;h.open('team-invite');h.rpc(async()=>({invitation_id:'invite-new',invitation_token:TOKEN}));await h.submit(f);assert.equal(h.calls.length,0);});
test('late invitation acknowledgement after logout never exposes one-time secret',async t=>{const h=harness(t);invite(h);const d=deferred();h.rpc(()=>d.promise);await h.submit();h.open('logout');d.resolve({invitation_id:'invite-new',invitation_token:TOKEN});await h.settle();assert.equal(h.loads.length,0);assert.equal(h.toasts.length,0);assert.equal(JSON.stringify(h.shown).includes(TOKEN),false);});
test('cold link token leaves browser history immediately and resume keeps it only in intended form',t=>{const h=harness(t);const core=createTeamCore({getState:()=>h.state,showModal:h.showModal,perform(){},apiRequest(){},toast(){}});const historyCalls=[];core.consumeLink({origin:ORIGIN,pathname:'/uitnodiging',href:`${ORIGIN}/uitnodiging?invitation=${TOKEN}`},{state:null,replaceState:(...args)=>historyCalls.push(args)});assert.equal(historyCalls[0][2],'/#/vandaag');assert.equal(JSON.stringify(historyCalls).includes(TOKEN),false);core.resume();assert.equal(h.form.controls.find(c=>c.name==='invitation').value,TOKEN);h.open('team');core.resume();assert.equal(h.form,null);});

for(const change of ['role','revoke'])test(`membership ${change} requires a canonical acknowledgement before success`,async t=>{const h=harness(t);h.open('team-member',{id:'membership-1'});h.fill({role:'groom',change});h.rpc(async()=>null);await h.submit();assert.equal(h.toasts.length,0);assert.equal(h.form.dataset.uncertain,'true');});
